import { useState } from 'react';
import { api, tokens } from '../api';
import type { User } from '../types';
import { HalqaOrb, Logo } from '../components/ui';

export default function AuthPage({onAuth}:{onAuth:(user:User)=>void}){
  const [mode,setMode]=useState<'login'|'register'>('login');
  const [form,setForm]=useState({identity:'sana',password:'halqa123',fullName:'',username:'',phone:'',email:''});
  const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const submit=async(event:React.FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{const body=mode==='login'?{identity:form.identity.trim(),password:form.password.trim()}:{fullName:form.fullName.trim(),username:form.username.trim(),phone:form.phone.trim(),email:form.email.trim(),password:form.password.trim()};const data=await api<{user:User;accessToken:string;refreshToken:string}>(`/auth/${mode}`,{method:'POST',body:JSON.stringify(body)});tokens.set(data.accessToken,data.refreshToken);onAuth(data.user)}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  return <main className="auth-layout"><section className="auth-story"><Logo/><div className="auth-copy"><HalqaOrb/><span className="eyebrow">Pakistan's transparent savings network</span><h1>Save together.<br/>Grow with clarity.</h1><p>Locked schedules, visible turns, payment accountability and carefully modelled growth options.</p></div><small>Stage 1 · Record-only prototype · No money held</small></section><section className="auth-form"><div className="auth-card"><div className="mobile-logo"><Logo/></div><h2>{mode==='login'?'Welcome back':'Join your first Halqa'}</h2><p>{mode==='login'?'Sign in using username, phone or email.':'Every account begins with a 700 reliability score.'}</p><form onSubmit={submit}>{mode==='register'&&<><input className="field" placeholder="Full name" value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/><input className="field" placeholder="Username" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/><input className="field" placeholder="03XXXXXXXXX" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input className="field" type="email" placeholder="Email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></>}{mode==='login'&&<input className="field" placeholder="Username, phone or email" value={form.identity} onChange={e=>setForm({...form,identity:e.target.value})}/>}<input className="field" type="password" placeholder="Password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>{error&&<div className="error-box">{error}</div>}<button className="primary" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':'Create account'}</button></form><button className="text-action" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'New to Halqa? Create account':'Already registered? Sign in'}</button>{mode==='login'&&<div className="demo-note"><b>Demo</b><span>sana / halqa123</span></div>}</div></section></main>
}
