import { useEffect, useMemo, useState } from 'react';
import { ChevronLeft, Landmark, Repeat2, ShieldCheck, TrendingUp } from 'lucide-react';
import { api, money } from '../api';
import { emitHalqaAction } from '../lib/events';
import type { Committee, Partner, Scheme, User } from '../types';
import { Field, profitProjection, RateStamp } from '../components/ui';
import { SHOW_BANK_RAIL } from '../config';

type Mode='ROTATING'|'HYBRID'|'INVESTMENT';
const modes=[
  {id:'ROTATING' as Mode,title:'Classic rotating',cap:25,riskCap:3,icon:<Repeat2/>,description:'Most cash reaches each turn-holder. Capital-preservation schemes only.'},
  {id:'HYBRID' as Mode,title:'Hybrid growth',cap:75,riskCap:6,icon:<TrendingUp/>,description:'Balances periodic payouts with a larger, moderate-risk growth reserve.'},
  {id:'INVESTMENT' as Mode,title:'Investment circle',cap:100,riskCap:8,icon:<Landmark/>,description:'No rotating payout. Capital stays invested until the locked maturity.'},
];
const band=(score:number)=>score<=3?'LOW':score<=6?'MEDIUM':score<=8?'HIGH':'EXTREME';
const GOAL_LABELS:Record<string,string>={HAJJ:'Hajj / Umrah',EDUCATION:'Education',WEDDING:'Wedding',HOME:'Home',BUSINESS:'Business',CUSTOM:'Custom goal'};

export default function CreateCirclePage({user,done,cancel}:{user:User;done:(id:string)=>void;cancel:()=>void}){
  const [schemes,setSchemes]=useState<Scheme[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const [partner,setPartner]=useState<Partner|null>(null);const [custody,setCustody]=useState(false);const [guaranteed,setGuaranteed]=useState(false);const slotFee=1;
  // Profit engine is now composable: tick any combination of levers and the
  // named tier is derived at submit. earn = the Sukoon float+deposit base;
  // patience = the Bazaar tilt; earlyFeeOn = the conventional Priority fee.
  const [earn,setEarn]=useState(true);const [patience,setPatience]=useState(true);const [prizeDraw,setPrizeDraw]=useState(false);const [earlyFeeOn,setEarlyFeeOn]=useState(false);const [earlyFeePct,setEarlyFeePct]=useState(10);const [dividendPooled,setDividendPooled]=useState(true);
  const [goalType,setGoalType]=useState('');const [goalName,setGoalName]=useState('');
  // Gold hedge — a simple, prominent way to back the circle with gold without
  // digging into the generic "advanced invest" controls.
  const [goldHedge,setGoldHedge]=useState(false);const [goldPct,setGoldPct]=useState(20);
  // Investing a slice of the pool into a market scheme is now an OPTIONAL,
  // advanced choice — off by default. The circle earns the profit engine
  // (float + deposits) with no scheme or risk decision required.
  const [advanced,setAdvanced]=useState(false);
  const [form,setForm]=useState({name:'',mode:'ROTATING' as Mode,memberCap:6,contribution:25000,cadencePreset:'SHORT',periodDays:30,minMembersToStart:3,reinvestPercent:0,schemeId:'',distributionMode:'SHARE',targetRiskScore:3,payoutBuffer:15,liquidityReserve:10,latePenalty:2,guarantorRequired:false,dynamicDeposit:true,profitCollateral:true,capitalDaysDistribution:true,delayedDistributionDays:0,profitRecycling:false,progressivePenalties:true,payoutHoldbackEnabled:true,holdbackReleasePayments:2,featureLockOnDefault:true,smartNudges:true,peerNudges:true,promissoryNoteRequired:false,autoDebitMandateRequired:false,depositYield:0,insuranceReserve:0,postReceiptPenaltyPoints:200,rehabilitationCooldownMonths:6});
  useEffect(()=>{void api<Scheme[]>('/schemes').then(items=>{setSchemes(items);if(items[0])setForm(value=>({...value,schemeId:items[0].id}))});void api<{partner:Partner|null}>('/partner').then(data=>setPartner(data.partner)).catch(()=>setPartner(null))},[]);
  const selectedMode=modes.find(mode=>mode.id===form.mode)!;
  const effectiveRiskCap=Math.min(selectedMode.riskCap,form.targetRiskScore);
  // Rotating/hybrid circles pay out every period, so a scheme must be liquidatable
  // at least 7 days before payout. Investment circles lock capital until maturity.
  const liquidityLimitDays=form.mode==='INVESTMENT'?Number.MAX_SAFE_INTEGER:Math.max(1,form.periodDays-7);
  const eligible=schemes.filter(item=>item.riskScore<=effectiveRiskCap&&item.liquidityDays<=liquidityLimitDays);
  const hiddenByLiquidity=schemes.filter(item=>item.riskScore<=effectiveRiskCap&&item.liquidityDays>liquidityLimitDays).length;
  const scheme=eligible.find(item=>item.id===form.schemeId)||eligible[0];
  const goldScheme=schemes.find(s=>s.slug==='gold-linked-allocation');
  const cycleDays=form.memberCap*form.periodDays;const gross=form.memberCap*form.contribution;const invested=gross*form.reinvestPercent/100;
  const projected=useMemo(()=>profitProjection(invested,scheme?.indicativeRatePct||0,cycleDays),[invested,scheme,cycleDays]);
  // Derived engine tier from the composable levers (see the state above).
  const engineTier=form.mode==='INVESTMENT'?'CLASSIC':earlyFeeOn?(earn?'SIGMA':'PRIORITY'):earn?(patience?'BAZAAR':'SUKOON'):'CLASSIC';
  const engineName=engineTier==='CLASSIC'?'Classic (no engine)':engineTier==='SIGMA'?'Sigma':engineTier.charAt(0)+engineTier.slice(1).toLowerCase();
  const isShariah=engineTier!=='PRIORITY'&&engineTier!=='SIGMA';
  const effectiveFeePct=engineTier==='SIGMA'?Math.min(10,earlyFeePct):earlyFeePct;
  const setMode=(mode:Mode)=>{const next=modes.find(item=>item.id===mode)!;const nextRisk=Math.min(next.riskCap,form.targetRiskScore);const nextScheme=schemes.find(item=>item.riskScore<=nextRisk);setForm(value=>({...value,mode,targetRiskScore:nextRisk,reinvestPercent:mode==='INVESTMENT'?Math.max(50,Math.min(next.cap,value.reinvestPercent)):Math.min(next.cap,Math.max(1,value.reinvestPercent)),schemeId:nextScheme?.id||''}))};
  // Pick a risk band: lock the ceiling at the top of that band and auto-select
  // the highest-return scheme that fits — "maximise profit within the level".
  const pickRiskBand=(bandScore:number)=>{const target=Math.min(selectedMode.riskCap,bandScore);const ranked=[...schemes].filter(item=>item.riskScore<=target&&item.liquidityDays<=liquidityLimitDays).sort((a,b)=>b.indicativeRatePct-a.indicativeRatePct);setForm(current=>({...current,targetRiskScore:target,schemeId:ranked[0]?.id||current.schemeId}))};
  const setPercent=(value:number)=>setForm(current=>({...current,reinvestPercent:Math.max(current.mode==='INVESTMENT'?50:0,Math.min(selectedMode.cap,Math.round(value)))}));
  // Turning investing on/off: off resets to a pure rotating circle (0% invested);
  // on seeds a sensible default slice so the controls have something to show.
  const toggleAdvanced=(on:boolean)=>{setAdvanced(on);if(!on)setForm(f=>({...f,mode:'ROTATING' as Mode,reinvestPercent:0,targetRiskScore:3}));else setForm(f=>({...f,reinvestPercent:f.reinvestPercent>0?f.reinvestPercent:15}))};
  const submit=async()=>{setBusy(true);setError('');try{
    const bankRail=custody&&form.mode!=='INVESTMENT';
    // Gold hedge overrides the investment config with a simple HYBRID gold slice.
    // Guarded: not in INVESTMENT mode (the section is hidden there but the
    // toggle state survives), and only when the period clears gold's 3-day
    // liquidity + the 7-day payout buffer.
    const useGold=goldHedge&&!!goldScheme&&form.mode!=='INVESTMENT'&&form.periodDays>=10;
    const modeOut=useGold?(form.mode==='INVESTMENT'?'INVESTMENT':'HYBRID'):form.mode;
    const reinvestOut=useGold?goldPct/100:form.reinvestPercent/100;
    const schemeIdOut=useGold?goldScheme!.id:(form.reinvestPercent?scheme?.id:null);
    const riskOut=useGold?Math.max(6,form.targetRiskScore):form.targetRiskScore;
    const committee=await api<Committee>('/committees',{method:'POST',body:JSON.stringify({name:form.name,mode:modeOut,memberCap:form.memberCap,contributionPaisa:String(Math.round(form.contribution*100)),cadencePreset:form.cadencePreset,periodDays:form.periodDays,minMembersToStart:form.minMembersToStart,reinvestRatio:reinvestOut,riskTolerance:riskOut,schemeId:schemeIdOut,distributionMode:form.distributionMode,orderMode:'CREDIT_WEIGHTED',joinPolicy:'INVITE_ONLY',custodyMode:custody?'BANK_CUSTODY':'RECORDED',payoutGuaranteed:bankRail&&guaranteed,slotFeeBps:bankRail?Math.round(slotFee*100):0,tier:engineTier,prizeDrawEnabled:earn&&engineTier!=='CLASSIC'?prizeDraw:false,earlyFeeBps:earlyFeeOn&&engineTier!=='CLASSIC'?Math.round(effectiveFeePct*100):0,dividendPooled:engineTier==='SIGMA'?dividendPooled:false,goalType:goalType||undefined,goalName:goalName.trim()||undefined})});
    await api(`/risk/committee/${committee.id}/policy`,{method:'PATCH',body:JSON.stringify({targetRiskScore:riskOut,payoutBufferBps:form.payoutBuffer*100,liquidityReserveBps:form.liquidityReserve*100,latePenaltyBps:form.latePenalty*100,guarantorRequired:form.guarantorRequired,dynamicDeposit:form.dynamicDeposit,profitCollateral:form.profitCollateral,capitalDaysDistribution:form.capitalDaysDistribution,delayedDistributionDays:form.delayedDistributionDays,profitRecycling:form.profitRecycling,progressivePenalties:form.progressivePenalties,payoutHoldbackEnabled:form.payoutHoldbackEnabled,holdbackReleasePayments:form.holdbackReleasePayments,featureLockOnDefault:form.featureLockOnDefault,smartNudges:form.smartNudges,peerNudges:form.peerNudges,promissoryNoteRequired:form.promissoryNoteRequired,autoDebitMandateRequired:form.autoDebitMandateRequired,depositYieldBps:form.depositYield*100,insuranceReserveBps:form.insuranceReserve*100,postReceiptPenaltyPoints:form.postReceiptPenaltyPoints,rehabilitationCooldownMonths:form.rehabilitationCooldownMonths,consentText:`I accept ${form.reinvestPercent>0?`a ${form.reinvestPercent}% group allocation into ${scheme?.name||'the selected scheme'} at a risk ceiling of ${form.targetRiskScore}/10, `:''}graduated collateral, payout holdback, progressive penalties, feature locks and the disclosed rehabilitation policy.`})});
    emitHalqaAction('CREATE_CIRCLE');
    done(committee.id);
  }catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  if(user.creditScore<700)return <div className="blocked-page"><h2>Hosting locked</h2><p>A reliability score of 700 or higher is required.</p><button className="secondary" onClick={cancel}>Go back</button></div>;
  return <div className="page narrow enter"><button className="back-link" onClick={cancel}><ChevronLeft/>Back</button>
  <div className="page-head"><div><span className="eyebrow">Host studio · locks at start</span><h1>Start a savings circle</h1><p>Set the basics and choose how it earns. Investing a slice of the pool, risk and advanced safeguards are all optional — tucked away below.</p></div></div>
  <div className="projection-summary"><div><span>Pool / period</span><strong>{money(gross*100)}</strong></div><div><span>Members</span><strong>{form.memberCap}</strong></div><div><span>Earns via</span><strong>{engineName}</strong></div><div><span>Goal</span><strong>{goalType?GOAL_LABELS[goalType]:'General savings'}</strong></div></div>
  <section className="form-card"><Field label="Committee name"><input className="field" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g. Islamabad Builders Circle"/></Field>
  <div className="form-grid"><Field label="Saving for a goal? (optional)" hint="Give the circle a purpose — Hajj, fees, a wedding. The profit engine works the same."><select className="field" value={goalType} onChange={e=>setGoalType(e.target.value)}><option value="">No specific goal</option><option value="HAJJ">Hajj / Umrah</option><option value="EDUCATION">Education / fees</option><option value="WEDDING">Wedding</option><option value="HOME">Home / property</option><option value="BUSINESS">Business</option><option value="CUSTOM">Something else</option></select></Field>{goalType&&<Field label="Goal name (optional)"><input className="field" maxLength={60} value={goalName} onChange={e=>setGoalName(e.target.value)} placeholder="e.g. Ayesha's Hajj 2027"/></Field>}</div>
  <div className="form-grid"><Field label="Total members" hint="Includes host; independent from duration."><input className="field" type="number" min="3" max="30" step="1" value={form.memberCap} onChange={e=>{const count=Math.max(3,Math.min(30,+e.target.value));setForm({...form,memberCap:count,minMembersToStart:Math.min(form.minMembersToStart,count)})}}/></Field><Field label="Minimum to start"><input className="field" type="number" min="3" max={form.memberCap} step="1" value={form.minMembersToStart} onChange={e=>setForm({...form,minMembersToStart:Math.max(3,Math.min(form.memberCap,+e.target.value))})}/></Field><Field label="Contribution / period (PKR)"><input className="field" type="number" min="100" step="100" value={form.contribution} onChange={e=>setForm({...form,contribution:+e.target.value})}/></Field><Field label="Exact period (days)"><input className="field" type="number" min="7" max="365" step="1" value={form.periodDays} onChange={e=>setForm({...form,periodDays:+e.target.value})}/></Field><Field label="Duration label"><select className="field" value={form.cadencePreset} onChange={e=>setForm({...form,cadencePreset:e.target.value})}><option value="VERY_SHORT">Very short</option><option value="SHORT">Short</option><option value="MID">Mid term</option><option value="LONG">Long term</option></select></Field></div>

  {/* PROFIT ENGINE — the primary "how it earns" choice, front and centre */}
  {form.mode!=='INVESTMENT'&&<section className="default-policy-panel"><div className="panel-head"><div><span className="eyebrow">Profit engine · how this circle earns</span><h2>Earn while everyone saves</h2><p>Money sitting idle between payments earns real, halal profit automatically — no investing decision needed. Pick which levers to switch on.</p></div></div>
  <p className="combo-hint">Tick any combination — the named tier is worked out for you. The halal levers stack freely; adding the early fee makes it Priority (fee only) or Sigma (fee + earning engine).</p>
  <div className="engine-lever-group"><span className="eyebrow">Halal levers · real profit on money that's just waiting</span>
  <div className="policy-toggles compact"><label><input type="checkbox" checked={earn} onChange={e=>{const on=e.target.checked;setEarn(on);if(!on){setPatience(false);setPrizeDraw(false)}}}/><span><b>Earn on idle money (Sukoon)</b><small>Between the day a member pays and the day someone collects, the pool earns on an Islamic money-market sleeve. Deposits earn too. Shared by how much & how long you put in.</small></span></label>
  <label className={earn?'':'lever-off'}><input type="checkbox" disabled={!earn} checked={earn&&patience} onChange={e=>setPatience(e.target.checked)}/><span><b>Patience pays (Bazaar)</b><small>Profit tilts toward later turns (up to 2x) — whoever waits longest earns most. Every deposit still comes back in full.</small></span></label>
  <label className={earn?'':'lever-off'}><input type="checkbox" disabled={!earn} checked={earn&&prizeDraw} onChange={e=>setPrizeDraw(e.target.checked)}/><span><b>Monthly profit gift draw</b><small>Half of each round's profit is gifted to one on-time payer. Savings are never staked. Pending Shariah board sign-off.</small></span></label></div></div>
  <div className="engine-lever-group conventional"><span className="eyebrow">Conventional lever · not Shariah-reviewed</span>
  <div className="policy-toggles compact"><label><input type="checkbox" checked={earlyFeeOn} onChange={e=>setEarlyFeeOn(e.target.checked)}/><span><b>Early-turn fee (Priority)</b><small>An early turn pays a fee out of its own payout, dropping to 0% for the last turn — it becomes a dividend for everyone else, never kept by Halqa. Combine with the earning engine for the maximum-bonus Sigma tier.</small></span></label></div>
  {earlyFeeOn&&<><Field label="Early fee % (earliest turn)" hint={engineTier==='SIGMA'?'Hard-capped at 10% when combined with the earning engine — extra return comes from the profit levers, never a higher fee.':'Declines to 0% for the last turn. Default 10%.'}><input className="field" type="number" min="0.5" max={engineTier==='SIGMA'?10:20} step="0.5" value={effectiveFeePct} onChange={e=>setEarlyFeePct(Math.max(0.5,Math.min(engineTier==='SIGMA'?10:20,+e.target.value)))}/></Field>
  <div className="fee-explainer"><div><span>How it works</span><b>The member whose turn it is has this fee <u>deducted from their own payout</u> — e.g. a {effectiveFeePct}% fee on a {money(gross*100)} pool means the first recipient collects {money(Math.round(gross*100*(1-effectiveFeePct/100)))} and the deducted {money(Math.round(gross*100*effectiveFeePct/100))} {engineTier==='SIGMA'&&dividendPooled?'joins the completion pot, shared through the patience split':'is split equally among the other members that same round'}.</b></div><div><span>Declining charge</span><b>Turn #1 pays the full rate; it steps down each turn to 0% for the last turn, who pays nothing and only collects.</b></div><div><span>Net effect</span><b>Early turns pay more than they receive (the cost of early cash); later turns receive more (the reward for waiting). Halqa keeps none of it.</b></div></div>
  {engineTier==='SIGMA'&&<div className="policy-toggles compact"><label><input type="checkbox" checked={dividendPooled} onChange={e=>setDividendPooled(e.target.checked)}/><span><b>Pool the fee into the patience split (recommended)</b><small>Fees flow into the completion pot and out through the patience tilt instead of equal monthly splits — in the engine-verified 12-member reference case this lifts the best annual bonus from Rs 13,942 to Rs 15,639.</small></span></label></div>}</>}</div>
  <div className="engine-summary"><div><span className="eyebrow">Your combination</span><h3>{engineTier==='CLASSIC'?'Classic — no engine':engineTier==='SUKOON'?'Sukoon':engineTier==='BAZAAR'?'Bazaar':engineTier==='PRIORITY'?'Priority':'Sigma (all levers)'} <i className={isShariah?'rafa-halal':'rafa-conv'}>{isShariah?'halal structure':'not Shariah-reviewed'}</i></h3><p>{engineTier==='SIGMA'?'Every lever at once — the engine-verified maximum-bonus configuration.':engineTier==='BAZAAR'?'Earning engine with the patience tilt toward later turns.':engineTier==='SUKOON'?'Earning engine, profit shared by capital-days.':engineTier==='PRIORITY'?'The early-turn fee only, no investment engine.':'A pure rotating committee — equal in, equal out.'}</p></div></div>
  {!isShariah&&<div className="warning-box">This combination includes the conventional early-turn fee — paying for early access to shared money, funded by the members who take later turns. It has <b>not</b> been reviewed by a Shariah board and is a deliberate opt-in. Untick it for a fully halal circle.</div>}
  </section>}

  {/* Gold hedge — simple, prominent, optional */}
  {form.mode!=='INVESTMENT'&&goldScheme&&<section className="default-policy-panel gold-hedge"><div className="panel-head"><div><span className="eyebrow">Optional · halal inflation hedge</span><h2>🪙 Back this circle with gold</h2><p>Put a slice of every pool into gold — a Shariah-friendly hedge that tends to hold its value when the rupee weakens. Just choose how much; the rest rotates as normal.</p></div></div>
  <div className="policy-toggles compact"><label className={form.periodDays<10?'lever-off':''}><input type="checkbox" disabled={form.periodDays<10} checked={goldHedge&&form.periodDays>=10} onChange={e=>setGoldHedge(e.target.checked)}/><span><b>Add gold ({goldScheme.indicativeRatePct}% indicative)</b><small>{form.periodDays<10?'Needs a period of at least 10 days — gold takes 3 days to liquidate before each payout.':`Invests the chosen % of each pool into the gold-linked allocation (risk ${goldScheme.riskScore}/10). Halal.`}</small></span></label></div>
  {goldHedge&&<><div className="allocation-box"><div className="allocation-head"><div><span className="eyebrow">Gold allocation</span><h3>{goldPct}% of every pool</h3></div><label><input className="percentage-input" type="number" min="5" max="50" step="5" value={goldPct} onChange={e=>setGoldPct(Math.max(5,Math.min(50,+e.target.value)))}/><span>%</span></label></div><input className="allocation-slider" type="range" min="5" max="50" step="5" value={goldPct} onChange={e=>setGoldPct(+e.target.value)}/></div>
  <div className="info-stack"><div><span>Into gold each cycle</span><b>{money(Math.round(gross*goldPct/100*100))}</b></div><div><span>Est. gold growth / cycle</span><b className="profit">{money(Math.round(profitProjection(gross*goldPct/100,goldScheme.indicativeRatePct,cycleDays)*100))}</b></div><div><span>On Rs 100,000 in a year</span><b>{money(Math.round((100000+profitProjection(100000,goldScheme.indicativeRatePct,365))*100))}</b></div></div></>}
  </section>}

  {/* Protection stays visible — it's about safety, not investing */}
  <section className="default-policy-panel"><div className="panel-head"><div><span className="eyebrow">Anti-default mandate</span><h2>Lock the prevention stack</h2><p>These rules become immutable when the committee starts.</p></div></div><div className="policy-toggles compact"><label><input type="checkbox" checked={form.payoutHoldbackEnabled} onChange={e=>setForm({...form,payoutHoldbackEnabled:e.target.checked})}/><span><b>Rolling payout holdback</b><small>Retain a buffer until clean follow-up payments.</small></span></label><label><input type="checkbox" checked={form.progressivePenalties} onChange={e=>setForm({...form,progressivePenalties:e.target.checked})}/><span><b>Escalating fixed penalties</b><small>2% / 5% / 10% bands; no compounding interest.</small></span></label><label><input type="checkbox" checked={form.featureLockOnDefault} onChange={e=>setForm({...form,featureLockOnDefault:e.target.checked})}/><span><b>Platform feature lock</b><small>Blocks joining, hosting and marketplace access after default.</small></span></label><label><input type="checkbox" checked={form.smartNudges} onChange={e=>setForm({...form,smartNudges:e.target.checked})}/><span><b>Smart deadline nudges</b><small>Loss-aware reminders before and after deadlines.</small></span></label><label><input type="checkbox" checked={form.dynamicDeposit} onChange={e=>setForm({...form,dynamicDeposit:e.target.checked})}/><span><b>Dynamic security deposit</b><small>Scales with position and default exposure.</small></span></label><label><input type="checkbox" checked={form.guarantorRequired} onChange={e=>setForm({...form,guarantorRequired:e.target.checked})}/><span><b>Guarantor for early turns</b><small>A disclosed second line of accountability.</small></span></label></div></section>

  {/* ADVANCED, OPTIONAL: actively invest a slice of the pool */}
  <label className="advanced-toggle"><input type="checkbox" checked={advanced} onChange={e=>toggleAdvanced(e.target.checked)}/><span><b>Also invest a slice of the pool into a market scheme</b><small>Optional & advanced — off by default. Your circle already earns the profit engine above with no extra risk. Turn this on only if you want to actively invest part of each pool (this is where risk, schemes and allocation come in).</small></span></label>
  {advanced&&<div className="advanced-invest"><section className="mode-grid">{modes.map(mode=><button key={mode.id} type="button" className={`mode-option ${form.mode===mode.id?'selected':''}`} onClick={()=>setMode(mode.id)}><div>{mode.icon}<span>Up to {mode.cap}% · risk ≤{mode.riskCap}</span></div><h3>{mode.title}</h3><p>{mode.description}</p></button>)}</section>
  <div className="risk-band-box"><div><span className="eyebrow">Risk level for the invested slice</span><h3>{band(form.targetRiskScore)} risk</h3><p>Pick a level — the ceiling locks at the top of that band and the highest-return eligible scheme is selected automatically.</p></div>
  <div className="mode-grid risk-band-grid">{([{id:'LOW',label:'Low',score:3,blurb:'Capital preservation — government paper and savings certificates.'},{id:'MEDIUM',label:'Medium',score:6,blurb:'Balanced growth — income and asset-allocation funds.'},{id:'HIGH',label:'High',score:8,blurb:'Maximum growth — equity, REIT and higher-yield sleeves.'}] as const).map(rb=>{const avail=rb.score<=selectedMode.riskCap;const active=band(form.targetRiskScore)===rb.id;return <button key={rb.id} type="button" disabled={!avail} className={`mode-option ${active?'selected':''}`} onClick={()=>pickRiskBand(rb.score)}><div><span>Risk ≤ {rb.score}/10</span></div><h3>{rb.label}</h3><p>{avail?rb.blurb:`Available in ${rb.score<=6?'Hybrid or Investment':'Investment'} mode.`}</p></button>})}</div></div>
  <Field label="Eligible investment scheme" hint={hiddenByLiquidity>0?`${hiddenByLiquidity} scheme(s) hidden: liquidity exceeds this circle's ${form.periodDays}-day period minus the 7-day payout buffer.`:undefined}><select className="field" value={scheme?.id||''} onChange={e=>setForm({...form,schemeId:e.target.value})}>{eligible.map(item=><option key={item.id} value={item.id}>{item.name} · {item.indicativeRatePct}% · risk {item.riskScore}/10 · {item.liquidityDays}d liquidity</option>)}</select>{scheme&&<RateStamp rateAsOf={scheme.rateAsOf}/>}{eligible.length===0&&<small className="field-warning">No scheme fits this period at the chosen risk ceiling. Extend the period, or lower the level.</small>}</Field>
  <div className="allocation-box"><div className="allocation-head"><div><span className="eyebrow">Growth allocation</span><h3>{form.reinvestPercent}% of every pool</h3></div><label><input className="percentage-input" type="number" min={form.mode==='INVESTMENT'?50:0} max={selectedMode.cap} step="1" value={form.reinvestPercent} onChange={e=>setPercent(+e.target.value)}/><span>%</span></label></div><input className="allocation-slider" type="range" min={form.mode==='INVESTMENT'?50:0} max={selectedMode.cap} step="1" value={form.reinvestPercent} onChange={e=>setPercent(+e.target.value)}/></div>
  <div className="risk-policy-grid"><Field label="Payout buffer %"><input className="field" type="number" min="0" max="30" step="1" value={form.payoutBuffer} onChange={e=>setForm({...form,payoutBuffer:+e.target.value})}/></Field><Field label="Liquidity reserve %"><input className="field" type="number" min="5" max="40" step="1" value={form.liquidityReserve} onChange={e=>setForm({...form,liquidityReserve:+e.target.value})}/></Field><Field label="Late penalty %"><input className="field" type="number" min="0" max="10" step="1" value={form.latePenalty} onChange={e=>setForm({...form,latePenalty:+e.target.value})}/></Field><Field label="Delayed distribution"><select className="field" value={form.delayedDistributionDays} onChange={e=>setForm({...form,delayedDistributionDays:+e.target.value})}><option value="0">None</option><option value="30">30 days</option><option value="60">60 days</option><option value="90">90 days</option></select></Field></div></div>}

  {SHOW_BANK_RAIL&&partner&&<section className="default-policy-panel"><div className="panel-head"><div><span className="eyebrow">Partner rail · {partner.name}{partner.sandbox?' sandbox':''}</span><h2>Custody &amp; guaranteed payouts</h2><p>{user.kycLevel>=2?'The partner collects and disburses. A disclosed slot fee funds this circle’s own guarantee pool.':'Complete verification (Level 2) on your profile to unlock custody.'}</p></div><ShieldCheck/></div>
  {user.kycLevel>=2&&<div className="policy-toggles compact"><label><input type="checkbox" checked={custody} onChange={e=>{setCustody(e.target.checked);if(!e.target.checked)setGuaranteed(false)}}/><span><b>Custody via {partner.name}</b><small>Installments settle by statement matching.</small></span></label></div>}
  </section>}
  <div className="projection-summary"><div><span>Pool / period</span><strong>{money(gross*100)}</strong></div>{advanced&&form.reinvestPercent>0&&<><div><span>Invested slice</span><strong>{money(invested*100)}</strong></div><div><span>Est. scheme profit / cycle</span><strong>{money(Math.round(projected*100))}</strong></div></>}<p>This circle earns the <b>{engineName}</b> engine automatically on idle pool days and deposits — indicative, not guaranteed.{advanced&&form.reinvestPercent>0?' The invested slice adds market-scheme profit on top, at the disclosed risk.':''} Every member accepts the locked policy before start.</p></div>{error&&<div className="error-box">{error}</div>}<div className="form-actions"><button className="secondary" onClick={cancel}>Cancel</button><button className="primary" disabled={busy||form.name.trim().length<3||(form.reinvestPercent>0&&!scheme)} onClick={submit}>{busy?'Building…':'Create circle'}</button></div></section></div>;
}
