import { useEffect, useState } from 'react';
import { CalendarDays, Clock3, Plus, ShieldCheck, Users, X } from 'lucide-react';
import { api, money } from '../api';
import type { Committee, User } from '../types';
import { CircleCard, cached, keep } from './HomePage';
import { Empty, modeName } from '../components/ui';
import { HostCard, type Reputation } from '../components/HostCard';
import { SHOW_INVESTOR_BRIEFING_FEATURES } from '../config';

type Preview={id:string;name:string;mode:'ROTATING'|'HYBRID'|'INVESTMENT';status:string;memberCount:number;memberCap:number;contributionPaisa:string;periodDays:number;reinvestRatio:number;riskScore:number;riskBand:string;distributionMode:string;scheme:{name:string;riskScore:number;indicativeRatePct:number}|null;host:Reputation};
type Slot={position:number;expectedPayoutAt:string;indicative:boolean};
type CreditHealth={averageCreditScore:number;grade:'EXCELLENT'|'STRONG'|'FAIR'|'WATCH';defaults:number;latePayments:number;earlyPayments:number;settledPayments:number;paymentQualityPct:number};
type DiscoveryCircle={id:string;name:string;mode:'ROTATING'|'HYBRID'|'INVESTMENT';status:string;availability:'OPEN'|'WAIT_NEXT_CYCLE';memberCount:number;memberCap:number;contributionPaisa:string;periodDays:number;cycleNumber:number;orderMode:string;secure:boolean;riskScore:number;riskBand:string;host:{id:string;fullName:string;creditScore:number};scheme:{name:string;riskScore:number;indicativeRatePct:number}|null;availablePositions:Slot[];projectedCycleStart:string;creditHealth:CreditHealth;engines:string[];waitlisted:boolean};

export default function CirclesPage({user,openCommittee,create}:{user:User;openCommittee:(id:string)=>void;create:()=>void}){
  const [rows,setRows]=useState<Committee[]>(()=>cached('circles.rows',[]));
  const [discover,setDiscover]=useState<DiscoveryCircle[]>(()=>cached('circles.discover',[]));
  const [code,setCode]=useState('');const [error,setError]=useState('');const [preview,setPreview]=useState<Preview|null>(null);const [busy,setBusy]=useState(false);
  const load=async()=>{
    if(SHOW_INVESTOR_BRIEFING_FEATURES){const data=await api<DiscoveryCircle[]>('/committees/discover');setDiscover(data);keep('circles.discover',data)}
    else{const data=await api<Committee[]>('/committees');setRows(data);keep('circles.rows',data)}
  };
  useEffect(()=>{void load()},[]);
  const inspect=async()=>{try{setError('');setBusy(true);setPreview(await api<Preview>(`/committees/preview/${encodeURIComponent(code.trim())}`))}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  const join=async()=>{try{setError('');setBusy(true);const joined=preview?.id;await api('/committees/join',{method:'POST',body:JSON.stringify({inviteCode:code.trim()})});setCode('');setPreview(null);await load();if(joined)openCommittee(joined)}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  const joinPublic=async(id:string)=>{try{setError('');setBusy(true);await api(`/committees/${id}/join-public`,{method:'POST',body:'{}'});await load();openCommittee(id)}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  const waitlist=async(id:string,preferredPosition:number|null)=>{try{setError('');setBusy(true);await api(`/committees/${id}/waitlist`,{method:'POST',body:JSON.stringify({preferredPosition})});await load()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  const openRows=discover.filter(item=>item.availability==='OPEN');const nextRows=discover.filter(item=>item.availability==='WAIT_NEXT_CYCLE');
  return <div className="page enter"><div className="page-head"><div><span className="eyebrow">Savings network</span><h1>{SHOW_INVESTOR_BRIEFING_FEATURES?'Discover circles':'Committees'}</h1><p>{SHOW_INVESTOR_BRIEFING_FEATURES?'Explore circles you have not joined, compare their repayment record, and see every projected turn slot.':'Member capacity and duration are configured independently.'}</p></div><button className="primary" onClick={create}><Plus/>Create</button></div><div className="join-bar"><input className="field" value={code} onChange={e=>{setCode(e.target.value);setPreview(null)}} placeholder="Have a private invite code?"/><button className="secondary" disabled={busy||code.trim().length<3} onClick={inspect}>Check before joining</button></div>{error&&<div className="error-box">{error}</div>}
  {preview&&<section className="panel" style={{display:'grid',gap:12}}><div className="panel-head"><div><span className="eyebrow">{modeName[preview.mode]} · risk {preview.riskScore}/10 {preview.riskBand}</span><h2>{preview.name}</h2><p>{money(preview.contributionPaisa)} every {preview.periodDays} days · {preview.memberCount}/{preview.memberCap} members · {Math.round(preview.reinvestRatio*100)}% growth allocation{preview.scheme?` into ${preview.scheme.name}`:''}</p></div><button className="icon-button" aria-label="Close preview" onClick={()=>setPreview(null)}><X/></button></div><HostCard reputation={preview.host}/><button className="primary" disabled={busy||preview.status!=='FORMING'} onClick={join}>{preview.status==='FORMING'?`Join ${preview.name}`:'This circle has already started'}</button></section>}
  {SHOW_INVESTOR_BRIEFING_FEATURES?<><DiscoveryGroup title="Open now" subtitle="Choose a forming circle with room for new members." rows={openRows} busy={busy} joinPublic={joinPublic} waitlist={waitlist}/><DiscoveryGroup title="Wait for next cycle" subtitle="Follow established circles and reserve interest in a future turn." rows={nextRows} busy={busy} joinPublic={joinPublic} waitlist={waitlist}/></>:<section className="circle-grid">{rows.map((committee,index)=><CircleCard key={committee.id} committee={committee} userId={user.id} index={index} open={openCommittee}/>)}{!rows.length&&<Empty text="No committees are available."/>}</section>}</div>
}

function DiscoveryGroup({title,subtitle,rows,busy,joinPublic,waitlist}:{title:string;subtitle:string;rows:DiscoveryCircle[];busy:boolean;joinPublic:(id:string)=>void;waitlist:(id:string,position:number|null)=>void}){
  return <section className="discovery-group"><div className="section-head"><div><span className="eyebrow">Public network</span><h2>{title}</h2><p>{subtitle}</p></div><span>{rows.length} circle{rows.length===1?'':'s'}</span></div><div className="discovery-grid">{rows.map((circle,index)=><DiscoveryCard key={circle.id} circle={circle} index={index} busy={busy} joinPublic={joinPublic} waitlist={waitlist}/>)}{!rows.length&&<Empty text={`No circles are marked “${title}” right now.`}/>}</div></section>
}

function DiscoveryCard({circle,index,busy,joinPublic,waitlist}:{circle:DiscoveryCircle;index:number;busy:boolean;joinPublic:(id:string)=>void;waitlist:(id:string,position:number|null)=>void}){
  const [preferred,setPreferred]=useState<number|null>(circle.availablePositions[0]?.position??null);
  const health=circle.creditHealth;
  return <article className="discovery-card stagger" style={{animationDelay:`${index*55}ms`}}><header><div><div className="discovery-badges"><span className={`availability availability-${circle.availability.toLowerCase()}`}>{circle.availability==='OPEN'?'Open':'Wait next cycle'}</span>{circle.secure&&<span className="secure-chip"><ShieldCheck/>Secure</span>}<span className={`health-grade health-${health.grade.toLowerCase()}`}>{health.grade}</span></div><h3>{circle.name}</h3><p>Hosted by {circle.host.fullName} · host score {circle.host.creditScore}</p></div><div className="circle-icon"><Users/></div></header><div className="discovery-summary"><div><span>Contribution</span><b>{money(circle.contributionPaisa)}</b><small>every {circle.periodDays} days</small></div><div><span>Circle credit</span><b>{health.averageCreditScore}</b><small>{health.paymentQualityPct}% clean record</small></div><div><span>Members</span><b>{circle.memberCount}/{circle.memberCap}</b><small>{circle.memberCap-circle.memberCount} current openings</small></div></div><div className="credit-evidence"><span><b>{health.defaults}</b> defaults</span><span><b>{health.latePayments}</b> late</span><span><b>{health.earlyPayments}</b> early payments</span></div><div className="engine-tags">{circle.engines.map(engine=><span key={engine}>{engine}</span>)}</div><div className="slot-board"><div><span className="eyebrow">Available payout timeline</span><small>{circle.orderMode==='CREDIT_WEIGHTED'?'Indicative: final slots follow verified credit ranking.':'Final order locks when the cycle starts.'}</small></div><div className="slot-list">{circle.availablePositions.map(slot=><button type="button" key={slot.position} className={preferred===slot.position?'selected':''} onClick={()=>setPreferred(slot.position)}><b>This turn available · #{slot.position}</b><span><CalendarDays/>Expected {new Date(slot.expectedPayoutAt).toLocaleDateString('en-PK',{day:'numeric',month:'short',year:'numeric'})}</span></button>)}</div></div>{circle.availability==='OPEN'?<button className="primary full" disabled={busy} onClick={()=>joinPublic(circle.id)}>Join this open circle</button>:<button className="primary full" disabled={busy||circle.waitlisted} onClick={()=>waitlist(circle.id,preferred)}><Clock3/>{circle.waitlisted?'You are on the next-cycle list':'Join next-cycle waitlist'}</button>}</article>
}
