import { lazy, Suspense, useCallback, useEffect, useRef, useState } from 'react';
import { io, type Socket } from 'socket.io-client';
import { ChevronLeft, Crown, Landmark, Send, ShieldCheck, UserRound, Users, X } from 'lucide-react';
import { API_ORIGIN, api, key, money, tokens } from '../api';
import { emitHalqaAction } from '../lib/events';
import type { Committee, Round, User } from '../types';
import { Field, Mini, formatDuration, modeName, scoreColor, tierName } from '../components/ui';
import { SHOW_BANK_RAIL, SIMPLE_MODE } from '../config';
import RiskConsole from '../components/RiskConsole';
import ProtectionCenter from '../components/ProtectionCenter';
import { HostCardById } from '../components/HostCard';
import ErrorBoundary from '../components/ErrorBoundary';

const ProjectionChart=lazy(()=>import('../components/ProjectionChart'));
const PersonalGrowthChart=lazy(()=>import('../components/PersonalGrowthChart'));
type Tab='turns'|'payments'|'growth'|'protection'|'chat';

export default function CommitteePage({id,user,onBack}:{id:string;user:User;onBack:()=>void}){
  const [committee,setCommittee]=useState<Committee|null>(null);const [tab,setTab]=useState<Tab>('turns');const [error,setError]=useState('');
  const load=useCallback(()=>api<Committee>(`/committees/${id}`).then(setCommittee).catch(reason=>setError(reason.message)),[id]);useEffect(()=>{void load()},[load]);
  if(!committee)return <div className="splash">{error||'Loading committee…'}</div>;
  const host=committee.hostId===user.id;const active=committee.rounds.find(round=>['COLLECTING','INVESTED'].includes(round.status));const membership=committee.members.find(member=>member.userId===user.id);const myRound=committee.rounds.find(round=>round.recipientId===user.id&&round.status!=='CLOSED');const myPayment=active?.payments.find(payment=>payment.payerId===user.id);
  const action=async(path:string,body:unknown={})=>{try{setError('');await api(`/committees/${id}/${path}`,{method:'POST',body:JSON.stringify(body)});await load()}catch(reason){setError((reason as Error).message)}};
  return <div className="committee-page"><header className="committee-header"><button className="icon-button" onClick={onBack}><ChevronLeft/></button><div><b>{committee.name}</b><span>{modeName[committee.mode]} · {committee.members.length}/{committee.memberCap} members</span></div><span className="host-chip">{host?<><Crown/>Host controls</>:<>Member view</>}</span></header><main className="committee-content enter"><section className="committee-hero"><div><span className="eyebrow">{committee.mode==='INVESTMENT'?'Maturity pool':'Current payout'}</span><strong>{money(active?.payoutPaisa||0)}</strong><p>{committee.mode==='INVESTMENT'?'No rotating payout; all value stays in the maturity reserve.':`${Math.round(committee.reinvestRatio*100)}% retained in the growth reserve.`}</p></div><div className="your-turn"><UserRound/><span>Your position</span><strong>{membership?`#${membership.turnPosition}`:'—'}</strong><small>{myRound?`${formatDuration(myRound.payoutDate)} until payout`:'Completed or not scheduled'}</small></div><div className="hero-mini"><Mini label="Contribution" value={money(committee.contributionPaisa)}/><Mini label="Round" value={committee.currentRound?`${committee.currentRound}/${committee.rounds.length}`:'Forming'}/><Mini label="Growth allocation" value={`${Math.round(committee.reinvestRatio*100)}%`}/></div></section>
  {SHOW_BANK_RAIL&&committee.custodyMode==='BANK_CUSTODY'&&<div className="market-rules"><Landmark/><div><b>Custody · {committee.partner?.name||'Partner'}{committee.partner?.sandbox?' (sandbox)':''}{committee.payoutGuaranteed?' · payouts guaranteed up to the pool balance':''}</b><p>Installments settle from the partner statement. Slot fee {((committee.slotFeeBps||0)/100).toFixed(2)}% funds this circle's guarantee pool{committee.guaranteeFundPaisa!==undefined?` · pool balance ${money(committee.guaranteeFundPaisa)}`:''}. Never redistributed to members or the platform.</p></div></div>}
  {committee.payoutGuaranteed&&committee.custodyMode!=='BANK_CUSTODY'&&<div className="market-rules"><ShieldCheck/><div><b>Safety Fund · guaranteed payouts{committee.guaranteeFundPaisa!==undefined?` · fund ${money(committee.guaranteeFundPaisa)}`:''}</b><p>Each round a {((committee.slotFeeBps||0)/100).toFixed(1)}% slot fee pools into this circle's own Safety Fund. If a member falls short on someone's turn, the fund tops up their payout so it lands on time and in full — guaranteed up to the fund's balance. Never Halqa's money; any remainder returns to the circle at completion. A mutual safety fund (takaful-style){committee.custodyMode==='RECORDED'?'; recorded in Stage 1, bank-held at custody':''}.</p></div></div>}
  {committee.tier&&(committee.tier==='SUKOON'||committee.tier==='BAZAAR')&&<div className="market-rules"><ShieldCheck/><div><b>{tierName(committee.tier)} profit engine · halal floor</b><p>Idle pool days earn on {committee.floatScheme?`${committee.floatScheme.name} (${committee.floatScheme.indicativeRatePct}% indicative)`:'the Islamic float sleeve'}; recorded deposits accrue at {committee.depositScheme?`${committee.depositScheme.indicativeRatePct}%`:'the Mudarabah rate'}. Profit is distributed at cycle completion by capital-days{committee.tier==='BAZAAR'?' with a disclosed patience tilt (later turns weigh up to 2x). Deposit yield is pooled into that tilt, so the members who waited longest earn the most — deposits themselves are returned in full':''}.{committee.prizeDrawEnabled?' Half of each round’s net profit is gifted to one on-time payer.':''} Simulated and indicative — never guaranteed.</p></div></div>}
  {committee.tier==='PRIORITY'&&<div className="market-rules"><Landmark/><div><b>Early Access (conventional) · not Shariah-reviewed</b><p>Each turn's fee is deducted from that recipient's own payout, starting at {((committee.earlyFeeBps||0)/100).toFixed(2)}% for the earliest turn and declining to 0% for the last. It's split immediately among every other active member as a dividend — never kept by Halqa. Early turns net negative (they pay for early cash); later turns net positive (their reward for waiting).</p></div></div>}
  {committee.tier==='SIGMA'&&<div className="market-rules"><Landmark/><div><b>Maximum (all levers) · not Shariah-reviewed</b><p>Every return lever runs in this circle: the early fee (from {((committee.earlyFeeBps||0)/100).toFixed(2)}% for turn #1, declining to 0%, hard-capped at 10%) is {committee.dividendPooled?'pooled into the completion pot and distributed through the patience tilt':'split among the other members every round'}; idle pool days earn on {committee.floatScheme?`${committee.floatScheme.name} (${committee.floatScheme.indicativeRatePct}% indicative)`:'the Islamic float sleeve'}; deposit yield is pooled into the patience split (later turns weigh up to 2x, deposits return in full); consistently early payers carry a 1.25x early-bird weight.{committee.prizeDrawEnabled?' Half of each round’s net float profit is gifted to one on-time payer.':''} Simulated and indicative — never guaranteed, and never a fee above 10%.</p></div></div>}<nav className="segmented">{((SIMPLE_MODE?['turns','payments','protection','chat']:['turns','payments','growth','protection','chat']) as Tab[]).map(item=><button className={tab===item?'active':''} key={item} onClick={()=>setTab(item)}>{item==='turns'?'Turns & people':item==='protection'?'Safety':item.charAt(0).toUpperCase()+item.slice(1)}</button>)}</nav>{error&&<div className="error-box">{error}</div>}
  {tab==='turns'&&<Turns committee={committee} user={user} host={host} action={action}/>} {tab==='payments'&&<Payments committee={committee} user={user} active={active} myPayment={myPayment} host={host} reload={load} action={action}/>} {tab==='growth'&&<Growth committee={committee} active={active} host={host} action={action} myPosition={membership?.turnPosition}/>} {tab==='protection'&&<ProtectionCenter committeeId={committee.id} user={user} host={host}/>} {tab==='chat'&&<ErrorBoundary scoped label="Committee chat"><Chat committeeId={committee.id} user={user}/></ErrorBoundary>}</main></div>
}

function Turns({committee,user,host,action}:{committee:Committee;user:User;host:boolean;action:(path:string,body?:unknown)=>Promise<void>}){
  return <div className="detail-grid"><section className="panel"><div className="panel-head"><div><span className="eyebrow">Locked order</span><h2>Everybody's turn</h2></div>{host&&committee.status==='FORMING'&&<div style={{display:'flex',gap:8,flexWrap:'wrap'}}><button className="primary" disabled={committee.members.length<committee.minMembersToStart} onClick={()=>action('start')}>Start with {committee.members.length}</button>{committee.members.length>=committee.minMembersToStart&&committee.members.length<committee.memberCap&&<button className="secondary" onClick={()=>action('start',{fundGap:true})} title="Halqa contributes into the unfilled positions so the circle starts full. Halqa's seats take the FIRST turns and Halqa pays its share into every round, so members holding later turns are still paid on schedule. Circles Halqa helps fill carry a higher management fee, per the Fees & Payments Policy.">Start full — Halqa fills {committee.memberCap-committee.members.length} slot{committee.memberCap-committee.members.length===1?'':'s'} · higher mgmt fee</button>}</div>}</div>{committee.status==='FORMING'&&<div className="assembly"><Users/><div><b>{committee.members.length} of {committee.minMembersToStart} required</b><p>The host is included. Minimum is three total people.</p></div></div>}
{committee.status==='FORMING'&&committee.members.length<committee.memberCap&&<div className="market-rules"><div><b>Halqa's own contribution</b><p>If seats stay empty, the host can start the circle full — Halqa contributes into the unfilled positions and takes the <u>first</u> turns. Halqa pays its share into every round, so members holding later turns are paid on schedule. Circles Halqa helps fill carry a higher management fee, disclosed in the Fees & Payments Policy.</p></div></div>}<div className="turn-timeline">{committee.rounds.length?committee.rounds.map(round=><article className={`${round.recipientId===user.id?'mine':''} ${round.status.toLowerCase()}`} key={round.id}><div className="turn-index">{round.roundNumber}</div><div><b>{round.recipient.fullName}{round.recipientId===user.id?' · You':''}</b><p>{new Date(round.payoutDate).toLocaleDateString()} · {money(round.payoutPaisa)}</p></div><span>{round.status}</span></article>):committee.members.map(member=><article className={member.userId===user.id?'mine':''} key={member.id}><div className="turn-index">{member.turnPosition}</div><div><b>{member.user.fullName}{member.userId===user.id?' · You':''}</b><p>Provisional order · score {member.user.creditScore}</p></div><span>FORMING</span></article>)}</div></section><section className="panel"><div className="panel-head"><div><span className="eyebrow">Circle</span><h2>Members</h2></div></div><div className="member-list">{committee.members.map(member=><article key={member.id}><div className="avatar">{member.user.fullName[0]}</div><div><b>{member.user.fullName}{member.userId===user.id?' · You':''}</b><p>Position {member.turnPosition}{member.userId===committee.hostId?' · Host':''}</p></div><strong style={{color:scoreColor(member.user.creditScore)}}>{member.user.creditScore}</strong></article>)}</div><HostCardById userId={committee.hostId}/><div className="invite-code"><span>Invite code</span><b>{committee.inviteCode}</b></div><a className="secondary" style={{display:'block',textAlign:'center',marginTop:8,padding:'10px 12px',borderRadius:12,textDecoration:'none',fontWeight:700,fontSize:12}} href={`https://wa.me/?text=${encodeURIComponent(`Assalam-o-alaikum! Join our committee "${committee.name}" on Halqa — ${money(committee.contributionPaisa)} per round. Open the app and enter invite code: ${committee.inviteCode}`)}`} target="_blank" rel="noreferrer">Share invite on WhatsApp</a></section></div>
}

function Payments({committee,user,active,myPayment,host,reload,action}:{committee:Committee;user:User;active?:Round;myPayment?:Round['payments'][number];host:boolean;reload:()=>Promise<void>;action:(path:string,body?:unknown)=>Promise<void>}){
  const [pay,setPay]=useState(false);const paid=active?.payments.filter(payment=>payment.status==='PAID').length||0;
  const mine=committee.members.find(member=>member.userId===user.id);const autoOn=!!mine?.autoDebitEnabled;const autoRail=mine?.autoDebitRail||'RAAST';
  // Guaranteed circles can release with MISSED installments (pool covers them);
  // PENDING/LATE still block, mirroring the API rule.
  const blocking=active?.payments.filter(payment=>payment.status!=='PAID'&&!(committee.payoutGuaranteed&&payment.status==='MISSED')).length||0;
  const myRound=committee.rounds?.find(r=>r.recipientId===user.id);
  const [showReceipt,setShowReceipt]=useState(false);
  return <section className="panel detail-panel"><div className="panel-head"><div><span className="eyebrow">Round {active?.roundNumber||'—'}</span><h2>Installment matrix</h2><p>{active?`${formatDuration(active.dueDate)} until due · ${paid}/${active.payments.length} recorded`:'The committee has not started.'}</p></div>{myPayment&&(myPayment.status!=='PAID'
    ?<button className="primary" onClick={()=>setPay(true)}>Pay installment</button>
    :<button className="secondary" onClick={()=>setShowReceipt(!showReceipt)}>Paid ✓ · receipt</button>)}</div>
  {myRound&&<div className="your-payout"><div><span>Your turn · round {myRound.roundNumber}</span><b>{money(myRound.payoutPaisa)}</b><small>{myRound.status==='CLOSED'?'Collected':`Lands ${new Date(myRound.payoutDate).toLocaleDateString()}`} · already net of the turn-order adjustment</small></div><i>#{committee.members.find(m=>m.userId===user.id)?.turnPosition||'—'}</i></div>}
  {!active&&<div className="warning-box">{committee.status==='FORMING'?(host?'Installments appear here the moment you start the circle — use Start on the Turns tab.':'Installments appear here once the host starts the circle. Nothing is owed while it forms.'):'No round is collecting right now.'}</div>}
  {showReceipt&&myPayment&&<div className="receipt-rows" style={{marginBottom:12}}><div><span>Status</span><b className="paid">PAID</b></div><div><span>Amount</span><b>{money(myPayment.amountPaisa)}</b></div><div><span>Rail</span><b>{(myPayment as unknown as {paidVia?:string}).paidVia||'—'}</b></div><div><span>Reference</span><b className="mono">{(myPayment as unknown as {txnRef?:string}).txnRef||'—'}</b></div></div>}<div className="payment-grid">{active?.payments.map(payment=><article key={payment.id}><div className="avatar">{payment.payer?.fullName[0]}</div><div><b>{payment.payer?.fullName}</b><p>{money(payment.amountPaisa)}</p></div><span className={`status status-${payment.status.toLowerCase()}`}>{payment.status}</span></article>)}</div>
  {mine&&autoOn&&<p className="field-note" style={{fontSize:11.5,opacity:0.8,margin:'6px 0 0'}}>Auto-pay is on for this circle via {autoRail} — manage it from your Profile.</p>}
  {SHOW_BANK_RAIL&&host&&committee.custodyMode==='BANK_CUSTODY'&&active&&<StatementImport committeeId={committee.id} reload={reload}/>}{host&&active&&<div className="host-actions"><button className="primary" disabled={active.status==='INVESTED'||blocking>0} onClick={async()=>{await action('payout',{idempotencyKey:key()});emitHalqaAction('PAYOUT')}}>{committee.mode==='INVESTMENT'?'Close contribution cycle':'Release payout & advance'}</button><button className="secondary" title="Export a bank-facing statement of this circle's future receivables and member reliability" onClick={async()=>{try{const pack=await api<Record<string,unknown>>(`/committees/${committee.id}/receivables-pack`);const blob=new Blob([JSON.stringify(pack,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`halqa-receivables-${committee.name.replace(/\W+/g,'-')}.json`;a.click();URL.revokeObjectURL(url)}catch{/* non-fatal */}}}>Bank pack</button><small>{blocking>0?'All current installments must be recorded first.':paid<(active.payments.length||0)?'Missed installments will be covered from the guarantee pool at release.':'Ready when no investment remains active.'}</small></div>}{pay&&<PaymentModal round={active!} committee={committee} user={user} amountPaisa={myPayment?.amountPaisa||committee.contributionPaisa} close={()=>setPay(false)} done={async()=>{setPay(false);await reload()}}/>}</section>
}

// Partner rail (#96): the host pastes statement lines as `ref | amount PKR | narration`.
// A line settles a member's installment only when the amount equals the
// contribution and the narration names exactly one unpaid member.
function StatementImport({committeeId,reload}:{committeeId:string;reload:()=>Promise<void>}){
  const [raw,setRaw]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const [summary,setSummary]=useState<{matchedLines:number;totalLines:number;results:{lineRef:string;status:string;payerUsername?:string;note?:string}[]}|null>(null);
  const parsed=raw.split('\n').map(line=>line.trim()).filter(Boolean).map(line=>{const [lineRef,amount,...rest]=line.split('|').map(part=>part.trim());return {lineRef,amountPaisa:String(Math.round((+amount||0)*100)),narration:rest.join(' '),postedAt:new Date().toISOString()}});
  const valid=parsed.length>0&&parsed.every(line=>line.lineRef?.length>=4&&+line.amountPaisa>0&&line.narration.length>=3);
  const submit=async()=>{setBusy(true);setError('');try{setSummary(await api(`/partner/committees/${committeeId}/statements`,{method:'POST',body:JSON.stringify({lines:parsed})}));setRaw('');await reload()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  return <div className="deposit-board"><header><b>Partner statement import</b><span>One line per transfer: reference | amount PKR | narration naming the member</span></header>
  <textarea className="field" rows={3} value={raw} onChange={e=>setRaw(e.target.value)} placeholder={'SON-8841 | 250 | monthly installment from ayesha\nSON-8842 | 250 | bilal committee transfer'}/>
  {summary&&<div className="info-stack"><div><span>Last import</span><b>{summary.matchedLines}/{summary.totalLines} matched</b></div>{summary.results.filter(item=>item.status!=='MATCHED').slice(0,3).map(item=><div key={item.lineRef}><span>{item.lineRef}</span><b>{item.status}{item.note?` · ${item.note}`:''}</b></div>)}</div>}
  {error&&<div className="error-box">{error}</div>}
  <button className="secondary" disabled={busy||!valid} onClick={submit}>{busy?'Matching…':`Match ${parsed.length||''} line(s)`}</button></div>;
}

// The checkout sheet — a proper gateway-style flow (order summary → rail →
// processing → receipt), modelled on how Safepay/PayFast present a charge.
// Sandbox settles instantly behind the same UI a live rail will use.
const RAILS:[string,string,string,string][]=[["RAAST","Raast","RA","#0e7d72"],["JAZZCASH","JazzCash","JC","#c8102e"],["EASYPAISA","Easypaisa","EP","#3f9c35"],["BANK_TRANSFER","Bank transfer","BK","#5b6472"],["CASH","Cash","₨","#b08d2f"]];
type LinkedMethod={id:string;rail:string;accountNo:string;label:string;preferred:boolean};
function PaymentModal({round,committee,user,amountPaisa,close,done}:{round:Round;committee:Committee;user:User;amountPaisa:string;close:()=>void;done:()=>Promise<void>}){
  const [via,setVia]=useState('RAAST');const [wallet,setWallet]=useState(user.phone||'');const [reference,setReference]=useState('');const [error,setError]=useState('');
  const [step,setStep]=useState<'select'|'processing'|'receipt'|'failed'>('select');const [receipt,setReceipt]=useState<{ref:string;at:Date;rail:string;live:boolean}|null>(null);const [copied,setCopied]=useState(false);
  const [methods,setMethods]=useState<LinkedMethod[]>([]);const [methodId,setMethodId]=useState('');const [saveMethod,setSaveMethod]=useState(false);
  useEffect(()=>{void api<{methods:LinkedMethod[]}>('/profile/payment-methods').then(d=>{setMethods(d.methods);const pref=d.methods.find(m=>m.preferred);if(pref){setMethodId(pref.id);setVia(pref.rail)}}).catch(()=>setMethods([]))},[]);
  const digital=via==='RAAST'||via==='JAZZCASH'||via==='EASYPAISA';const wallets=via==='JAZZCASH'||via==='EASYPAISA';
  const railMeta=RAILS.find(r=>r[0]===via)!;
  const chooseMethod=(m:LinkedMethod)=>{setMethodId(m.id);setVia(m.rail)};
  const chooseRail=(id:string)=>{setMethodId('');setVia(id)};
  const afterSuccess=()=>{if(saveMethod&&wallets&&!methodId)void api('/profile/payment-methods',{method:'POST',body:JSON.stringify({rail:via,accountNo:wallet.replace(/\D/g,''),preferred:true})}).catch(()=>{})};
  const payNow=async()=>{setStep('processing');setError('');const started=Date.now();try{
    const r=await api<{settled:boolean;payment?:{txnRef?:string};instruction?:{instruction:string;reference?:string}}>('/payments/initiate',{method:'POST',body:JSON.stringify({roundId:round.id,rail:via,idempotencyKey:key()})});
    emitHalqaAction('PAY_INSTALLMENT');
    await new Promise(resolve=>setTimeout(resolve,Math.max(0,1400-(Date.now()-started)))); // let the processing state read as real work, never a flicker
    afterSuccess();
    if(r.settled){setReceipt({ref:r.payment?.txnRef||r.instruction?.reference||'—',at:new Date(),rail:railMeta[1],live:false});setStep('receipt')}
    else{setReceipt({ref:r.instruction?.reference||'—',at:new Date(),rail:railMeta[1],live:true});setStep('receipt')}
  }catch(reason){setError((reason as Error).message);setStep('failed')}};
  const record=async()=>{setStep('processing');setError('');const started=Date.now();try{
    await api('/payments',{method:'POST',body:JSON.stringify({roundId:round.id,paidVia:via,txnRef:reference,idempotencyKey:key()})});
    emitHalqaAction('PAY_INSTALLMENT');
    await new Promise(resolve=>setTimeout(resolve,Math.max(0,1100-(Date.now()-started))));
    setReceipt({ref:reference,at:new Date(),rail:railMeta[1],live:false});setStep('receipt');
  }catch(reason){setError((reason as Error).message);setStep('failed')}};
  const copyRef=async()=>{try{await navigator.clipboard.writeText(receipt?.ref||'');setCopied(true);setTimeout(()=>setCopied(false),1500)}catch{/* clipboard unavailable */}};
  return <div className="modal-backdrop"><section className="modal checkout">
    <div className="modal-head"><div className="checkout-title"><h2>Checkout</h2><span className="secure-chip">🔒 Encrypted</span></div>{step!=='processing'&&<button onClick={step==='receipt'?()=>void done():close}><X/></button>}</div>
    {step==='select'&&<>
      <div className="checkout-summary"><div className="checkout-lines"><div><span>{committee.name}</span><b>Round {round.roundNumber} installment</b></div><div><span>Service fee</span><b className="fee-zero">Rs 0 — members never pay Halqa</b></div></div><div className="checkout-amount"><span>Total</span><strong>{money(amountPaisa)}</strong></div></div>
      {methods.length>0&&<><span className="eyebrow" style={{display:'block',margin:'12px 0 6px'}}>Your linked methods</span>
      <div className="method-list">{methods.map(m=>{const meta=RAILS.find(r=>r[0]===m.rail);return <button key={m.id} type="button" className={`method-row ${methodId===m.id?'on':''}`} onClick={()=>chooseMethod(m)}><i className="method-radio"/><i className="method-logo" style={{background:meta?.[3]||'#5b6472'}}>{meta?.[2]||'PM'}</i><span className="method-text"><b>{m.label}</b><small className="mono">{m.accountNo}</small></span>{m.preferred&&<span className="pref-chip">Preferred</span>}</button>})}</div></>}
      <span className="eyebrow" style={{display:'block',margin:'12px 0 6px'}}>{methods.length?'Or pay another way':'Pay with'}</span>
      <div className="rail-cards">{RAILS.map(([id,label,mono,color])=><button key={id} type="button" className={`rail-card ${via===id&&!methodId?'on':''}`} onClick={()=>chooseRail(id)}><i style={{background:color}}>{mono}</i><b>{label}</b>{via===id&&!methodId&&<span className="tick">✓</span>}</button>)}</div>
      {wallets&&!methodId&&<><Field label={`${railMeta[1]} wallet number`}><input className="field" inputMode="tel" value={wallet} onChange={e=>setWallet(e.target.value)} placeholder="03XXXXXXXXX"/></Field>
      <label className="tos-check" style={{margin:'2px 0 8px'}}><input type="checkbox" checked={saveMethod} onChange={e=>setSaveMethod(e.target.checked)}/><span>Save this as my preferred way to pay</span></label></>}
      {via==='BANK_TRANSFER'&&<div className="warning-box">Send the transfer to the recipient directly from your banking app, then enter the transaction reference below.</div>}
      {via==='CASH'&&<div className="warning-box">Hand the cash to the recipient or host, then enter the receipt or slip number below.</div>}
      {!digital&&<Field label="Transaction reference"><input className="field" value={reference} onChange={e=>setReference(e.target.value)} placeholder="e.g. slip no. 739204"/></Field>}
      {error&&<div className="error-box">{error}</div>}
      {digital
        ?<button className="primary full checkout-pay" disabled={wallets&&wallet.replace(/\D/g,'').length<11} onClick={payNow}>Pay {money(amountPaisa)} securely</button>
        :<button className="primary full checkout-pay" disabled={reference.trim().length<4} onClick={record}>Confirm {money(amountPaisa)} record</button>}
      <p className="checkout-foot">Halqa never holds your money — it moves member to member and Halqa records it. {digital?'Digital rails run in sandbox until live credentials connect: this confirmation is instant and no real money moves.':''}</p>
    </>}
    {step==='processing'&&<div className="checkout-processing"><i className="pay-spinner"/><b>Contacting {railMeta[1]}…</b><span>Confirming your installment — don't close this window.</span></div>}
    {step==='failed'&&<div className="checkout-failed">
      <div className="failed-badge">!</div>
      <h3>Oops</h3>
      <p className="failed-sub">Something went wrong.<br/>Please try again.</p>
      {error&&<div className="failed-reason">{error}</div>}
      <button type="button" className="failed-cancel" onClick={close}>Cancel <X size={16}/></button>
      <button type="button" className="primary full failed-retry" onClick={()=>{setStep('select');setError('')}}>Try again →</button>
      <p className="checkout-foot">Nothing was recorded — your installment is untouched until a payment confirms.</p>
    </div>}
    {step==='receipt'&&receipt&&<div className="checkout-receipt">
      <div className={`receipt-badge ${receipt.live?'pending':''}`}>{receipt.live?'⏳':'✓'}</div>
      <h3>{receipt.live?'Payment initiated':'Payment confirmed'}</h3>
      <div className="receipt-amount">{money(amountPaisa)}</div>
      <div className="receipt-rows">
        <div><span>Status</span><b className={receipt.live?'':'paid'}>{receipt.live?'AWAITING CONFIRMATION':'PAID'}</b></div>
        <div><span>Rail</span><b>{receipt.rail}{receipt.live?'':' · sandbox'}</b></div>
        <div><span>Reference</span><b className="mono">{receipt.ref}</b></div>
        <div><span>Circle</span><b>{committee.name} · round {round.roundNumber}</b></div>
        <div><span>Date</span><b>{receipt.at.toLocaleString('en-PK')}</b></div>
        <div><span>Paid by</span><b>{user.fullName}</b></div>
      </div>
      <div className="form-actions"><button className="secondary" onClick={copyRef}>{copied?'Copied':'Copy reference'}</button><button className="primary" onClick={()=>void done()}>Done</button></div>
      <p className="checkout-foot">This receipt is recorded on the circle's ledger and counts toward your reliability score.</p>
    </div>}
  </section></div>}

function Growth({committee,active,host,action,myPosition}:{committee:Committee;active?:Round;host:boolean;action:(path:string,body?:unknown)=>Promise<void>;myPosition?:number}){const investment=active?.investments.find(item=>item.status==='ACTIVE');const principal=Number(active?.grossPoolPaisa||0)/100*committee.reinvestRatio;return <div className="growth-stack">{myPosition&&committee.mode!=='INVESTMENT'&&<section className="panel"><div className="panel-head"><div><span className="eyebrow">Your circle · turn #{myPosition}</span><h2>What you’ll get, month by month</h2><p>Your own money’s journey: paying in each round, collecting the pot at your turn, and your estimated profit share at the end. Only your position is shown.</p></div></div><Suspense fallback={<div className="chart-skeleton"/>}><PersonalGrowthChart committee={committee} turnPosition={myPosition}/></Suspense></section>}<RiskConsole committeeId={committee.id} host={host}/><div className="detail-grid"><section className="panel"><div className="panel-head"><div><span className="eyebrow">Member-visible performance</span><h2>{committee.scheme?.name||'No scheme selected'}</h2><p>{committee.scheme?.indicativeRatePct||0}% indicative · risk {committee.scheme?.riskScore||1}/10 · dated source</p></div></div><Suspense fallback={<div className="chart-skeleton"/>}><ProjectionChart principal={principal} rate={committee.scheme?.indicativeRatePct||0} months={Math.max(1,Math.ceil(committee.periodDays/30))}/></Suspense><div className="warning-box">Inspect the risk, range and every deployment. Only the host can execute the locked group mandate.</div></section><section className="panel"><span className="eyebrow">Host execution</span><h2>{investment?'Simulation deployed':'Ready to deploy'}</h2><div className="info-stack"><div><span>Mode</span><b>{modeName[committee.mode]}</b></div><div><span>Allocation</span><b>{Math.round(committee.reinvestRatio*100)}%</b></div><div><span>Principal this round</span><b>{money(principal*100)}</b></div><div><span>Liquidity</span><b>{committee.scheme?.liquidityDays||0} days</b></div><div><span>Access</span><b>{host?'Host control':'Read only'}</b></div></div>{host&&active&&committee.reinvestRatio>0&&(investment?<button className="primary full" onClick={()=>action('liquidate',{idempotencyKey:key()})}>Simulate liquidation</button>:<button className="primary full" onClick={()=>action('invest',{idempotencyKey:key()})}>Simulate deployment</button>)}</section></div></div>}

type ChatMessage={id:string;senderId:string;body:string;sentAt:string;sender?:{fullName:string}};
type ChatHistoryResponse={messages?:ChatMessage[];error?:string};

function chatTime(iso:string){const d=new Date(iso);return isNaN(d.getTime())?'':d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}
function Chat({committeeId,user}:{committeeId:string;user:User}){const [messages,setMessages]=useState<ChatMessage[]>([]);const [body,setBody]=useState('');const [down,setDown]=useState(false);const socket=useRef<Socket|null>(null);const end=useRef<HTMLDivElement|null>(null);useEffect(()=>{let client:Socket|null=null;try{client=io(API_ORIGIN,{auth:{token:tokens.get()},reconnectionAttempts:3});socket.current=client;client.on('connect_error',()=>setDown(true));client.emit('join_room',{committeeId});client.emit('get_history',{committeeId},(response:ChatHistoryResponse)=>{if(response&&Array.isArray(response.messages))setMessages(response.messages)});client.on('new_message',(message:ChatMessage)=>{if(message&&message.id)setMessages(items=>[...items,message])})}catch{setDown(true)}return()=>{try{client?.emit('leave_room',{committeeId});client?.disconnect()}catch{/* already gone */}}},[committeeId]);useEffect(()=>{try{end.current?.scrollIntoView({behavior:'smooth'})}catch{/* jsdom */}},[messages]);const send=()=>{const value=body.trim();if(!value)return;setBody('');try{socket.current?.emit('send_message',{committeeId,body:value})}catch{setDown(true)}};return <section className="chat-panel"><header><div><h2>Committee chat</h2><p>Verified members only</p></div><ShieldCheck/></header>{down&&<div className="warning-box">Live chat is temporarily unreachable. Your committee and payments are unaffected.</div>}<div className="messages">{messages.map(message=><article className={message.senderId===user.id?'mine':''} key={message.id}><div><b>{message.sender?.fullName||'Member'}</b><p>{message.body}</p><span>{chatTime(message.sentAt)}</span></div></article>)}<div ref={end}/></div><footer><input className="field" maxLength={2000} value={body} onChange={e=>setBody(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')send()}} placeholder="Message the committee…"/><button className="primary" onClick={send}><Send/></button></footer></section>}
