import { useEffect, useMemo, useState } from 'react';
import { ChevronLeft, Landmark, Repeat2, ShieldCheck, TrendingUp } from 'lucide-react';
import { api, money } from '../api';
import { emitHalqaAction } from '../lib/events';
import type { Committee, Partner, Scheme, User } from '../types';
import { Field, profitProjection, RateStamp, tierName } from '../components/ui';
import { SHOW_BANK_RAIL, SHOW_INVESTOR_BRIEFING_FEATURES, SIMPLE_MODE } from '../config';

type Mode='ROTATING'|'HYBRID'|'INVESTMENT';
const modes=[
  {id:'ROTATING' as Mode,title:'Classic rotating',cap:25,riskCap:3,icon:<Repeat2/>,description:'Most cash reaches each turn-holder. Capital-preservation schemes only.'},
  {id:'HYBRID' as Mode,title:'Hybrid growth',cap:75,riskCap:6,icon:<TrendingUp/>,description:'Balances periodic payouts with a larger, moderate-risk growth reserve.'},
  {id:'INVESTMENT' as Mode,title:'Investment circle',cap:100,riskCap:8,icon:<Landmark/>,description:'No rotating payout. Capital stays invested until the locked maturity.'},
];
const band=(score:number)=>score<=3?'LOW':score<=6?'MEDIUM':score<=8?'HIGH':'EXTREME';
const GOAL_LABELS:Record<string,string>={HAJJ:'Hajj / Umrah',EDUCATION:'Education',WEDDING:'Wedding',HOME:'Home',BUSINESS:'Business',CUSTOM:'Custom goal'};

export default function CreateCirclePage({user,done,cancel}:{user:User;done:(id:string)=>void;cancel:()=>void}){
  const [schemes,setSchemes]=useState<Scheme[]>([]);const [error,setError]=useState('');const [busy,setBusy]=useState(false);
  const [partner,setPartner]=useState<Partner|null>(null);const [custody,setCustody]=useState(false);const [guaranteed,setGuaranteed]=useState(false);const slotFee=1;
  // Safety Fund: guaranteed on-time payouts funded by a per-round slot fee that
  // pools into the circle's own fund. Works in recorded mode (fund tracked on
  // the ledger, guaranteed up to its balance). Host-configurable fee 0.5–3%.
  const [safetyFund,setSafetyFund]=useState(false);const [slotFeePct,setSlotFeePct]=useState(1);
  const [allowHalqaFill,setAllowHalqaFill]=useState(false);
  const [creditWeighted,setCreditWeighted]=useState(true);
  const [secureEarly,setSecureEarly]=useState(false);
  const [discoverable,setDiscoverable]=useState(true);
  // Profit engine is now composable: tick any combination of levers and the
  // named tier is derived at submit. earn = the Sukoon float+deposit base;
  // patience = the Bazaar tilt; earlyFeeOn = the conventional Priority fee.
  const [earn,setEarn]=useState(true);const [patience,setPatience]=useState(true);const [earlyFeeOn,setEarlyFeeOn]=useState(false);const [earlyFeePct,setEarlyFeePct]=useState(10);const [dividendPooled,setDividendPooled]=useState(true);
  const [goalType,setGoalType]=useState('');const [goalName,setGoalName]=useState('');
  // Gold hedge — a simple, prominent way to back the circle with gold without
  // digging into the generic "advanced invest" controls.
  const [goldHedge,setGoldHedge]=useState(false);const [goldPct,setGoldPct]=useState(20);
  // Deposit coverage: how much of each member's remaining dues their security
  // deposit covers, sized down the turn order. Host-chosen 30–90%. Higher =
  // safer + more deposit yield in the pool, but early turns lock up more cash.
  const [depositCoverage,setDepositCoverage]=useState(70);
  // Host's expectation of how early members pay (days before the due date).
  // Feeds the float part of the projections only; real profit always follows
  // real timestamps. Default = pay at round open (the reference assumption).
  const [leadDays,setLeadDays]=useState(30);
  // Investing a slice of the pool into a market scheme is now an OPTIONAL,
  // advanced choice — off by default. The circle earns the profit engine
  // (float + deposits) with no scheme or risk decision required.
  const [advanced,setAdvanced]=useState(false);
  const [form,setForm]=useState({name:'',mode:'ROTATING' as Mode,memberCap:6,contribution:25000,cadencePreset:'SHORT',periodDays:30,minMembersToStart:3,reinvestPercent:0,schemeId:'',distributionMode:'SHARE',targetRiskScore:3,payoutBuffer:15,liquidityReserve:10,latePenalty:2,guarantorRequired:false,dynamicDeposit:true,profitCollateral:true,capitalDaysDistribution:true,delayedDistributionDays:0,profitRecycling:false,progressivePenalties:true,payoutHoldbackEnabled:true,holdbackReleasePayments:2,featureLockOnDefault:true,smartNudges:true,peerNudges:true,promissoryNoteRequired:false,autoDebitMandateRequired:false,depositYield:0,insuranceReserve:0,postReceiptPenaltyPoints:200,rehabilitationCooldownMonths:6});
  useEffect(()=>{void api<Scheme[]>('/schemes').then(items=>{setSchemes(items);if(items[0])setForm(value=>({...value,schemeId:items[0].id}))});void api<{partner:Partner|null}>('/partner').then(data=>setPartner(data.partner)).catch(()=>setPartner(null))},[]);
  const selectedMode=modes.find(mode=>mode.id===form.mode)!;
  const effectiveRiskCap=Math.min(selectedMode.riskCap,form.targetRiskScore);
  // Rotating/hybrid circles pay out every period, so a scheme must be liquidatable
  // at least 7 days before payout. Investment circles lock capital until maturity.
  const liquidityLimitDays=form.mode==='INVESTMENT'?Number.MAX_SAFE_INTEGER:Math.max(1,form.periodDays-7);
  const eligible=schemes.filter(item=>item.riskScore<=effectiveRiskCap&&item.liquidityDays<=liquidityLimitDays);
  const hiddenByLiquidity=schemes.filter(item=>item.riskScore<=effectiveRiskCap&&item.liquidityDays>liquidityLimitDays).length;
  const scheme=eligible.find(item=>item.id===form.schemeId)||eligible[0];
  const goldScheme=schemes.find(s=>s.slug==='gold-linked-allocation');
  const cycleDays=form.memberCap*form.periodDays;const gross=form.memberCap*form.contribution;const invested=gross*form.reinvestPercent/100;
  const effLead=Math.min(leadDays,Math.max(0,form.periodDays));
  const floatFactor=(effLead+7)/(form.periodDays+7);
  const daily=form.periodDays<7;
  // Deposit-coverage preview. Reference curves (verified by the engine's own
  // tests on the 12×Rs11,667 / Rs140,004 circle) are scaled to THIS pool for
  // the bonus, and used as-is for recovery (a pool-independent ratio). Values
  // are indicative, never guaranteed — same as every other projection here.
  const COV_PTS=[30,40,50,60,70,80,90];
  const BONUS_REF=earlyFeeOn?[12953,13624,14296,14968,15639,16311,16982]:[3619,4291,4962,5634,6306,6977,7649];
  const RECOV_REF=[69.6,73.1,76.6,80.0,83.5,86.9,90.4];
  const interpCov=(pts:number[],cov:number)=>{const i=Math.max(0,Math.min(5,Math.floor((cov-30)/10)));return pts[i]+(pts[i+1]-pts[i])*((cov-30-i*10)/10);};
  const estBonus=earn&&!daily?Math.round(interpCov(BONUS_REF,depositCoverage)*(gross/140004)*(earlyFeeOn?0.9+0.1*floatFactor:0.75+0.25*floatFactor)):0;
  const estRecovery=Math.round(interpCov(RECOV_REF,depositCoverage));
  const covX=(cov:number)=>10+(cov-30)/60*300;
  const projected=useMemo(()=>profitProjection(invested,scheme?.indicativeRatePct||0,cycleDays),[invested,scheme,cycleDays]);
  // Derived engine tier from the composable levers (see the state above).
  const engineTier=form.mode==='INVESTMENT'||daily?'CLASSIC':earlyFeeOn?(earn?'SIGMA':'PRIORITY'):earn?(patience?'BAZAAR':'SUKOON'):'CLASSIC';
  const engineName=engineTier==='CLASSIC'?'Basic (no engine)':tierName(engineTier);
  const isShariah=engineTier!=='PRIORITY'&&engineTier!=='SIGMA';
  const effectiveFeePct=engineTier==='SIGMA'?Math.min(10,earlyFeePct):earlyFeePct;
  const setMode=(mode:Mode)=>{const next=modes.find(item=>item.id===mode)!;const nextRisk=Math.min(next.riskCap,form.targetRiskScore);const nextScheme=schemes.find(item=>item.riskScore<=nextRisk);setForm(value=>({...value,mode,targetRiskScore:nextRisk,reinvestPercent:mode==='INVESTMENT'?Math.max(50,Math.min(next.cap,value.reinvestPercent)):Math.min(next.cap,Math.max(1,value.reinvestPercent)),schemeId:nextScheme?.id||''}))};
  // Pick a risk band: lock the ceiling at the top of that band and auto-select
  // the highest-return scheme that fits — "maximise profit within the level".
  const pickRiskBand=(bandScore:number)=>{const target=Math.min(selectedMode.riskCap,bandScore);const ranked=[...schemes].filter(item=>item.riskScore<=target&&item.liquidityDays<=liquidityLimitDays).sort((a,b)=>b.indicativeRatePct-a.indicativeRatePct);setForm(current=>({...current,targetRiskScore:target,schemeId:ranked[0]?.id||current.schemeId}))};
  const setPercent=(value:number)=>setForm(current=>({...current,reinvestPercent:Math.max(current.mode==='INVESTMENT'?50:0,Math.min(selectedMode.cap,Math.round(value)))}));
  // Turning investing on/off: off resets to a pure rotating circle (0% invested);
  // on seeds a sensible default slice so the controls have something to show.
  const toggleAdvanced=(on:boolean)=>{setAdvanced(on);if(!on)setForm(f=>({...f,mode:'ROTATING' as Mode,reinvestPercent:0,targetRiskScore:3}));else setForm(f=>({...f,reinvestPercent:f.reinvestPercent>0?f.reinvestPercent:15}))};
  const submit=async()=>{setBusy(true);setError('');try{
    const bankRail=custody&&form.mode!=='INVESTMENT';
    const useSafety=safetyFund&&form.mode!=='INVESTMENT';
    const guaranteedOut=(bankRail&&guaranteed)||useSafety;
    const slotBpsOut=bankRail?Math.round(slotFee*100):useSafety?Math.round(slotFeePct*100):0;
    // Gold hedge overrides the investment config with a simple HYBRID gold slice.
    // Guarded: not in INVESTMENT mode (the section is hidden there but the
    // toggle state survives), and only when the period clears gold's 3-day
    // liquidity + the 7-day payout buffer.
    const useGold=goldHedge&&!!goldScheme&&form.mode!=='INVESTMENT'&&form.periodDays>=10;
    const modeOut=useGold?(form.mode==='INVESTMENT'?'INVESTMENT':'HYBRID'):form.mode;
    const reinvestOut=daily?0:useGold?goldPct/100:form.reinvestPercent/100;
    const schemeIdOut=daily?null:useGold?goldScheme!.id:(form.reinvestPercent?scheme?.id:null);
    const riskOut=useGold?Math.max(6,form.targetRiskScore):form.targetRiskScore;
    const publicDiscovery=SHOW_INVESTOR_BRIEFING_FEATURES&&discoverable;
    const committee=await api<Committee>('/committees',{method:'POST',body:JSON.stringify({name:form.name,mode:modeOut,memberCap:form.memberCap,contributionPaisa:String(Math.round(form.contribution*100)),cadencePreset:SIMPLE_MODE?(form.periodDays<10?'VERY_SHORT':form.periodDays<=20?'SHORT':form.periodDays<=45?'MID':'LONG'):form.cadencePreset,periodDays:form.periodDays,minMembersToStart:form.minMembersToStart,reinvestRatio:reinvestOut,riskTolerance:riskOut,schemeId:schemeIdOut,distributionMode:form.distributionMode,orderMode:SHOW_INVESTOR_BRIEFING_FEATURES?(creditWeighted?'CREDIT_WEIGHTED':'RANDOM_BALLOT'):'CREDIT_WEIGHTED',joinPolicy:publicDiscovery?'OPEN_UNTIL_FULL':'INVITE_ONLY',listedPublicly:publicDiscovery,custodyMode:custody?'BANK_CUSTODY':'RECORDED',payoutGuaranteed:guaranteedOut,slotFeeBps:slotBpsOut,tier:engineTier,prizeDrawEnabled:false,earlyFeeBps:earlyFeeOn&&engineTier!=='CLASSIC'?Math.round(effectiveFeePct*100):0,dividendPooled:engineTier==='SIGMA'?dividendPooled:false,depositCoverageBps:depositCoverage*100,expectedPaymentLeadDays:daily?0:effLead,goalType:goalType||undefined,goalName:goalName.trim()||undefined,forwardLiabilityGate:modeOut!=='INVESTMENT'&&secureEarly,allowHalqaFill})});
    await api(`/risk/committee/${committee.id}/policy`,{method:'PATCH',body:JSON.stringify({targetRiskScore:riskOut,payoutBufferBps:form.payoutBuffer*100,liquidityReserveBps:form.liquidityReserve*100,latePenaltyBps:form.latePenalty*100,guarantorRequired:form.guarantorRequired,dynamicDeposit:SIMPLE_MODE?false:form.dynamicDeposit,profitCollateral:form.profitCollateral,capitalDaysDistribution:form.capitalDaysDistribution,delayedDistributionDays:form.delayedDistributionDays,profitRecycling:form.profitRecycling,progressivePenalties:form.progressivePenalties,payoutHoldbackEnabled:form.payoutHoldbackEnabled,holdbackReleasePayments:form.holdbackReleasePayments,featureLockOnDefault:form.featureLockOnDefault,smartNudges:form.smartNudges,peerNudges:form.peerNudges,promissoryNoteRequired:form.promissoryNoteRequired,autoDebitMandateRequired:form.autoDebitMandateRequired,depositYieldBps:form.depositYield*100,insuranceReserveBps:form.insuranceReserve*100,postReceiptPenaltyPoints:form.postReceiptPenaltyPoints,rehabilitationCooldownMonths:form.rehabilitationCooldownMonths,consentText:`I accept ${form.reinvestPercent>0?`a ${form.reinvestPercent}% group allocation into ${scheme?.name||'the selected scheme'} at a risk ceiling of ${form.targetRiskScore}/10, `:''}graduated collateral, payout holdback, progressive penalties, feature locks and the disclosed rehabilitation policy.`})});
    emitHalqaAction('CREATE_CIRCLE');
    done(committee.id);
  }catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  // Simple mode runs creation as a 3-step wizard (name → people & money →
  // engines & review) — one decision per screen, wallet-app style.
  const [wstep,setWstep]=useState(0);
  const WIZ=['Name & goal','People & money','Review & start'];
  if(user.creditScore<700)return <div className="blocked-page"><h2>Hosting locked</h2><p>A reliability score of 700 or higher is required.</p><button className="secondary" onClick={cancel}>Go back</button></div>;
  return <div className="page narrow enter"><button className="back-link" onClick={cancel}><ChevronLeft/>Back</button>
  <div className="page-head"><div><span className="eyebrow">Host studio · locks at start</span><h1>Start a savings circle</h1><p>{SIMPLE_MODE?'Set the name, members, amount, period and a goal. Invite your circle with the code — that\'s it.':'Set the basics and choose how it earns. Investing a slice of the pool, risk and advanced safeguards are all optional — tucked away below.'}</p></div></div>
  {(!SIMPLE_MODE||wstep===2)&&<div className="projection-summary"><div><span>Pool / period</span><strong>{money(gross*100)}</strong></div><div><span>Members</span><strong>{form.memberCap}</strong></div>{!SIMPLE_MODE&&<div><span>Earns via</span><strong>{engineName}</strong></div>}<div><span>Goal</span><strong>{goalType?GOAL_LABELS[goalType]:'General savings'}</strong></div></div>}
  {SIMPLE_MODE&&<div className="wizard-bar">{WIZ.map((label,i)=><button key={label} type="button" className={`wizard-step ${i===wstep?'on':''} ${i<wstep?'done':''}`} onClick={()=>{if(i<wstep)setWstep(i)}}><i>{i<wstep?'✓':i+1}</i><span>{label}</span></button>)}</div>}
  <section className="form-card">{(!SIMPLE_MODE||wstep===0)&&<Field label="Committee name"><input className="field" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="e.g. Islamabad Builders Circle"/></Field>}
  {(!SIMPLE_MODE||wstep===0)&&<div className="form-grid"><Field label="Saving for a goal? (optional)" hint="Give the circle a purpose — Hajj, fees, a wedding, a home. It helps keep the group motivated."><select className="field" value={goalType} onChange={e=>setGoalType(e.target.value)}><option value="">No specific goal</option><option value="HAJJ">Hajj / Umrah</option><option value="EDUCATION">Education / fees</option><option value="WEDDING">Wedding</option><option value="HOME">Home / property</option><option value="BUSINESS">Business</option><option value="CUSTOM">Something else</option></select></Field>{goalType&&<Field label="Goal name (optional)"><input className="field" maxLength={60} value={goalName} onChange={e=>setGoalName(e.target.value)} placeholder="e.g. Ayesha's Hajj 2027"/></Field>}</div>}
  {(!SIMPLE_MODE||wstep===1)&&<div className="form-grid"><Field label="Total members" hint={form.memberCap>30?'Large circle: interval must stay 30 days or less.':'Includes host; independent from duration. Up to 150.'}><input className="field" type="number" min="3" max="150" step="1" value={form.memberCap} onChange={e=>{const count=Math.max(3,Math.min(150,+e.target.value));setForm({...form,memberCap:count,minMembersToStart:Math.min(form.minMembersToStart,count),periodDays:count>30?Math.min(form.periodDays,30):form.periodDays})}}/></Field><Field label="Minimum to start"><input className="field" type="number" min="3" max={form.memberCap} step="1" value={form.minMembersToStart} onChange={e=>setForm({...form,minMembersToStart:Math.max(3,Math.min(form.memberCap,+e.target.value))})}/></Field><Field label="Contribution / period (PKR)"><input className="field" type="number" min="100" step="100" value={form.contribution} onChange={e=>setForm({...form,contribution:+e.target.value})}/></Field><Field label="Exact period (days)" hint={form.periodDays<7?'Daily-tempo circle: runs as a plain rotation — see the note below.':undefined}><input className="field" type="number" min="1" max={form.memberCap>30?30:365} step="1" value={form.periodDays} onChange={e=>setForm({...form,periodDays:Math.max(1,Math.min(form.memberCap>30?30:365,+e.target.value))})}/></Field>{!SIMPLE_MODE&&<Field label="Duration label"><select className="field" value={form.cadencePreset} onChange={e=>setForm({...form,cadencePreset:e.target.value})}><option value="VERY_SHORT">Very short</option><option value="SHORT">Short</option><option value="MID">Mid term</option><option value="LONG">Long term</option></select></Field>}{SIMPLE_MODE&&<Field label="Tempo" hint="Set automatically from the period so the label always matches the days."><div className="field" style={{display:'flex',alignItems:'center',fontWeight:700,fontSize:13}}>{form.periodDays<10?'Very short':form.periodDays<=20?'Short':form.periodDays<=45?'Mid term':'Long term'} · every {form.periodDays} day{form.periodDays===1?'':'s'}</div></Field>}</div>}
  {(!SIMPLE_MODE||wstep===1)&&<div className="halqa-fill-box"><label className="settings-toggle" style={{padding:'4px 0'}}><input type="checkbox" checked={allowHalqaFill} onChange={e=>setAllowHalqaFill(e.target.checked)}/><span><b>Let Halqa join to fill empty seats</b><small>If your circle isn't full when you start, Halqa steps in to fill the remaining seats so you don't have to wait.</small></span></label>
  {allowHalqaFill&&<div className="disclaimer-box"><b>Please note before you turn this on:</b><ul><li><b>Halqa reserves the first turn positions.</b> Halqa's seats collect the earliest payouts; you and your members take the later turns.</li><li><b>A higher management fee applies</b> to circles Halqa helps fill, disclosed in the Fees &amp; Payments Policy.</li><li>Halqa pays its share into every round, so the members holding later turns are still paid on schedule.</li></ul></div>}</div>}
  {(!SIMPLE_MODE||wstep===1)&&form.mode!=='INVESTMENT'&&<div className="halqa-fill-box"><label className="settings-toggle" style={{padding:'4px 0'}}><input type="checkbox" checked={secureEarly} onChange={e=>setSecureEarly(e.target.checked)}/><span><b>🛡 Secure early payouts</b><small>A member taking an early turn must have their <b>forward liability</b> — the installments still owed after they receive the pot — secured before payout: from held collateral, a host-verified guarantee or signed undertaking, or a slice held back from their own payout. This is the strongest guard against someone taking the pool early and stopping their contributions.</small></span></label></div>}
  {(!SIMPLE_MODE||wstep===1)&&form.periodDays<7&&<div className="market-rules"><div><b>Daily-tempo circle — plain rotation only, and riskier</b><p>At intervals under 7 days the earning engines are not applicable: no instrument settles inside the window, so idle money has nothing to earn on. The circle runs as pure record-keeping — payments, turns, scores and penalties still fully enforced — but the faster tempo means missed payments bite sooner. Daily committees work best between traders who see each other every day; for households, longer periods are safer.</p></div></div>}

  {/* SIMPLE MODE — one option, a spectrum, no jargon: the turn-order
      adjustment. Turn 1 pays the full rate, declining position by position to
      zero for the last turn; what early turns pay flows to later turns on the
      same declining weights (position 2 mirrors second-last, and so on). The
      backend earlyFee engine already prices exactly this spectrum. The safety
      fund stays out (custody optics) and the float runs silently. */}
  {SHOW_INVESTOR_BRIEFING_FEATURES&&SIMPLE_MODE&&wstep===2&&<section className="default-policy-panel discovery-controls"><div className="panel-head"><div><span className="eyebrow">Joining &amp; turn order</span><h2>Choose how members find and trust this circle</h2><p>Both controls are optional and lock when the first cycle starts.</p></div></div><div className="policy-toggles compact"><label><input type="checkbox" checked={discoverable} onChange={e=>setDiscoverable(e.target.checked)}/><span><b>Show open slots in Discover</b><small>New members can see each available turn and its projected payout date. Turn this off for invite-only groups.</small></span></label><label><input type="checkbox" checked={creditWeighted} onChange={e=>setCreditWeighted(e.target.checked)}/><span><b>Secure credit-weighted ordering</b><small>Verified members with stronger Halqa repayment records receive earlier high-exposure turns. Off uses a fair random ballot.</small></span></label></div>{creditWeighted&&<div className="secure-explainer"><ShieldCheck/><span><b>Secure circle</b> — the credit-weighted policy is disclosed before anyone joins or bids.</span></div>}</section>}

  {SIMPLE_MODE&&wstep===2&&form.mode!=='INVESTMENT'&&!daily&&<section className="default-policy-panel"><div className="panel-head"><div><span className="eyebrow">Optional · turn-order adjustment</span><h2>Early turns pay a little, late turns earn it</h2><p>One slider. At 0% every turn is equal.</p></div></div>
  <div className="allocation-box"><div className="allocation-head"><div><span className="eyebrow">First turn pays</span><h3>{earlyFeeOn?effectiveFeePct:0}% <small style={{fontWeight:400,opacity:0.7}}>— declining to 0% for the last turn</small></h3></div></div>
  <input className="allocation-slider" type="range" min="0" max="10" step="0.5" value={earlyFeeOn?effectiveFeePct:0} onChange={e=>{const v=+e.target.value;setEarlyFeeOn(v>0);if(v>0)setEarlyFeePct(v)}}/>
  {earlyFeeOn&&<div className="spectrum-preview">{Array.from({length:Math.min(form.memberCap,10)},(_,i)=>{const n=Math.min(form.memberCap,10);const pct=effectiveFeePct*(n-1-i)/(n-1);return <div key={i} title={`Turn ${i+1}: pays ${pct.toFixed(1)}%`}><i style={{height:`${Math.max(6,pct/effectiveFeePct*100)}%`}}/><span>{i+1}</span></div>})}</div>}
  <p className="field-note" style={{opacity:0.85}}>{earlyFeeOn?`Turn 1 collects its pool minus ${effectiveFeePct}%; each later turn pays less on a straight line down to 0%. What's paid is shared back the same way in reverse — position 2 mirrors the second-last, and the final turn earns the most. Halqa keeps none of it.`:'Off — every member collects the identical pool on their turn.'}</p></div>
  <p className="field-note" style={{fontSize:12,opacity:0.8}}>Late fees are standard: 2% / 5% / 10% by lateness tier. After start, a future turn can be listed on the Market and sold at a premium — even to buyers outside this circle.</p></section>}

  {/* PROFIT ENGINE — the primary "how it earns" choice, front and centre */}
  {!SIMPLE_MODE&&form.mode!=='INVESTMENT'&&<section className="default-policy-panel"><div className="panel-head"><div><span className="eyebrow">Profit engine · how this circle earns</span><h2>Earn while everyone saves</h2><p>Money sitting idle between payments earns real, halal profit automatically — no investing decision needed. Pick which levers to switch on.</p></div></div>
  <p className="combo-hint">Tick any combination — the plan is worked out for you. The halal levers stack freely; adding the early fee makes it Early Access (fee only) or Maximum (fee + earning engine).</p>
  <div className="engine-lever-group"><span className="eyebrow">Halal levers · real profit on money that's just waiting</span>
  <div className="policy-toggles compact"><label className={daily?'lever-off':''}><input type="checkbox" disabled={daily} checked={earn&&!daily} onChange={e=>{const on=e.target.checked;setEarn(on);if(!on){setPatience(false)}}}/><span><b>Earn on idle money</b><small>{daily?'Not applicable at daily tempo — no instrument settles inside the window.':'Between the day a member pays and the day someone collects, the pool earns on an Islamic money-market sleeve. Deposits earn too. Shared by how much & how long you put in.'}</small></span></label>
  <label className={earn&&!daily?'':'lever-off'}><input type="checkbox" disabled={!earn||daily} checked={earn&&patience&&!daily} onChange={e=>setPatience(e.target.checked)}/><span><b>Patience pays</b><small>Profit tilts toward later turns (up to 2x) — whoever waits longest earns most. Every deposit still comes back in full.</small></span></label>
  </div>
  {earn&&!daily&&<div className="allocation-box"><div className="allocation-head"><div><span className="eyebrow">How early do members usually pay?</span><h3>{effLead} {effLead===1?'day':'days'} <small style={{fontWeight:400,opacity:0.7}}>before the due date</small></h3></div></div><input className="allocation-slider" type="range" min="0" max={form.periodDays} step="1" value={effLead} onChange={e=>setLeadDays(+e.target.value)}/><p className="field-note" style={{opacity:0.85}}>Earlier payment means more idle days earning, so the projections rise with this setting. It only shapes the estimate — actual profit always follows the real dates people pay.</p></div>}
  </div>
  <div className="engine-lever-group conventional"><span className="eyebrow">Conventional lever · not Shariah-reviewed</span>
  <div className="policy-toggles compact"><label><input type="checkbox" checked={earlyFeeOn} onChange={e=>setEarlyFeeOn(e.target.checked)}/><span><b>Early-turn fee</b><small>An early turn pays a fee out of its own payout, dropping to 0% for the last turn — it becomes a dividend for everyone else, never kept by Halqa. Combine with the earning engine for the maximum-bonus plan.</small></span></label></div>
  {earlyFeeOn&&<><Field label="Early fee % (earliest turn)" hint={engineTier==='SIGMA'?'Hard-capped at 10% when combined with the earning engine — extra return comes from the profit levers, never a higher fee.':'Declines to 0% for the last turn. Default 10%.'}><input className="field" type="number" min="0.5" max={engineTier==='SIGMA'?10:20} step="0.5" value={effectiveFeePct} onChange={e=>setEarlyFeePct(Math.max(0.5,Math.min(engineTier==='SIGMA'?10:20,+e.target.value)))}/></Field>
  <div className="fee-explainer"><div><span>How it works</span><b>The member whose turn it is has this fee <u>deducted from their own payout</u> — e.g. a {effectiveFeePct}% fee on a {money(gross*100)} pool means the first recipient collects {money(Math.round(gross*100*(1-effectiveFeePct/100)))} and the deducted {money(Math.round(gross*100*effectiveFeePct/100))} {engineTier==='SIGMA'&&dividendPooled?'joins the completion pot, shared through the patience split':'is split equally among the other members that same round'}.</b></div><div><span>Declining charge</span><b>Turn #1 pays the full rate; it steps down each turn to 0% for the last turn, who pays nothing and only collects.</b></div><div><span>Net effect</span><b>Early turns pay more than they receive (the cost of early cash); later turns receive more (the reward for waiting). Halqa keeps none of it.</b></div></div>
  {engineTier==='SIGMA'&&<div className="policy-toggles compact"><label><input type="checkbox" checked={dividendPooled} onChange={e=>setDividendPooled(e.target.checked)}/><span><b>Pool the fee into the patience split (recommended)</b><small>Fees flow into the completion pot and out through the patience tilt instead of equal monthly splits — in the engine-verified 12-member reference case this lifts the best annual bonus from Rs 15,285 to Rs 16,982.</small></span></label></div>}</>}</div>
  <div className="engine-summary"><div><span className="eyebrow">Your combination</span><h3>{engineTier==='CLASSIC'?'Basic — no engine':engineTier==='SIGMA'?'Maximum (all levers)':tierName(engineTier)} <i className={isShariah?'rafa-halal':'rafa-conv'}>{isShariah?'halal structure':'not Shariah-reviewed'}</i></h3><p>{engineTier==='SIGMA'?'Every lever at once — the engine-verified maximum-bonus configuration.':engineTier==='BAZAAR'?'Earning engine with the patience tilt toward later turns.':engineTier==='SUKOON'?'Earning engine, profit shared by capital-days.':engineTier==='PRIORITY'?'The early-turn fee only, no investment engine.':'A pure rotating committee — equal in, equal out.'}</p></div></div>
  {!isShariah&&<div className="warning-box">This combination includes the conventional early-turn fee — paying for early access to shared money, funded by the members who take later turns. It has <b>not</b> been reviewed by a Shariah board and is a deliberate opt-in. Untick it for a fully halal circle.</div>}
  </section>}

  {/* Gold hedge — simple, prominent, optional */}
  {!SIMPLE_MODE&&form.mode!=='INVESTMENT'&&goldScheme&&<section className="default-policy-panel gold-hedge"><div className="panel-head"><div><span className="eyebrow">Optional · halal inflation hedge</span><h2>🪙 Back this circle with gold</h2><p>Put a slice of every pool into gold — a Shariah-friendly hedge that tends to hold its value when the rupee weakens. Just choose how much; the rest rotates as normal.</p></div></div>
  <div className="policy-toggles compact"><label className={form.periodDays<10?'lever-off':''}><input type="checkbox" disabled={form.periodDays<10} checked={goldHedge&&form.periodDays>=10} onChange={e=>setGoldHedge(e.target.checked)}/><span><b>Add gold ({goldScheme.indicativeRatePct}% indicative)</b><small>{form.periodDays<10?'Needs a period of at least 10 days — gold takes 3 days to liquidate before each payout.':`Invests the chosen % of each pool into the gold-linked allocation (risk ${goldScheme.riskScore}/10). Halal.`}</small></span></label></div>
  {goldHedge&&<><div className="allocation-box"><div className="allocation-head"><div><span className="eyebrow">Gold allocation</span><h3>{goldPct}% of every pool</h3></div><label><input className="percentage-input" type="number" min="5" max="50" step="5" value={goldPct} onChange={e=>setGoldPct(Math.max(5,Math.min(50,+e.target.value)))}/><span>%</span></label></div><input className="allocation-slider" type="range" min="5" max="50" step="5" value={goldPct} onChange={e=>setGoldPct(+e.target.value)}/></div>
  <div className="info-stack"><div><span>Into gold each cycle</span><b>{money(Math.round(gross*goldPct/100*100))}</b></div><div><span>Est. gold growth / cycle</span><b className="profit">{money(Math.round(profitProjection(gross*goldPct/100,goldScheme.indicativeRatePct,cycleDays)*100))}</b></div><div><span>On Rs 100,000 in a year</span><b>{money(Math.round((100000+profitProjection(100000,goldScheme.indicativeRatePct,365))*100))}</b></div></div></>}
  </section>}

  {/* Protection stays visible — it's about safety, not investing. In simple mode it runs on sane defaults, hidden from the host. */}
  {!SIMPLE_MODE&&<section className="default-policy-panel"><div className="panel-head"><div><span className="eyebrow">Anti-default mandate</span><h2>Lock the prevention stack</h2><p>These rules become immutable when the committee starts.</p></div></div><div className="policy-toggles compact"><label><input type="checkbox" checked={form.payoutHoldbackEnabled} onChange={e=>setForm({...form,payoutHoldbackEnabled:e.target.checked})}/><span><b>Rolling payout holdback</b><small>Retain a buffer until clean follow-up payments.</small></span></label><label><input type="checkbox" checked={form.progressivePenalties} onChange={e=>setForm({...form,progressivePenalties:e.target.checked})}/><span><b>Escalating fixed penalties</b><small>2% / 5% / 10% bands; no compounding interest.</small></span></label><label><input type="checkbox" checked={form.featureLockOnDefault} onChange={e=>setForm({...form,featureLockOnDefault:e.target.checked})}/><span><b>Platform feature lock</b><small>Blocks joining, hosting and marketplace access after default.</small></span></label><label><input type="checkbox" checked={form.smartNudges} onChange={e=>setForm({...form,smartNudges:e.target.checked})}/><span><b>Smart deadline nudges</b><small>Loss-aware reminders before and after deadlines.</small></span></label><label><input type="checkbox" checked={form.dynamicDeposit} onChange={e=>setForm({...form,dynamicDeposit:e.target.checked})}/><span><b>Dynamic security deposit</b><small>Scales with position and default exposure.</small></span></label><label><input type="checkbox" checked={form.guarantorRequired} onChange={e=>setForm({...form,guarantorRequired:e.target.checked})}/><span><b>Guarantor for early turns</b><small>A disclosed second line of accountability.</small></span></label></div></section>}

  {/* Deposit coverage — the safety/liquidity trade-off, made visible */}
  {!SIMPLE_MODE&&form.mode!=='INVESTMENT'&&<section className="default-policy-panel"><div className="panel-head"><div><span className="eyebrow">Security deposit · {depositCoverage}% coverage</span><h2>How much collateral each member posts</h2><p>Deposits are sized down the turn order and always returned in full. Higher coverage means safer circles and a bigger shared profit pool — but the earliest turns lock up more of their own cash.</p></div></div>
  <div className="allocation-box"><div className="allocation-head"><div><span className="eyebrow">Coverage of remaining dues</span><h3>{depositCoverage}% <small style={{fontWeight:400,opacity:0.7}}>({depositCoverage<45?'lighter — more early cash':depositCoverage>75?'strong — maximum protection':'balanced'})</small></h3></div><label><input className="percentage-input" type="number" min="30" max="90" step="5" value={depositCoverage} onChange={e=>setDepositCoverage(Math.max(30,Math.min(90,+e.target.value)))}/><span>%</span></label></div><input className="allocation-slider" type="range" min="30" max="90" step="5" value={depositCoverage} onChange={e=>setDepositCoverage(+e.target.value)}/></div>
  <div className="info-stack"><div><span>Est. best-member bonus / yr</span><b className="profit">{earn?money(estBonus*100):'—'}</b></div><div><span>Recovered if someone defaults</span><b>{estRecovery}%</b></div><div><span>Deposit the 1st turn posts</span><b>{money(Math.round(form.contribution*(form.memberCap-1)*depositCoverage/100*100))}</b></div></div>
  <svg viewBox="0 0 320 140" style={{width:'100%',maxWidth:420,marginTop:12}} role="img" aria-label={`At ${depositCoverage}% coverage, estimated best-member bonus ${money(estBonus*100)} and about ${estRecovery}% recovered on default.`}>
    <line x1="10" y1="112" x2="310" y2="112" stroke="var(--color-border-secondary)" strokeWidth="1"/>
    <polyline points={COV_PTS.map(c=>`${covX(c).toFixed(0)},${(110-(interpCov(RECOV_REF,c)-65)/27*92).toFixed(0)}`).join(' ')} fill="none" stroke="var(--color-success-text,#2e7d32)" strokeWidth="2"/>
    {earn&&<polyline points={COV_PTS.map(c=>`${covX(c).toFixed(0)},${(110-(interpCov(BONUS_REF,c)-BONUS_REF[0])/(BONUS_REF[6]-BONUS_REF[0])*92).toFixed(0)}`).join(' ')} fill="none" stroke="var(--color-info-text,#1c6349)" strokeWidth="2" strokeDasharray="5 3"/>}
    <line x1={covX(depositCoverage).toFixed(0)} y1="14" x2={covX(depositCoverage).toFixed(0)} y2="112" stroke="var(--color-text-tertiary)" strokeWidth="1" strokeDasharray="3 3"/>
    <circle cx={covX(depositCoverage).toFixed(0)} cy={(110-(interpCov(RECOV_REF,depositCoverage)-65)/27*92).toFixed(0)} r="4" fill="var(--color-success-text,#2e7d32)"/>
    {earn&&<circle cx={covX(depositCoverage).toFixed(0)} cy={(110-(interpCov(BONUS_REF,depositCoverage)-BONUS_REF[0])/(BONUS_REF[6]-BONUS_REF[0])*92).toFixed(0)} r="4" fill="var(--color-info-text,#1c6349)"/>}
    <text x="10" y="132" fontSize="10" fill="var(--color-text-tertiary)">30%</text>
    <text x="150" y="132" fontSize="10" fill="var(--color-text-tertiary)">60%</text>
    <text x="296" y="132" fontSize="10" fill="var(--color-text-tertiary)">90%</text>
    <text x="14" y="22" fontSize="10" fill="var(--color-success-text,#2e7d32)">▬ recovery on default{earn?'   ':''}</text>{earn&&<text x="150" y="22" fontSize="10" fill="var(--color-info-text,#1c6349)">- - best-member bonus</text>}
  </svg>
  <p className="field-note" style={{marginTop:8,opacity:0.85}}>{depositCoverage<45?'Lighter deposits leave more cash in early takers’ hands, but if someone runs after their payout the group recovers less of the loss.':depositCoverage>75?'Strongest protection and the largest profit pool, but the first few turns must set aside most of their payout as a deposit until the cycle ends.':'A balanced setting: solid recovery if someone defaults, without over-burdening the early turns.'}{earn&&depositCoverage<65&&(earlyFeeOn?depositCoverage<60:true)?' At this level the Rs 15,000 headline bonus may not be reached — raise coverage (or keep pooled dividends on) to lift it.':''}</p>
  </section>}

  {/* Safety Fund — guaranteed on-time payouts, funded by a per-round slot fee */}
  {!SIMPLE_MODE&&form.mode!=='INVESTMENT'&&<section className="default-policy-panel"><div className="panel-head"><div><span className="eyebrow">Optional · guaranteed payouts</span><h2>🛡️ Add a Safety Fund</h2><p>Members add a small fee each round into the circle's own fund. If someone falls short on your turn, the fund tops up your payout so you're paid in full, on time — guaranteed up to the fund's balance. Never Halqa's money; whatever's left returns to the circle.</p></div></div>
  <div className="policy-toggles compact"><label><input type="checkbox" checked={safetyFund} onChange={e=>setSafetyFund(e.target.checked)}/><span><b>Guarantee on-time payouts</b><small>Turns a “you get paid if everyone pays” circle into a “you get paid, period” one — up to the fund balance.</small></span></label></div>
  {safetyFund&&<><div className="allocation-box"><div className="allocation-head"><div><span className="eyebrow">Slot fee per round</span><h3>{slotFeePct}% <small style={{fontWeight:400,opacity:0.7}}>of each payout</small></h3></div><label><input className="percentage-input" type="number" min="0.5" max="3" step="0.5" value={slotFeePct} onChange={e=>setSlotFeePct(Math.max(0.5,Math.min(3,+e.target.value)))}/><span>%</span></label></div><input className="allocation-slider" type="range" min="0.5" max="3" step="0.5" value={slotFeePct} onChange={e=>setSlotFeePct(+e.target.value)}/></div>
  <div className="info-stack"><div><span>Fund builds to about</span><b>{money(Math.round(gross*slotFeePct/100*form.memberCap/2*100))}</b></div><div><span>Typical cost to a member</span><b>{money(Math.round(gross*slotFeePct/100*0.5*100))}</b></div><div><span>Your payout still lands</span><b>on time, in full*</b></div></div>
  <p className="field-note" style={{marginTop:8,opacity:0.85}}>*Guaranteed up to the fund's balance — a real, funded buffer, not an unlimited promise. The slot fee is a small cost you pay for certainty; it slightly lowers each member's net. In Stage 1 the fund is recorded on the ledger; it becomes bank-held at custody. This is a mutual safety fund (takaful-style), not a Halqa charge.</p></>}
  </section>}

  {/* ADVANCED, OPTIONAL: actively invest a slice of the pool */}
  {!SIMPLE_MODE&&<label className="advanced-toggle"><input type="checkbox" checked={advanced} onChange={e=>toggleAdvanced(e.target.checked)}/><span><b>Also invest a slice of the pool into a market scheme</b><small>Optional & advanced — off by default. Your circle already earns the profit engine above with no extra risk. Turn this on only if you want to actively invest part of each pool (this is where risk, schemes and allocation come in).</small></span></label>}
  {!SIMPLE_MODE&&advanced&&<div className="advanced-invest"><section className="mode-grid">{modes.map(mode=><button key={mode.id} type="button" className={`mode-option ${form.mode===mode.id?'selected':''}`} onClick={()=>setMode(mode.id)}><div>{mode.icon}<span>Up to {mode.cap}% · risk ≤{mode.riskCap}</span></div><h3>{mode.title}</h3><p>{mode.description}</p></button>)}</section>
  <div className="risk-band-box"><div><span className="eyebrow">Risk level for the invested slice</span><h3>{band(form.targetRiskScore)} risk</h3><p>Pick a level — the ceiling locks at the top of that band and the highest-return eligible scheme is selected automatically.</p></div>
  <div className="mode-grid risk-band-grid">{([{id:'LOW',label:'Low',score:3,blurb:'Capital preservation — government paper and savings certificates.'},{id:'MEDIUM',label:'Medium',score:6,blurb:'Balanced growth — income and asset-allocation funds.'},{id:'HIGH',label:'High',score:8,blurb:'Maximum growth — equity, REIT and higher-yield sleeves.'}] as const).map(rb=>{const avail=rb.score<=selectedMode.riskCap;const active=band(form.targetRiskScore)===rb.id;return <button key={rb.id} type="button" disabled={!avail} className={`mode-option ${active?'selected':''}`} onClick={()=>pickRiskBand(rb.score)}><div><span>Risk ≤ {rb.score}/10</span></div><h3>{rb.label}</h3><p>{avail?rb.blurb:`Available in ${rb.score<=6?'Hybrid or Investment':'Investment'} mode.`}</p></button>})}</div></div>
  <Field label="Eligible investment scheme" hint={hiddenByLiquidity>0?`${hiddenByLiquidity} scheme(s) hidden: liquidity exceeds this circle's ${form.periodDays}-day period minus the 7-day payout buffer.`:undefined}><select className="field" value={scheme?.id||''} onChange={e=>setForm({...form,schemeId:e.target.value})}>{eligible.map(item=><option key={item.id} value={item.id}>{item.name} · {item.indicativeRatePct}% · risk {item.riskScore}/10 · {item.liquidityDays}d liquidity</option>)}</select>{scheme&&<RateStamp rateAsOf={scheme.rateAsOf}/>}{eligible.length===0&&<small className="field-warning">No scheme fits this period at the chosen risk ceiling. Extend the period, or lower the level.</small>}</Field>
  <div className="allocation-box"><div className="allocation-head"><div><span className="eyebrow">Growth allocation</span><h3>{form.reinvestPercent}% of every pool</h3></div><label><input className="percentage-input" type="number" min={form.mode==='INVESTMENT'?50:0} max={selectedMode.cap} step="1" value={form.reinvestPercent} onChange={e=>setPercent(+e.target.value)}/><span>%</span></label></div><input className="allocation-slider" type="range" min={form.mode==='INVESTMENT'?50:0} max={selectedMode.cap} step="1" value={form.reinvestPercent} onChange={e=>setPercent(+e.target.value)}/></div>
  <div className="risk-policy-grid"><Field label="Payout buffer %"><input className="field" type="number" min="0" max="30" step="1" value={form.payoutBuffer} onChange={e=>setForm({...form,payoutBuffer:+e.target.value})}/></Field><Field label="Liquidity reserve %"><input className="field" type="number" min="5" max="40" step="1" value={form.liquidityReserve} onChange={e=>setForm({...form,liquidityReserve:+e.target.value})}/></Field><Field label="Late penalty %"><input className="field" type="number" min="0" max="10" step="1" value={form.latePenalty} onChange={e=>setForm({...form,latePenalty:+e.target.value})}/></Field><Field label="Delayed distribution"><select className="field" value={form.delayedDistributionDays} onChange={e=>setForm({...form,delayedDistributionDays:+e.target.value})}><option value="0">None</option><option value="30">30 days</option><option value="60">60 days</option><option value="90">90 days</option></select></Field></div></div>}

  {SHOW_BANK_RAIL&&partner&&<section className="default-policy-panel"><div className="panel-head"><div><span className="eyebrow">Partner rail · {partner.name}{partner.sandbox?' sandbox':''}</span><h2>Custody &amp; guaranteed payouts</h2><p>{user.kycLevel>=2?'The partner collects and disburses. A disclosed slot fee funds this circle’s own guarantee pool.':'Complete verification (Level 2) on your profile to unlock custody.'}</p></div><ShieldCheck/></div>
  {user.kycLevel>=2&&<div className="policy-toggles compact"><label><input type="checkbox" checked={custody} onChange={e=>{setCustody(e.target.checked);if(!e.target.checked)setGuaranteed(false)}}/><span><b>Custody via {partner.name}</b><small>Installments settle by statement matching.</small></span></label></div>}
  </section>}
  {(!SIMPLE_MODE||wstep===2)&&<div className="projection-summary"><div><span>Pool / period</span><strong>{money(gross*100)}</strong></div><div><span>Members</span><strong>{form.memberCap}</strong></div><div><span>Each round</span><strong>{money(form.contribution*100)}</strong></div>{!SIMPLE_MODE&&advanced&&form.reinvestPercent>0&&<><div><span>Invested slice</span><strong>{money(invested*100)}</strong></div><div><span>Est. scheme profit / cycle</span><strong>{money(Math.round(projected*100))}</strong></div></>}<p>{SIMPLE_MODE?'Everyone contributes each round; one member collects the full pool each round until everyone has had a turn. The order and rules lock when the circle starts.':<>This circle earns the <b>{engineName}</b> engine automatically on idle pool days and deposits — indicative, not guaranteed.{advanced&&form.reinvestPercent>0?' The invested slice adds market-scheme profit on top, at the disclosed risk.':''} Every member accepts the locked policy before start.</>}</p></div>}{error&&<div className="error-box">{error}</div>}{SIMPLE_MODE&&wstep<2
  ?<div className="form-actions"><button className="secondary" onClick={()=>wstep===0?cancel():setWstep(wstep-1)}>{wstep===0?'Cancel':'Back'}</button><button className="primary" disabled={wstep===0&&form.name.trim().length<3} onClick={()=>setWstep(wstep+1)}>Continue</button></div>
  :<div className="form-actions"><button className="secondary" onClick={()=>SIMPLE_MODE?setWstep(1):cancel()}>{SIMPLE_MODE?'Back':'Cancel'}</button><button className="primary" disabled={busy||form.name.trim().length<3||(form.reinvestPercent>0&&!scheme)} onClick={submit}>{busy?'Building…':'Create circle'}</button></div>}</section></div>;
}
