import type { PrismaClient, Scheme } from '@prisma/client';

export type SchemeSeed = Omit<Scheme, 'id' | 'riskLevel'> & { minAmountPaisa: bigint; riskLevel?: string };

export const schemeCatalog: SchemeSeed[] = [
  { name: 'Pakistan T-Bill 91 Day', slug: 't-bill-91', category: 'Government Security', issuer: 'State Bank of Pakistan', tenorDays: 91, indicativeRatePct: 11.5, shariahCompliant: false, sourceUrl: 'https://www.sbp.org.pk/ecodata/auction-tbills.pdf', riskScore: 1, liquidityDays: 3, volatilityBps: 35, creditRiskBps: 15, regulatoryStatus: 'CURATED_VERIFIED', eligibilityNotes: 'Anchored to the SBP policy rate of 11.5% (15 Jun 2026); confirm against the latest auction cut-off before deployment.', isActive: true, rateAsOf: new Date('2026-06-15'), minAmountPaisa: 500000n },
  { name: 'Pakistan T-Bill 182 Day', slug: 't-bill-182', category: 'Government Security', issuer: 'State Bank of Pakistan', tenorDays: 182, indicativeRatePct: 11.5, shariahCompliant: false, sourceUrl: 'https://www.sbp.org.pk/ecodata/auction-tbills.pdf', riskScore: 2, liquidityDays: 5, volatilityBps: 55, creditRiskBps: 15, regulatoryStatus: 'CURATED_VERIFIED', eligibilityNotes: 'Anchored to the SBP policy rate of 11.5% (15 Jun 2026); confirm against the latest auction cut-off before deployment.', isActive: true, rateAsOf: new Date('2026-06-15'), minAmountPaisa: 500000n },
  { name: 'Pakistan T-Bill 364 Day', slug: 't-bill-364', category: 'Government Security', issuer: 'State Bank of Pakistan', tenorDays: 364, indicativeRatePct: 11.5, shariahCompliant: false, sourceUrl: 'https://www.sbp.org.pk/ecodata/auction-tbills.pdf', riskScore: 2, liquidityDays: 7, volatilityBps: 85, creditRiskBps: 15, regulatoryStatus: 'CURATED_VERIFIED', eligibilityNotes: 'Anchored to the SBP policy rate of 11.5% (15 Jun 2026); confirm against the latest auction cut-off before deployment.', isActive: true, rateAsOf: new Date('2026-06-15'), minAmountPaisa: 500000n },
  { name: 'Pakistan Investment Bond 3 Year', slug: 'pib-3y', category: 'Government Security', issuer: 'State Bank of Pakistan', tenorDays: 1095, indicativeRatePct: 13.1, shariahCompliant: false, sourceUrl: 'https://www.sbp.org.pk/ecodata/auction_pib.pdf', riskScore: 2, liquidityDays: 15, volatilityBps: 90, creditRiskBps: 15, regulatoryStatus: 'CURATED_VERIFIED', eligibilityNotes: 'Longer sovereign duration for staged circles.', isActive: true, rateAsOf: new Date('2026-05-13'), minAmountPaisa: 500000n },
  { name: 'Pakistan Investment Bond 5 Year', slug: 'pib-5y', category: 'Government Security', issuer: 'State Bank of Pakistan', tenorDays: 1825, indicativeRatePct: 13.8, shariahCompliant: false, sourceUrl: 'https://www.sbp.org.pk/ecodata/auction_pib.pdf', riskScore: 3, liquidityDays: 30, volatilityBps: 140, creditRiskBps: 20, regulatoryStatus: 'CURATED_VERIFIED', eligibilityNotes: 'Medium-duration sovereign ladder leg.', isActive: true, rateAsOf: new Date('2026-05-13'), minAmountPaisa: 500000n },
  { name: 'Government Ijarah Sukuk', slug: 'gov-ijarah-sukuk', category: 'Sovereign Sukuk', issuer: 'Government of Pakistan', tenorDays: 365, indicativeRatePct: 11.8, shariahCompliant: true, sourceUrl: 'https://www.sbp.org.pk/dmmd/sukuk.asp', riskScore: 2, liquidityDays: 7, volatilityBps: 80, creditRiskBps: 20, regulatoryStatus: 'CURATED_VERIFIED', eligibilityNotes: 'Shariah-compliant sovereign exposure.', isActive: true, rateAsOf: new Date('2026-05-13'), minAmountPaisa: 500000n },
  { name: 'Special Savings Certificate', slug: 'special-savings-certificate', category: 'National Savings', issuer: 'Central Directorate of National Savings', tenorDays: 365, indicativeRatePct: 13.44, shariahCompliant: false, sourceUrl: 'https://savings.gov.pk/latest-profit-rates/', riskScore: 1, liquidityDays: 10, volatilityBps: 25, creditRiskBps: 15, regulatoryStatus: 'CURATED_VERIFIED', eligibilityNotes: 'Government retail savings product; bi-annual profit.', isActive: true, rateAsOf: new Date('2026-07-06'), minAmountPaisa: 500000n },
  { name: 'Defence Savings Certificate', slug: 'defence-savings-certificate', category: 'National Savings', issuer: 'Central Directorate of National Savings', tenorDays: 3650, indicativeRatePct: 13.24, shariahCompliant: false, sourceUrl: 'https://savings.gov.pk/latest-profit-rates/', riskScore: 1, liquidityDays: 45, volatilityBps: 20, creditRiskBps: 15, regulatoryStatus: 'CURATED_VERIFIED', eligibilityNotes: 'Long-duration conservative savings product; profit at maturity.', isActive: true, rateAsOf: new Date('2026-07-06'), minAmountPaisa: 500000n },
  { name: 'Regular Income Certificate', slug: 'regular-income-certificate', category: 'National Savings', issuer: 'Central Directorate of National Savings', tenorDays: 1825, indicativeRatePct: 13.56, shariahCompliant: false, sourceUrl: 'https://savings.gov.pk/latest-profit-rates/', riskScore: 2, liquidityDays: 30, volatilityBps: 30, creditRiskBps: 20, regulatoryStatus: 'CURATED_VERIFIED', eligibilityNotes: 'Monthly profit; early encashment terms apply.', isActive: true, rateAsOf: new Date('2026-07-06'), minAmountPaisa: 500000n },
  { name: 'Behbood Savings Certificate', slug: 'behbood-savings-certificate', category: 'National Savings', issuer: 'Central Directorate of National Savings', tenorDays: 3650, indicativeRatePct: 13.68, shariahCompliant: false, sourceUrl: 'https://savings.gov.pk/latest-profit-rates/', riskScore: 1, liquidityDays: 20, volatilityBps: 20, creditRiskBps: 15, regulatoryStatus: 'CURATED_VERIFIED', eligibilityNotes: 'Retiree and eligible saver product; monthly profit.', isActive: true, rateAsOf: new Date('2026-07-06'), minAmountPaisa: 500000n },
  { name: 'Pensioners Benefit Account', slug: 'pensioners-benefit-account', category: 'National Savings', issuer: 'Central Directorate of National Savings', tenorDays: 3650, indicativeRatePct: 12.8, shariahCompliant: false, sourceUrl: 'https://savings.gov.pk/latest-profit-rates/', riskScore: 1, liquidityDays: 15, volatilityBps: 20, creditRiskBps: 15, regulatoryStatus: 'CURATED_VERIFIED', eligibilityNotes: 'Pension-linked low-volatility savings account.', isActive: true, rateAsOf: new Date('2026-05-13'), minAmountPaisa: 500000n },
  { name: 'Pakistan Money Market Fund Basket', slug: 'money-market-fund-basket', category: 'Mutual Fund', issuer: 'SECP-regulated AMCs', tenorDays: 30, indicativeRatePct: 10.9, shariahCompliant: false, sourceUrl: 'https://www.mufap.com.pk/Industry/IndustryStatDaily?tab=1', riskScore: 2, liquidityDays: 1, volatilityBps: 90, creditRiskBps: 45, regulatoryStatus: 'CURATED_VERIFIED', eligibilityNotes: 'Short duration mutual fund sleeve.', isActive: true, rateAsOf: new Date('2026-05-13'), minAmountPaisa: 500000n },
  { name: 'Islamic Money Market Fund Basket', slug: 'islamic-money-market-fund-basket', category: 'Mutual Fund', issuer: 'SECP-regulated AMCs', tenorDays: 30, indicativeRatePct: 10.8, shariahCompliant: true, sourceUrl: 'https://www.mufap.com.pk/Industry/IndustryStatDaily?tab=1', riskScore: 2, liquidityDays: 1, volatilityBps: 90, creditRiskBps: 45, regulatoryStatus: 'CURATED_VERIFIED', eligibilityNotes: 'Shariah-compliant short duration fund sleeve.', isActive: true, rateAsOf: new Date('2026-05-13'), minAmountPaisa: 500000n },
  { name: 'Income Fund Basket', slug: 'income-fund-basket', category: 'Mutual Fund', issuer: 'SECP-regulated AMCs', tenorDays: 180, indicativeRatePct: 12.2, shariahCompliant: false, sourceUrl: 'https://www.mufap.com.pk/Industry/IndustryStatDaily?tab=1', riskScore: 4, liquidityDays: 3, volatilityBps: 260, creditRiskBps: 130, regulatoryStatus: 'CURATED_VERIFIED', eligibilityNotes: 'General bond-heavy income sleeve.', isActive: true, rateAsOf: new Date('2026-05-13'), minAmountPaisa: 500000n },
  { name: 'Islamic Income Fund Basket', slug: 'islamic-income-fund-basket', category: 'Mutual Fund', issuer: 'SECP-regulated AMCs', tenorDays: 180, indicativeRatePct: 12.1, shariahCompliant: true, sourceUrl: 'https://www.mufap.com.pk/Industry/IndustryStatDaily?tab=1', riskScore: 4, liquidityDays: 3, volatilityBps: 260, creditRiskBps: 130, regulatoryStatus: 'CURATED_VERIFIED', eligibilityNotes: 'Shariah-compliant income sleeve.', isActive: true, rateAsOf: new Date('2026-05-13'), minAmountPaisa: 500000n },
  { name: 'Asset Allocation Fund', slug: 'asset-allocation-fund', category: 'Mutual Fund', issuer: 'SECP-regulated AMCs', tenorDays: 365, indicativeRatePct: 13.5, shariahCompliant: false, sourceUrl: 'https://www.mufap.com.pk/Industry/IndustryStatDaily?tab=1', riskScore: 5, liquidityDays: 5, volatilityBps: 520, creditRiskBps: 160, regulatoryStatus: 'CURATED_VERIFIED', eligibilityNotes: 'Flexible multi-asset mutual fund bucket.', isActive: true, rateAsOf: new Date('2026-05-13'), minAmountPaisa: 500000n },
  { name: 'Islamic Asset Allocation Fund', slug: 'islamic-asset-allocation-fund', category: 'Mutual Fund', issuer: 'SECP-regulated AMCs', tenorDays: 365, indicativeRatePct: 13.2, shariahCompliant: true, sourceUrl: 'https://www.mufap.com.pk/Industry/IndustryStatDaily?tab=1', riskScore: 5, liquidityDays: 5, volatilityBps: 520, creditRiskBps: 160, regulatoryStatus: 'CURATED_VERIFIED', eligibilityNotes: 'Shariah-compliant multi-asset mutual fund bucket.', isActive: true, rateAsOf: new Date('2026-05-13'), minAmountPaisa: 500000n },
  { name: 'Balanced Fund Basket', slug: 'balanced-fund-basket', category: 'Mutual Fund', issuer: 'SECP-regulated AMCs', tenorDays: 730, indicativeRatePct: 15.8, shariahCompliant: false, sourceUrl: 'https://www.mufap.com.pk/Industry/IndustryStatDaily?tab=1', riskScore: 6, liquidityDays: 3, volatilityBps: 1100, creditRiskBps: 180, regulatoryStatus: 'CURATED_VERIFIED', eligibilityNotes: 'Higher equity mix than income funds.', isActive: true, rateAsOf: new Date('2026-05-13'), minAmountPaisa: 500000n },
  { name: 'Gold-Linked Allocation', slug: 'gold-linked-allocation', category: 'Commodity', issuer: 'Regulated Pakistani providers', tenorDays: 365, indicativeRatePct: 15.0, shariahCompliant: true, sourceUrl: 'https://www.pmex.com.pk/', riskScore: 6, liquidityDays: 3, volatilityBps: 1700, creditRiskBps: 120, regulatoryStatus: 'CURATED_VERIFIED', eligibilityNotes: 'Commodity-linked defensive diversification.', isActive: true, rateAsOf: new Date('2026-05-13'), minAmountPaisa: 500000n },
  { name: 'Corporate Sukuk Basket', slug: 'corporate-sukuk-basket', category: 'Corporate Debt', issuer: 'PSX-listed issuers', tenorDays: 730, indicativeRatePct: 14.0, shariahCompliant: true, sourceUrl: 'https://www.psx.com.pk/psx/product-and-services/products/debt-market', riskScore: 5, liquidityDays: 30, volatilityBps: 380, creditRiskBps: 260, regulatoryStatus: 'CURATED_VERIFIED', eligibilityNotes: 'Corporate credit exposure with higher yield.', isActive: true, rateAsOf: new Date('2026-05-13'), minAmountPaisa: 500000n },
  { name: 'Bank Term Deposit Basket', slug: 'bank-term-deposit-basket', category: 'Bank Deposit', issuer: 'Scheduled Pakistani Banks', tenorDays: 365, indicativeRatePct: 11.5, shariahCompliant: false, sourceUrl: 'https://www.sbp.org.pk/ecodata/deposit.asp', riskScore: 3, liquidityDays: 30, volatilityBps: 50, creditRiskBps: 75, regulatoryStatus: 'CURATED_VERIFIED', eligibilityNotes: 'Conventional bank fixed deposit basket.', isActive: true, rateAsOf: new Date('2026-05-13'), minAmountPaisa: 500000n },
  { name: 'Islamic Mudarabah Deposit Basket', slug: 'islamic-mudarabah-deposit-basket', category: 'Bank Deposit', issuer: 'Scheduled Pakistani Islamic Banks', tenorDays: 365, indicativeRatePct: 11.2, shariahCompliant: true, sourceUrl: 'https://www.sbp.org.pk/ecodata/deposit.asp', riskScore: 3, liquidityDays: 30, volatilityBps: 50, creditRiskBps: 75, regulatoryStatus: 'CURATED_VERIFIED', eligibilityNotes: 'Islamic bank deposit basket for low volatility.', isActive: true, rateAsOf: new Date('2026-05-13'), minAmountPaisa: 500000n },
  { name: 'PSX Index ETF Basket', slug: 'psx-index-etf-basket', category: 'Equity ETF', issuer: 'Pakistan Stock Exchange', tenorDays: 1095, indicativeRatePct: 18.0, shariahCompliant: false, sourceUrl: 'https://www.psx.com.pk/psx/product-and-services/products/exchange-traded-funds', riskScore: 8, liquidityDays: 3, volatilityBps: 2600, creditRiskBps: 200, regulatoryStatus: 'CURATED_VERIFIED', eligibilityNotes: 'Equity beta for higher-risk circles.', isActive: true, rateAsOf: new Date('2026-05-13'), minAmountPaisa: 500000n },
  { name: 'Shariah Equity Fund Basket', slug: 'shariah-equity-fund-basket', category: 'Equity Fund', issuer: 'SECP-regulated AMCs', tenorDays: 1095, indicativeRatePct: 17.2, shariahCompliant: true, sourceUrl: 'https://www.mufap.com.pk/Industry/IndustryStatDaily?tab=1', riskScore: 8, liquidityDays: 5, volatilityBps: 2400, creditRiskBps: 200, regulatoryStatus: 'CURATED_VERIFIED', eligibilityNotes: 'Higher-risk Shariah equity sleeve.', isActive: true, rateAsOf: new Date('2026-05-13'), minAmountPaisa: 500000n },
  { name: 'Real Estate REIT Basket', slug: 'real-estate-reit-basket', category: 'REIT', issuer: 'SECP/PSX listed REIT managers', tenorDays: 1095, indicativeRatePct: 14.4, shariahCompliant: true, sourceUrl: 'https://www.psx.com.pk/psx/product-and-services/products/reits', riskScore: 7, liquidityDays: 10, volatilityBps: 1200, creditRiskBps: 250, regulatoryStatus: 'CURATED_VERIFIED', eligibilityNotes: 'Property-linked listed trust exposure.', isActive: true, rateAsOf: new Date('2026-05-13'), minAmountPaisa: 500000n },
  { name: 'Invoice Discounting Pool', slug: 'invoice-discounting-pool', category: 'Private Credit', issuer: 'Approved private credit operators', tenorDays: 90, indicativeRatePct: 16.5, shariahCompliant: false, sourceUrl: 'https://www.sbp.org.pk/', riskScore: 7, liquidityDays: 20, volatilityBps: 1500, creditRiskBps: 320, regulatoryStatus: 'ILLUSTRATIVE_HIGHER_RISK', eligibilityNotes: 'Commercial receivables exposure with underwriting.', isActive: true, rateAsOf: new Date('2026-05-13'), minAmountPaisa: 500000n },
  { name: 'Murabaha Trade Finance Basket', slug: 'murabaha-trade-finance-basket', category: 'Islamic Finance', issuer: 'Licensed Islamic finance operators', tenorDays: 180, indicativeRatePct: 13.4, shariahCompliant: true, sourceUrl: 'https://www.sbp.org.pk/', riskScore: 6, liquidityDays: 20, volatilityBps: 280, creditRiskBps: 180, regulatoryStatus: 'ILLUSTRATIVE_CURATED', eligibilityNotes: 'Short Islamic trade-finance exposure.', isActive: true, rateAsOf: new Date('2026-05-13'), minAmountPaisa: 500000n },
  { name: 'Microfinance Deposit Basket', slug: 'microfinance-deposit-basket', category: 'Microfinance', issuer: 'Licensed microfinance institutions', tenorDays: 365, indicativeRatePct: 13.0, shariahCompliant: false, sourceUrl: 'https://www.sbp.org.pk/', riskScore: 6, liquidityDays: 30, volatilityBps: 260, creditRiskBps: 300, regulatoryStatus: 'ILLUSTRATIVE_CURATED', eligibilityNotes: 'Only for curated risk profiles.', isActive: true, rateAsOf: new Date('2026-05-13'), minAmountPaisa: 500000n },
  { name: 'Currency-Hedged Dual Pool', slug: 'currency-hedged-dual-pool', category: 'Multi-Asset', issuer: 'Curated multi-asset manager', tenorDays: 365, indicativeRatePct: 14.1, shariahCompliant: false, sourceUrl: 'https://www.mufap.com.pk/Industry/IndustryStatDaily?tab=1', riskScore: 7, liquidityDays: 15, volatilityBps: 900, creditRiskBps: 220, regulatoryStatus: 'ILLUSTRATIVE_CURATED', eligibilityNotes: 'Prototype hedge overlay for global expansion.', isActive: true, rateAsOf: new Date('2026-05-13'), minAmountPaisa: 500000n },
  // Cryptocurrency — the single highest-risk, EXTREME line. Pakistan has no
  // live government-backed crypto/CBDC, so this is a regulated-venue basket that
  // is explicitly NOT government-backed. Risk 10 keeps it out of committees
  // (which cap at 8) and behind the max-risk ceiling + a double-confirm in the UI.
  { name: 'Digital Asset Basket (Crypto)', slug: 'crypto-basket', category: 'Digital Asset', issuer: 'Regulated digital-asset venues', tenorDays: 365, indicativeRatePct: 30.0, shariahCompliant: false, sourceUrl: 'https://www.secp.gov.pk/', riskScore: 10, liquidityDays: 2, volatilityBps: 6500, creditRiskBps: 500, regulatoryStatus: 'ILLUSTRATIVE_EXTREME_RISK', eligibilityNotes: 'Cryptocurrency exposure — NOT government-backed and extremely volatile. Capital can fall sharply and fast; the indicative rate is speculative, not a promise. The highest-risk option in the catalog; kept out of committees and gated behind an explicit acknowledgement.', isActive: true, rateAsOf: new Date('2026-07-08'), minAmountPaisa: 500000n },
];

export async function syncSchemeCatalog(db: PrismaClient) {
  for (const scheme of schemeCatalog) {
    const riskLevel = scheme.riskScore <= 3 ? 'low' : scheme.riskScore <= 6 ? 'medium' : scheme.riskScore <= 8 ? 'high' : 'extreme';
    await db.scheme.upsert({
      where: { slug: scheme.slug },
      create: { ...scheme, riskLevel },
      update: { ...scheme, riskLevel },
    });
  }
  // Prune orphans: any scheme whose slug is no longer in the catalog (e.g. left
  // behind by a slug rename) is deactivated so it disappears from the catalog
  // without breaking committees that still reference it. Non-destructive.
  const slugs = schemeCatalog.map(scheme => scheme.slug);
  await db.scheme.updateMany({ where: { slug: { notIn: slugs }, isActive: true }, data: { isActive: false } });
}
