import { io } from 'socket.io-client';

const api='http://127.0.0.1:4101/api';
const login=async identity=>{const r=await fetch(`${api}/auth/login`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identity,password:'halqa123'})});if(!r.ok)throw new Error(`Login ${identity}: ${r.status}`);return (await r.json()).accessToken};
const get=async(path,token)=>{const r=await fetch(api+path,{headers:{authorization:`Bearer ${token}`}});if(!r.ok)throw new Error(`${path}: ${r.status}`);return r.json()};
const emit=(socket,event,payload)=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error(`${event} timeout`)),5000);socket.emit(event,payload,response=>{clearTimeout(timer);resolve(response)})});
const sana=await login('sana'); const taha=await login('taha'); const committees=await get('/committees',sana); const target=committees.find(c=>c.status==='ACTIVE'&&c.members.some(m=>m.userId)); if(!target)throw new Error('No active committee');
const member=io('http://127.0.0.1:4101',{auth:{token:sana},transports:['websocket']}); await new Promise((r,j)=>{member.once('connect',r);member.once('connect_error',j)}); const joined=await emit(member,'join_room',{committeeId:target.id});if(!joined.ok)throw new Error(JSON.stringify(joined));const history=await emit(member,'get_history',{committeeId:target.id});if(!Array.isArray(history.messages))throw new Error('History missing');const sent=await emit(member,'send_message',{committeeId:target.id,body:'<b>Socket verification</b>'});if(sent.message.body!=='Socket verification')throw new Error('HTML was not stripped');member.disconnect();
const outsider=io('http://127.0.0.1:4101',{auth:{token:taha},transports:['websocket']});await new Promise((r,j)=>{outsider.once('connect',r);outsider.once('connect_error',j)});const denied=await emit(outsider,'join_room',{committeeId:target.id});outsider.disconnect();if(denied.error!=='Membership required')throw new Error(`Outsider was not denied: ${JSON.stringify(denied)}`);console.log(JSON.stringify({passed:5,checks:['member connection','room join','history','HTML stripping/persistence','non-member denied']}));
