// Rafa's brain — a curated knowledge base with a lightweight intent matcher.
//
// Each entry carries many trigger keywords/synonyms, so a single entry answers
// a wide spread of phrasings (the ~90 entries below cover far more than 90
// literal questions). matchRafa() scores entries by how many of their triggers
// appear in the normalized query and returns the best hit, or null so the UI
// can offer suggestions. Everything here mirrors what the app actually does —
// if a mechanic changes, update the matching entry so Rafa never lies.

import { SIMPLE_MODE } from '../config';

export type RafaEntry = { id: string; cat: string; q: string; a: string; k: string[]; go?: string };

export const RAFA_CATEGORIES = ['Basics', 'Joining & hosting', 'Profit & bonus', 'Safety & defaults', 'Vault & savings', 'Turn market', 'Account'] as const;

export const RAFA_KB: RafaEntry[] = [
  // ---- Basics ----
  { id: 'what-is-halqa', cat: 'Basics', q: 'What is Halqa?', a: "Halqa is your neighbourhood committee (BC / ROSCA), made digital. A trusted group saves together every round, and each round one member collects the whole pot. Halqa records every rupee — references, ledgers, scores — but during Stage 1 it never holds your money.", k: ['what is halqa', 'about halqa', 'explain halqa', 'what does halqa do', 'what is this app', 'what is this'] },
  { id: 'what-is-committee', cat: 'Basics', q: 'What is a committee / BC?', a: "A committee (also called a BC, kameti or ROSCA) is a group savings circle. Everyone puts in a fixed amount each round, and members take turns receiving the full pool. It's an old, trusted way to save and get a lump sum when your turn comes.", k: ['what is a committee', 'what is bc', 'what is kameti', 'what is roration', 'rosca', 'committee meaning', 'what is a circle', 'what is a bc', 'kameti'] },
  { id: 'how-works', cat: 'Basics', q: 'How does it all work?', a: "Join or host a circle, everyone contributes each round, and one member collects the pool each round in a locked order. Pay on time and your reliability score rises. Pick a profit engine and the idle pool earns real profit while it waits.", k: ['how does it work', 'how it works', 'how do i use', 'how to use', 'getting started', 'how to start', 'walk me through', 'guide me'] },
  { id: 'is-it-safe', cat: 'Basics', q: 'Is my money safe?', a: "During Stage 1 Halqa records rather than holds money, so there's no pot for anyone to run off with. Security deposits, payout holdbacks, reliability scores and default bans all protect the group. Every amount is on a transparent ledger you can inspect.", k: ['is it safe', 'safe', 'is my money safe', 'security', 'can i trust', 'is it secure', 'safety', 'risk of losing'] },
  { id: 'is-money-held', cat: 'Basics', q: 'Does Halqa hold my money?', a: "No — not in Stage 1. You transfer directly to whoever's turn it is, and Halqa records the reference. This keeps everything transparent and means there's no central pot at risk.", k: ['do you hold my money', 'does halqa hold', 'where is my money', 'who holds the money', 'custody', 'hold money', 'keep my money'] },
  { id: 'is-halal', cat: 'Basics', q: 'Is Halqa halal?', a: "The Earn and Earn & Share engines are built to be halal: returns come from real profit on genuinely idle money (an Islamic money-market sleeve and Mudarabah deposits), never from charging early turns. The Early Access and Maximum engines add a conventional early fee and are clearly labelled 'not Shariah-reviewed' so you can choose.", k: ['is it halal', 'halal', 'haram', 'shariah', 'islamic', 'riba', 'interest', 'is it islamic', 'sharia'] },
  { id: 'cost', cat: 'Basics', q: 'What does Halqa cost me?', a: "Joining and saving are free. Halqa only takes a small 5% Mudarib share of the profit it helps generate on idle money — never a cut of your savings. Early fees and turn premiums move between members; Halqa keeps none of those.", k: ['what does it cost', 'fees', 'is it free', 'how much cost', 'charges', 'commission', 'what do you charge', 'price'] },

  // ---- Joining & hosting ----
  { id: 'how-join', cat: 'Joining & hosting', q: 'How do I join a committee?', a: "Go to Circles, and either enter an invite code someone shared with you or open a circle that's still forming. You need a reliability score of 550 or higher to join.", k: ['how to join', 'join a committee', 'join circle', 'how do i join', 'invite code', 'joining', 'enter code', 'become a member'], go: 'circles' },
  { id: 'how-host', cat: 'Joining & hosting', q: 'How do I host / create a circle?', a: "Tap 'Host a committee' on the dashboard or the Create button in Circles. You set members, contribution, period, a Low/Medium/High risk level, and the profit levers. You need a 700+ reliability score to host.", k: ['how to host', 'create a committee', 'create circle', 'start a committee', 'make a circle', 'how do i create', 'become a host', 'host a circle', 'new circle'], go: 'create' },
  { id: 'invite-code', cat: 'Joining & hosting', q: 'Where do I find the invite code?', a: "The host sees the invite code inside the committee page under 'Turns & people'. They share it with you, and you paste it in Circles to join.", k: ['invite code', 'where is the code', 'find code', 'share code', 'how to invite', 'invite people', 'invite members'] },
  { id: 'min-members', cat: 'Joining & hosting', q: 'How many members do I need?', a: "A circle needs at least 3 people (including the host) and can have up to 30. The host sets a 'minimum to start' — the circle can begin once that many have joined.", k: ['how many members', 'minimum members', 'how many people', 'members needed', 'group size', 'max members', 'how big'] },
  { id: 'turn-order', cat: 'Joining & hosting', q: 'How is the turn order decided?', a: "The host picks the order mode. Credit-weighted (default) gives earlier turns to higher reliability scores; there's also random ballot and host-assigned. The order locks when the circle starts.", k: ['turn order', 'who goes first', 'how is order', 'my position', 'when is my turn', 'order decided', 'sequence', 'who is first'] },
  { id: 'who-can-host', cat: 'Joining & hosting', q: 'Who can host?', a: "Any member with a reliability score of 700 or higher and no active default. Hosting is a responsibility — you run the schedule and confirm deposits — so it's earned by a clean record.", k: ['who can host', 'can i host', 'host requirements', 'eligible to host', 'need to host', 'score to host'] },

  // ---- Profit & bonus ----
  { id: 'how-bonus', cat: 'Profit & bonus', q: 'Where does the bonus money come from?', a: "Two honest sources. One: real profit on idle money — between your payment and the payout the pool earns on an Islamic money-market sleeve, and deposits earn at the Mudarabah rate. Two: disclosed member-to-member transfers (the early fee, turn premiums, late penalties). Halqa keeps none of the transfers.", k: ['where does bonus come from', 'how bonus', 'bonus money', 'how do i earn', 'where profit', 'how profit', 'extra money', 'how much extra', 'earnings'] },
  { id: 'engines', cat: 'Profit & bonus', q: 'What are the profit engines?', a: "Basic (no engine). Earn (earn on idle money — halal). Earn & Share (Earn plus a patience tilt toward later turns — halal). Early Access (a conventional early fee — not Shariah-reviewed). Maximum (every lever at once — the maximum-bonus setting, not Shariah-reviewed). You tick the levers and the plan is worked out for you.", k: ['what are the engines', 'tiers', 'profit engine', 'sukoon', 'bazaar', 'sigma', 'priority', 'classic', 'earn', 'maximum', 'types of circle', 'what engines', 'engine options'] },
  { id: 'sukoon', cat: 'Profit & bonus', q: 'What is the Earn engine?', a: "The Earn engine is the halal earning base: the pool earns on an Islamic money-market sleeve while it waits, and your security deposit earns at the Mudarabah deposit rate, paid to you. Profit is shared by capital-days — how much and how long you contributed.", k: ['what is earn', 'earn engine', 'sukoon', 'earning base'] },
  { id: 'bazaar', cat: 'Profit & bonus', q: 'What is Bazaar?', a: "Bazaar is Sukoon plus a patience tilt: the float profit and deposit yield are pooled and shared with a bias toward later turns (up to 2x). Whoever waits longest earns the most — and every deposit still returns in full. Fully halal.", k: ['what is bazaar', 'bazaar', 'patience tilt', 'patience pays', 'bazaar engine'] },
  { id: 'sigma', cat: 'Profit & bonus', q: 'What is Sigma?', a: "Sigma stacks every lever in one circle: the 10%-capped early fee plus the float sweep, pooled deposit yield and patience tilt. It's the engine-verified maximum-bonus setting. Because of the fee it's not Shariah-reviewed — choose Sukoon or Bazaar for a halal circle.", k: ['what is sigma', 'sigma', 'maximum bonus', 'best engine', 'highest return', 'most profit', 'sigma engine', 'all levers'] },
  { id: 'early-fee', cat: 'Profit & bonus', q: 'How does the 10% early fee work?', a: "In Priority and Sigma circles an early turn pays a fee — capped at 10%, deducted from that member's own payout, never charged on top. Example: a 10% fee on a Rs 150,000 pool means the first recipient collects Rs 135,000 and the Rs 15,000 goes to the others. The fee steps down each turn to 0% for the last turn.", k: ['early fee', '10 percent', '10%', 'how does the fee work', 'fee explained', 'priority fee', 'sigma fee', 'ten percent'] },
  { id: 'how-much-earn', cat: 'Profit & bonus', q: 'How much can I earn?', a: "It depends on your engine, position and how early you pay. In the reference example — 12 members, Rs 140,000 pool, one year — the best-placed member earns about Rs 17,000 a year on Sigma (pooled), around Rs 7,600 on Bazaar. Numbers are indicative, tied to dated rates, never guaranteed.", k: ['how much can i earn', 'how much profit', 'how much bonus', 'expected return', 'how much money', 'return rate', 'how much will i make', 'earnings example'] },
  { id: 'referral', cat: 'Profit & bonus', q: 'Is there a referral bonus?', a: "Yes — name a friend's username when you sign up, and when you complete your first full cycle they earn a Rs 250 bonus, paid from Halqa's own share of profit — never from members. One bonus per referred member, recorded on the ledger like everything else.", k: ['referral', 'refer a friend', 'invite bonus', 'referral bonus', 'refer someone', 'invitation reward', 'bring a friend'] },
  { id: 'join-gate', cat: 'Safety & defaults', q: 'What decides which circles I can join?', a: "Your reliability score is the gate — 550+ to join, 700+ to host. There's no fixed rupee cap on newcomers: instead, the graduated security deposit and credit-weighted ordering size each member's exposure to their standing, so a bigger circle simply asks for a larger deposit from less-proven members.", k: ['what circles can i join', 'can i join a big circle', 'join eligibility', 'why blocked from joining', 'newcomer limit', 'join limit', 'unlock larger circles', 'score to join'] },
  { id: 'bank-pack', cat: 'Account', q: 'What is the bank pack?', a: "A host can export a 'Bank pack' from the Payments tab — a structured statement of the circle's future contribution schedule, member reliability scores, on-time rates and collateral held. It's built for a bank's credit desk evaluating receivables-backed financing or deposit partnerships.", k: ['bank pack', 'receivables', 'receivables pack', 'export statement', 'cash flow statement', 'bank statement export', 'financing pack'] },
  { id: 'early-bird', cat: 'Profit & bonus', q: 'What is the early-bird boost?', a: "If you pay at least three quarters of your contributions three or more days early, you carry a 1.25x weight in the profit split. Early money genuinely earns more float profit for the whole group, so the boost is funded by profit you helped create — it's fully halal.", k: ['early bird', 'pay early', 'early payment bonus', 'reward for paying early', 'early boost', 'paying early', 'benefit of paying early'] },
  { id: 'patience-tilt', cat: 'Profit & bonus', q: 'Why do later turns earn more?', a: "Later turns carry the circle longest — their money supports everyone else's earlier payouts. So in Bazaar and Sigma the profit tilts toward them (up to 2x). Early turns get the value of cash sooner; late turns get more profit. Both are fair, and disclosed up front.", k: ['later turns earn more', 'last turn', 'patience', 'why later', 'wait longer', 'late position', 'end of circle', 'waiting reward'] },
  { id: 'prize-draw', cat: 'Profit & bonus', q: 'What is the profit gift draw?', a: "An optional feature on the earning engines: half of each round's net float profit is gifted (a hiba) to one on-time payer, chosen by a fair deterministic draw. Your savings are never staked — only profit is gifted. It's pending Shariah board sign-off.", k: ['prize draw', 'gift draw', 'lucky draw', 'hiba', 'profit gift', 'lottery', 'raffle', 'monthly draw'] },
  { id: 'guaranteed', cat: 'Profit & bonus', q: 'Is the profit guaranteed?', a: "No. Profit comes from real market instruments at indicative, dated rates — it can be higher or lower, and is never guaranteed. Your contributions and the rotating payout are the certain part; the investment profit on top is a genuine, modelled estimate.", k: ['is profit guaranteed', 'guaranteed', 'fixed return', 'promised return', 'certain profit', 'guarantee'] },

  // ---- Safety & defaults ----
  { id: 'reliability-score', cat: 'Safety & defaults', q: 'What is the reliability score?', a: "It's your Halqa credit score (300–850, everyone starts at 700). Paying on time raises it; paying late or defaulting lowers it. A higher score gives earlier turns, hosting rights and marketplace access. It follows you across every circle.", k: ['reliability score', 'credit score', 'my score', 'what is the score', 'points', 'rating', 'how score works', 'increase score', 'improve score'] },
  { id: 'what-if-late', cat: 'Safety & defaults', q: 'What happens if I pay late?', a: "You get smart reminders before the deadline. If you're late, a small fixed penalty applies (2% / 5% / 10% by how late, never compounding interest) and your score drops. Clear it promptly and you recover — one late payment isn't the end.", k: ['pay late', 'late payment', 'what if late', 'miss deadline', 'late penalty', 'penalty', 'i am late', 'missed payment', 'cant pay on time'] },
  { id: 'what-if-default', cat: 'Safety & defaults', q: 'What happens if someone defaults?', a: "Defaulting after receiving your payout is the serious case: the account is restricted, deposits and holdbacks can be forfeited to cover the group, and a recovery + cooldown path begins. This is exactly why the order, deposits and holdbacks exist — the group is protected.", k: ['default', 'defaults', 'someone stops paying', 'run away', 'what if default', 'defaulter', 'stops paying', 'abandon', 'not pay after payout'] },
  { id: 'penalty-where', cat: 'Safety & defaults', q: 'Where do late penalties go?', a: "In Sukoon and Bazaar circles, penalties are donated to charity at completion — a penalty may discipline, but it may never enrich anyone. In other circles they're shared among members who never paid late. Halqa keeps none of it.", k: ['where do penalties go', 'penalty money', 'charity', 'what happens to penalties', 'penalty destination', 'fine money'] },
  { id: 'security-deposit', cat: 'Safety & defaults', q: 'What is the security deposit?', a: "A recorded deposit that scales with your position and remaining dues — early turns post more because they owe more later. It protects the group if someone defaults, earns at the Mudarabah rate in the earning engines, and is returned to you in full at completion.", k: ['security deposit', 'deposit', 'what is the deposit', 'collateral', 'why deposit', 'do i get deposit back', 'deposit returned'] },
  { id: 'holdback', cat: 'Safety & defaults', q: 'What is the payout holdback?', a: "When you receive your payout, a small buffer (default 15%) is held back and released after you make a couple of clean follow-up payments. It's a gentle guarantee that early recipients keep paying — and it comes back to you.", k: ['holdback', 'payout holdback', 'why held back', 'buffer', 'part of payout missing', 'held payout', 'retained'] },
  { id: 'protect-default', cat: 'Safety & defaults', q: 'How does Halqa prevent defaults?', a: "Layers: security deposits, rolling payout holdbacks, credit-weighted turn order, progressive penalties, smart reminders, reliability scores that follow you everywhere, and feature locks on default. The Protection tab in each circle shows your live exposure and every safeguard.", k: ['prevent default', 'how prevent', 'stop defaults', 'protection', 'safeguards', 'what stops people', 'anti default', 'avoid default'] },
  { id: 'recover', cat: 'Safety & defaults', q: 'How do I recover after a default?', a: "Clear the outstanding amount, fixed penalties and the rehabilitation fee from the recovery panel on your Profile. Once every case is cleared, access is restored with a low-risk cooldown. The door back is always open.", k: ['recover', 'recovery', 'rehabilitation', 'unban', 'restore account', 'after default', 'get back', 'restricted account', 'account locked'], go: 'profile' },

  // ---- Vault & savings ----
  { id: 'vault', cat: 'Vault & savings', q: 'What is the Vault?', a: "Your personal halal savings pocket on the Profile page. Money in it earns the Islamic money-market rate until you sweep it out — principal plus profit, minus a 5% share on profit only. No committee needed.", k: ['vault', 'sukoon vault', 'savings', 'what is the vault', 'save money', 'savings account', 'piggy bank'], go: 'profile' },
  { id: 'vault-topup', cat: 'Vault & savings', q: 'How do I add money to the vault?', a: "On your Profile, open the Vault card, enter any amount from Rs 100 in 'Top up the vault' and record it. It starts earning from that day. Sweep it out whenever you like.", k: ['add to vault', 'top up', 'deposit vault', 'put money in vault', 'save in vault', 'topup', 'fund vault'], go: 'profile' },
  { id: 'parking', cat: 'Vault & savings', q: 'What is payout parking?', a: "Turn it on and your committee payouts stay recorded in your vault, earning the money-market rate, instead of releasing straight away. It's a one-tap way to keep a lump sum working until you need it. Reversible any time.", k: ['payout parking', 'parking', 'park payout', 'keep earning', 'reinvest payout', 'auto save payout'], go: 'profile' },
  { id: 'withdraw-vault', cat: 'Vault & savings', q: 'How do I take money out of the vault?', a: "Tap 'Sweep vault to my account' on the Profile vault card. You get all your principal plus the accrued profit (minus a 5% Mudarib share on the profit only). It's full-sweep, so it's always simple and clear.", k: ['withdraw vault', 'take out vault', 'sweep', 'cash out', 'get vault money', 'empty vault', 'vault withdrawal'], go: 'profile' },

  // ---- Turn market ----
  { id: 'turn-market', cat: 'Turn market', q: 'What is the turn market?', a: "Need cash sooner, or happy to wait? Members can trade turns. In Classic, Priority and Sigma circles a turn can be sold at a premium (the waiting member earns it). In Sukoon and Bazaar, only free swaps are allowed — selling a turn for money is contested under Shariah.", k: ['turn market', 'marketplace', 'sell turn', 'buy turn', 'trade turn', 'swap turn', 'exchange', 'market', 'change my turn'], go: 'market' },
  { id: 'sell-turn', cat: 'Turn market', q: 'How do I sell or swap my turn?', a: "In a Classic/Priority/Sigma circle, list your future turn on the Market with a premium; another member bids and you both swap positions. In Sukoon/Bazaar, list at zero premium for a free swap. You must have paid your current installment first.", k: ['sell my turn', 'how to sell turn', 'list turn', 'swap my turn', 'trade my position', 'give up turn', 'move my turn'], go: 'market' },
  { id: 'buy-turn', cat: 'Turn market', q: 'How do I get an earlier turn?', a: "On the Market, bid on a listed turn from a member willing to swap. If they accept, you take their earlier position and they take yours. In halal circles the swap is free; in others you agree a premium.", k: ['earlier turn', 'buy earlier turn', 'get cash sooner', 'jump the queue', 'move up', 'earlier position', 'bid on turn'], go: 'market' },

  // ---- Account ----
  { id: 'kyc', cat: 'Account', q: 'What is KYC / verification?', a: "KYC is identity verification. A basic account can join and save. Higher verification unlocks hosting and larger circles. You only verify what's needed for what you want to do.", k: ['kyc', 'verification', 'verify identity', 'verify account', 'identity', 'cnic', 'level 2', 'verify me'] },
  { id: 'passport', cat: 'Account', q: 'What is the Credit Passport?', a: "A signed export of your verified committee history — clean completions, on-time percentage, total recorded. Share the link with a landlord, employer or lender and they can confirm it without a Halqa account. It's valid 90 days.", k: ['passport', 'credit passport', 'export history', 'prove history', 'reference', 'proof of savings', 'credit report'], go: 'profile' },
  { id: 'reminders', cat: 'Account', q: 'Will I get payment reminders?', a: "Yes. Smart reminders reach you before each deadline and after, so you never miss a payment by accident. Members can also send each other private, rate-limited nudges. You'll see them under the bell / Halqa Pulse.", k: ['reminders', 'notifications', 'will i be reminded', 'alerts', 'nudge', 'deadline reminder', 'notify'] },
  { id: 'how-pay', cat: 'Account', q: 'How do I record a payment?', a: "When your installment is due, open the circle's Payments tab and tap 'Record installment'. Digital rails (Raast, JazzCash, EasyPaisa) have a one-tap Pay now; for cash or bank transfer you paste the reference. Halqa logs it — you pay the recipient directly. Tip: switch on Auto-pay and you never have to remember again.", k: ['how to pay', 'record payment', 'make payment', 'pay installment', 'how do i pay', 'submit payment', 'log payment', 'raast'] },
  { id: 'autopay', cat: 'Safety & defaults', q: 'What is auto-pay?', a: "A standing instruction, per circle: flip 'Auto-pay my installment' on the Payments tab, pick your rail, and every round is collected automatically on the due date — no reminders, no accidental late fees. Halqa never holds your money; it only schedules the transfer. You can switch it off any time.", k: ['auto pay', 'autopay', 'auto collect', 'automatic installment', 'mandate', 'collect automatically', 'standing instruction', 'auto debit', 'never miss'] },
  { id: 'chat', cat: 'Account', q: 'Can I talk to my committee?', a: "Yes — every circle has a members-only chat under the Chat tab, so you can coordinate, remind and celebrate together. It's verified members only.", k: ['chat', 'message committee', 'talk to members', 'group chat', 'contact members', 'committee chat'] },
  { id: 'navigate', cat: 'Account', q: 'How do I get around the app?', a: "The bottom bar (or left menu) has Dashboard, Circles, Market, Profile and Settings. Dashboard is your overview, Circles is your committees, Market is turn trading, and Profile holds your reliability score, linked accounts and Credit Passport.", k: ['navigate', 'get around', 'menu', 'where is', 'find', 'how to navigate', 'sections', 'tabs', 'lost', 'where do i'] },
  { id: 'terminal', cat: 'Account', q: 'What is the Terminal?', a: "The Terminal is where you explore every investment scheme with its dated rate, risk and liquidity, and build a transparent sample allocation. It's for understanding where profit comes from — nothing is invested from there.", k: ['terminal', 'what is terminal', 'schemes', 'investments', 'scheme list', 'explore schemes', 'investment options'], go: 'terminal' },

  // ---- Greetings & small talk (so a plain "hello" always works) ----
  { id: 'greet', cat: 'Chat', q: 'Say hello to Rafa', a: "Wa alaikum assalam! 👋 I'm Rafa, your Halqa guide. I can explain how committees work, how you earn, the vault, the tiers, staying safe from defaults — anything. What would you like to know? You can also tap ‘Show me around’ for a live walkthrough.", k: ['hello', 'hi', 'hey', 'yo', 'hiya', 'hola', 'salam', 'salaam', 'assalam', 'assalamualaikum', 'assalam o alaikum', 'aoa', 'a o a', 'greetings', 'good morning', 'good afternoon', 'good evening', 'sup', 'whats up', 'oi', 'namaste', 'howdy'] },
  { id: 'howareyou', cat: 'Chat', q: 'How are you?', a: "Alhamdulillah, running smoothly and happy to help! 🤖 More importantly — how can I help you with Halqa today?", k: ['how are you', 'how r u', 'hows it going', 'how do you do', 'you good', 'how are things', 'kaise ho', 'kese ho'] },
  { id: 'thanks', cat: 'Chat', q: 'Thank you', a: "You're most welcome! 😊 Ask me anything else, any time — that's what I'm here for.", k: ['thanks', 'thank you', 'thankyou', 'thx', 'ty', 'shukria', 'shukriya', 'jazakallah', 'appreciate it', 'appreciated', 'much appreciated', 'cheers', 'great thanks', 'thanks a lot'] },
  { id: 'bye', cat: 'Chat', q: 'Goodbye', a: "Khuda hafiz! 👋 Come back any time you need a hand — happy saving!", k: ['bye', 'goodbye', 'good bye', 'see you', 'see ya', 'later', 'cya', 'khuda hafiz', 'allah hafiz', 'take care', 'gtg', 'got to go'] },
  { id: 'who-are-you', cat: 'Chat', q: 'Who are you?', a: "I'm Rafa, Halqa's little guide bot. 🤖 I answer your questions about committees, saving, earning and staying safe, and I can walk you through the app step by step. Think of me as your friendly co-pilot.", k: ['who are you', 'what are you', 'your name', 'whats your name', 'are you a bot', 'are you real', 'are you human', 'what is rafa', 'who is rafa', 'introduce yourself', 'about you'] },
  { id: 'help', cat: 'Chat', q: 'What can you help with?', a: "Loads! I can explain: what committees are and how to join or host one; how you earn (the profit engines, vault, gold tier); the tiers (Sukoon, Bazaar, Priority, Sigma); safety and what happens with late payments or defaults; the turn market; and your reliability score and passport. Just ask in your own words — or tap a suggestion below.", k: ['help', 'help me', 'what can you do', 'what can you help', 'how can you help', 'what do you know', 'options', 'menu', 'commands', 'what should i ask', 'guide me', 'i need help', 'assist', 'support'] },
  { id: 'affirm', cat: 'Chat', q: 'Got it / okay', a: "👍 Great! Anything else you'd like to know? I'm right here.", k: ['ok', 'okay', 'okey', 'cool', 'nice', 'great', 'awesome', 'got it', 'understood', 'makes sense', 'alright', 'perfect', 'sounds good', 'thik hai', 'theek hai', 'acha'] },
  { id: 'confused', cat: 'Chat', q: "I'm confused", a: "No worries — it's simpler than it looks. 🙂 A committee is a group that saves together and takes turns getting the pot. On top of that, your money earns a bit of halal profit while it waits. Want me to walk you through it live? Tap ‘Show me around’, or ask me one thing at a time.", k: ['confused', 'i dont understand', 'i do not understand', 'dont get it', 'do not get it', 'this is confusing', 'too complicated', 'complicated', 'lost', 'huh', 'what', 'unclear', 'explain simply', 'explain like im 5', 'simple explanation', 'make it simple'] },
  { id: 'joke', cat: 'Chat', q: 'Tell me a joke', a: "Why did the committee member never miss a payment? Because their reliability score was on fire — 🔥 850 and climbing! Okay, back to business: what can I help you with?", k: ['joke', 'make me laugh', 'funny', 'tell me something funny', 'entertain me', 'bored'] },

  // ---- More depth: rounds, cycles, membership ----
  { id: 'round-cycle', cat: 'Basics', q: 'What is a round vs a cycle?', a: "A round is one period (say one month): everyone contributes, and one member collects the pot. A cycle is the full set of rounds — one for each member — so everyone has collected exactly once by the end.", k: ['what is a round', 'what is a cycle', 'round meaning', 'cycle meaning', 'how many rounds', 'what is payout round', 'rounds and cycles'] },
  { id: 'payout-meaning', cat: 'Basics', q: 'What is a payout?', a: "The payout is the pot you collect when it's your turn — everyone's contribution for that round, minus any holdback or (in Priority/Sigma) the early fee. It's the lump sum that makes committees so useful.", k: ['what is a payout', 'payout meaning', 'what is the pot', 'when do i get paid', 'my payout', 'collect the pool', 'lump sum'] },
  { id: 'multiple-committees', cat: 'Joining & hosting', q: 'Can I be in more than one committee?', a: "Yes — you can join several circles and host up to five at once (with a 700+ score). Each is independent, and they all build the same reliability score.", k: ['multiple committees', 'more than one', 'join many', 'how many can i join', 'several circles', 'two committees', 'multiple circles'] },
  { id: 'can-i-leave', cat: 'Joining & hosting', q: 'Can I leave a committee?', a: "You can leave freely before a circle starts. Once it's running you're committed until the cycle completes cleanly — leaving mid-way is treated as abandonment, because everyone's turn depends on everyone paying. Clear your dues and you can exit after completion.", k: ['can i leave', 'leave committee', 'quit', 'exit committee', 'drop out', 'cancel membership', 'get out', 'stop participating'] },
  { id: 'host-disappears', cat: 'Safety & defaults', q: 'What if the host disappears?', a: "The schedule and ledger are locked at start and enforced by Halqa, not the host — so the host can't run off with a pot (in Stage 1 there's no central pot to take). Turns, deposits and payouts follow the recorded rules regardless.", k: ['host disappears', 'host runs away', 'host scam', 'host steals', 'what if host', 'trust the host', 'host fraud', 'organizer runs off'] },
  { id: 'who-can-join', cat: 'Joining & hosting', q: 'Can men join, or is it women only?', a: "Everyone is welcome. Halqa is built to be especially friendly for women (who run most committees in Pakistan), but any verified member can join or host.", k: ['men join', 'women only', 'only for women', 'can men', 'is it for women', 'gender', 'who can use', 'anyone join', 'males'] },
  { id: 'min-contribution', cat: 'Joining & hosting', q: 'What is the minimum contribution?', a: "Committees start from as little as Rs 100 per period. So you can start small and grow as your confidence does.", k: ['minimum contribution', 'how much to start', 'smallest amount', 'minimum amount', 'least i can put', 'starting amount', 'minimum deposit', 'how little'] },

  // ---- More depth: money handling, safety, trust ----
  { id: 'scam', cat: 'Safety & defaults', q: 'Is this a scam / is it legit?', a: "Fair question — always ask it. Halqa is a transparent record-keeper: in Stage 1 it never touches your money, every rupee is on a ledger you can inspect, and the rules (turns, deposits, penalties) are enforced by code, not by trust in a stranger. No guaranteed 'get rich' promises — just your committee, made honest and a bit more rewarding.", k: ['scam', 'is it legit', 'legit', 'fraud', 'ponzi', 'pyramid', 'too good to be true', 'is it fake', 'can i trust this', 'real or fake', 'trustworthy'] },
  { id: 'insured', cat: 'Safety & defaults', q: 'Is my money insured / guaranteed?', a: "No — and anyone promising a guaranteed return is misleading you. Your contributions and rotating payout are the certain part; the extra profit is real but indicative. Committees rely on the group and Halqa's safeguards (deposits, holdbacks, scores, bans), not deposit insurance.", k: ['insured', 'insurance', 'guaranteed', 'is it protected', 'government backed', 'deposit protection', 'is my money guaranteed', 'protected by law'] },
  { id: 'privacy', cat: 'Account', q: 'Is my data private?', a: "Your personal details are yours. Inside a committee, members can see payment status (that's how the group stays accountable), but your data isn't sold, and your Credit Passport is only shared when you choose to generate and send it.", k: ['privacy', 'is my data safe', 'data', 'personal information', 'who sees my data', 'confidential', 'data protection', 'my information'] },
  { id: 'forgot-password', cat: 'Account', q: 'Password help', a: "If you're signed in, you can change your password on your Profile page (Security → Change password) — it signs out every other session for safety. If you're locked out entirely, honest answer: self-service reset isn't built yet in this Stage-1 prototype, so keep your password safe; full account recovery ships with the licensed launch.", k: ['forgot password', 'forgot my password', 'reset password', 'reset my password', 'change password', 'change my password', 'lost my password', 'password', 'cant login', 'cannot log in', 'cant log in', 'locked out', 'login problem', 'sign in problem'], go: 'profile' },
  { id: 'contact-support', cat: 'Account', q: 'How do I contact support?', a: "For anything about a specific circle, the committee chat is the fastest route — your host and members are right there. A dedicated support inbox ships with the licensed launch; in this Stage-1 prototype I'm your first line of help, so ask me anything.", k: ['contact support', 'help desk', 'customer service', 'talk to a human', 'contact halqa', 'report a problem', 'complaint', 'support team', 'get help from staff'] },
  { id: 'currency', cat: 'Basics', q: 'What currency does Halqa use?', a: "Pakistani Rupees (PKR). Amounts are shown in rupees and recorded precisely in paisa behind the scenes so nothing rounds away.", k: ['currency', 'what currency', 'rupees', 'pkr', 'dollars', 'money type', 'which currency'] },

  // ---- More depth: profit mechanics ----
  { id: 'mudarabah', cat: 'Profit & bonus', q: 'What is Mudarabah?', a: "Mudarabah is an Islamic profit-sharing partnership: one side provides the capital, the other manages it, and they share the actual profit by an agreed ratio (loss falls on the capital). Halqa's engine and vault use it — your money earns real profit, and Halqa takes a disclosed 5% share of the profit only.", k: ['mudarabah', 'what is mudarabah', 'mudaraba', 'profit sharing', 'islamic finance', 'how is it structured', 'mudarib'] },
  { id: 'riba', cat: 'Profit & bonus', q: 'What is riba and how do you avoid it?', a: "Riba is interest — a guaranteed extra on a loan, forbidden in Islam. Halqa avoids it in the Sukoon/Bazaar engines by earning only *real, variable* profit on money genuinely put to work (never a fixed charge for lending), and by never pricing the early turns. The Priority/Sigma fee is a conventional exception, clearly labelled so you can choose.", k: ['riba', 'what is riba', 'interest', 'is there interest', 'usury', 'avoid interest', 'interest free', 'sood', 'byaj'] },
  { id: 'which-tier', cat: 'Profit & bonus', q: 'Which tier should I pick?', a: "Want fully halal and simple? Sukoon. Halal and want patience to pay the most? Bazaar. Comfortable with a conventional early fee for a bigger bonus? Priority or Sigma (Sigma stacks everything for the maximum). When in doubt, Bazaar is the sweet spot for most groups.", k: ['which tier', 'what tier should i pick', 'best tier', 'recommend a tier', 'which engine should i use', 'help me choose', 'which one is best', 'what should i pick', 'safest tier', 'which is safest'] },
  { id: 'compound', cat: 'Vault & savings', q: 'Does my vault money compound?', a: "The vault accrues profit on your parked balance while it sits, and you can sweep it out whenever you like. Leave payouts parked round after round and the balance — and the profit on it — keeps growing.", k: ['compound', 'compounding', 'reinvest profit', 'does it grow', 'grow over time', 'accrue', 'interest on vault', 'keep growing'] },
  { id: 'more-shariah', cat: 'Profit & bonus', q: 'How can Halqa be even more Shariah-compliant?', a: "The halal engines already avoid riba and pricing early turns. Going further means a formal Shariah board signing off the prize-draw (hiba) framing and the deposit-yield pooling, publishing the fatwa, and offering a strictly halal-only mode that hides the conventional Priority/Sigma fee entirely. It's on the roadmap.", k: ['more shariah', 'more halal', 'shariah board', 'fatwa', 'shariah certified', 'islamic certification', 'how to make it halal', 'stricter halal', 'shariah compliant certification'] },

  // ---- Reliability & growth ----
  { id: 'improve-score-fast', cat: 'Safety & defaults', q: 'How do I raise my score fast?', a: "Pay every installment on time — better yet, three or more days early (that's +6 each and it also earns you the early-bird profit boost). Finish circles cleanly for a +25 bonus. Consistency is everything; the score follows you across every committee.", k: ['raise score', 'improve score fast', 'increase my score', 'boost score', 'build credit', 'higher score', 'grow my score', 'score up'] },
  { id: 'starting-score', cat: 'Safety & defaults', q: 'What score do I start with?', a: "Everyone starts at 700 — a solid, trusted baseline. Pay on time and it climbs toward 850; miss payments and it falls. You need 550+ to join and 700+ to host.", k: ['starting score', 'what score do i start', 'default score', 'begin score', 'initial score', 'new account score', '700'] },

  // ---- Newer features: vault tiers, gold, crypto, goals, streak, auto-cover ----
  { id: 'vault-tiers', cat: 'Vault & savings', q: 'What are the vault tiers?', a: "Three halal yield tiers, switchable on your Profile: Standard (Islamic money-market, ~10.8%, calmest), Income (Islamic income fund, ~12.1%, a bit more movement), and Gold-linked (~15%, the inflation hedge). Rates are indicative and dated — pick the character that suits you.", k: ['vault tiers', 'vault tier', 'income tier', 'standard tier', 'which vault tier', 'change tier', 'higher vault yield', 'vault options'], go: 'profile' },
  { id: 'gold', cat: 'Vault & savings', q: 'How does gold work in Halqa?', a: "Two ways. One: set your vault tier to Gold-linked (~15% indicative) so parked payouts and top-ups ride the gold hedge. Two: when creating a circle, tick 'Back this circle with gold' and a slice of every pool (5–50%) goes into the gold-linked allocation. Gold tends to hold value when the rupee weakens — a halal hedge, not a guarantee.", k: ['gold', 'gold tier', 'gold linked', 'buy gold', 'gold committee', 'gold hedge', 'sona', 'gold savings', 'invest in gold', 'gold growth'], go: 'profile' },
  { id: 'crypto', cat: 'Profit & bonus', q: 'Can I invest in cryptocurrency?', a: "Yes — but only in your personal vault, never in a committee, and only after you explicitly accept the risk. Hear the warning first: crypto is NOT government-backed, NOT Shariah-compliant, and extremely volatile — you could lose most of it fast. It's rated 10/10 EXTREME; switching your vault to the Crypto tier requires a double confirmation, and the halal tiers (Standard, Income, Gold) are always one tap away. Only use money you can afford to lose completely.", k: ['crypto', 'cryptocurrency', 'bitcoin', 'digital asset', 'btc', 'invest in crypto', 'crypto basket', 'is crypto available', 'coin', 'crypto tier', 'crypto vault'], go: 'profile' },
  { id: 'goal-circles', cat: 'Basics', q: 'What are goal circles?', a: "A committee with a purpose. When creating a circle you can tag it — Hajj/Umrah, education fees, a wedding, a home, a business — and give it a name like 'Ayesha's Hajj 2027'. The money mechanics are identical; the goal keeps the group motivated and shows as a 🎯 chip on the circle card.", k: ['goal circle', 'goal circles', 'hajj circle', 'wedding circle', 'education circle', 'saving for hajj', 'saving for wedding', 'purpose', 'target saving', 'umrah'], go: 'create' },
  { id: 'streak', cat: 'Profit & bonus', q: 'What is the group streak bonus?', a: "When your whole circle pays cleanly and on time, the circle earns a loyalty bonus on its float profit — +5% per consecutive clean round, up to +50%. One late or missed payment resets it. Discipline literally pays, for everyone at once.", k: ['streak', 'group streak', 'staking streak', 'clean streak', 'streak bonus', 'loyalty bonus', 'on time bonus', 'group bonus'] },
  { id: 'auto-cover', cat: 'Safety & defaults', q: 'What is vault auto-cover?', a: "An opt-in safety net on your Profile: if you ever miss an installment deadline and your vault holds enough, Halqa settles that installment from your own vault automatically — so a busy week never becomes a default. Your score still takes the small late hit (fairness to the group), but your standing and the circle stay safe.", k: ['auto cover', 'auto-cover', 'autocover', 'safety net', 'cover from vault', 'automatic payment', 'auto pay', 'miss a payment automatically', 'vault covers'], go: 'profile' },
  { id: 'vault-tab', cat: 'Vault & savings', q: 'Where is the vault?', a: "The Vault now has its own tab in the bottom navigation — the piggy-bank icon. Park payouts there, top up from Rs 100, pick a yield tier, and sweep out anytime. And remember: with auto-cover on, a committee installment you miss is settled from this balance automatically.", k: ['vault tab', 'where vault', 'find vault', 'open vault', 'vault page', 'my vault', 'wheres the vault', 'vault section'], go: 'vault' },
  { id: 'vault-sizing', cat: 'Vault & savings', q: 'Can I split my vault across tiers?', a: "Yes — the Vault tab is a full investment device now. Portion sizing lets you split your balance across the four sleeves (Standard, Income, Gold-linked, Crypto) in any mix totalling 100%; your money accrues at the blended rate of the mix. You also get projected-growth charts with conservative, expected and optimistic paths, a sleeve-by-sleeve risk model, and a money map showing exactly where every rupee is recorded to sit. Any crypto portion needs an explicit high-risk confirmation and never touches committees.", k: ['split vault', 'allocation', 'portion sizing', 'vault mix', 'diversify vault', 'projected growth', 'growth chart', 'risk model', 'where money sits', 'money map', 'blended rate'], go: 'vault' },
  { id: 'daily-circles', cat: 'Basics', q: 'Can I run a daily committee?', a: "Yes — circles can now run on intervals as short as 1 day, the bazaar-trader style. Be aware: at daily tempo the earning engines are NOT applicable (no instrument settles that fast), so daily circles run as plain record-keeping rotations — and the faster pace makes missed payments bite sooner, so they carry more risk. They work best between traders who see each other every day.", k: ['daily committee', 'daily circle', 'daily kameti', 'rozana', 'every day committee', 'bazaar committee', 'trader committee', '1 day', 'one day period', 'short period'], go: 'create' },
  { id: 'big-circles', cat: 'Basics', q: 'How many members can a circle have?', a: "Up to 150 members now. One rule for large circles: anything over 30 members must run on intervals of 30 days or less, so the full cycle doesn't stretch into years. Pot sizes have no cap — big pots come from more members, and each member's exposure is sized by their reliability score and graduated deposit rather than a fixed newcomer ceiling.", k: ['how many members', 'maximum members', 'member limit', 'big committee', 'large circle', '100 members', '150 members', 'members max', 'size limit'], go: 'create' },
  { id: 'lead-days', cat: 'Profit & bonus', q: 'What does "how early do members pay" mean?', a: "When creating a circle, the host can set how many days before the due date members usually pay. Earlier payment means money sits earning longer, so the projected bonus rises with it. It only shapes the estimates — your actual profit always follows the real dates people pay, computed to the day.", k: ['early payment setting', 'lead days', 'how early members pay', 'payment lead', 'pay early setting', 'expected payment', 'float window'], go: 'create' },
  { id: 'safety-fund', cat: 'Safety & defaults', q: 'What is the Safety Fund?', a: "An optional guarantee the host can switch on at creation: every round, a small slot fee (0.5–3%) pools into the circle's own Safety Fund. If someone falls short on your turn, the fund tops up your payout so it arrives in full and on time — guaranteed up to the fund's balance. It's the circle's own money, never Halqa's, and whatever's left returns to the circle at the end.", k: ['safety fund', 'guarantee', 'guaranteed payout', 'slot fee', 'guarantee pool', 'payout guarantee', 'fund tops up', 'covered payout'], go: 'create' },
  { id: 'coverage-slider', cat: 'Safety & defaults', q: 'What is deposit coverage?', a: "The host chooses how strongly the circle is collateralised — deposits sized between 30% and 90% of what each member still owes after their payout (default 70%). Higher coverage means more is recovered if someone defaults AND a bigger shared profit pool (deposits earn), but the earliest turns must lock up more cash. The create screen shows the trade-off live on a chart.", k: ['deposit coverage', 'coverage slider', 'collateral setting', 'coverage percent', 'deposit size', 'how much deposit', 'security deposit amount'], go: 'create' },
  { id: 'receivables-pack', cat: 'Host & running', q: 'What is the Bank pack?', a: "A host-only export on the payments tab of an active circle: a statement of the circle's future scheduled inflows plus each member's reliability score, verification level, on-time percentage and collateral held. It's the document a financier would ask for if they ever wanted to assess the circle — generated straight from the ledger, so it always matches the books.", k: ['bank pack', 'receivables', 'receivables pack', 'export statement', 'circle statement', 'financing export', 'inflow schedule'] },
  { id: 'referral', cat: 'Basics', q: 'Is there a referral bonus?', a: "Yes — name a friend's username when they register, and when they complete their FIRST full cycle you receive Rs 250. It's paid from Halqa's own share, never from member money, and only ever once per referred member. It pays on completion, not signup — so bring people who'll actually finish their circle.", k: ['referral', 'refer a friend', 'invite bonus', 'referral bonus', 'rs 250', 'invite reward', 'refer'] },
  { id: 'urdu', cat: 'Basics', q: 'Is Halqa available in Urdu?', a: "Yes — tap the language button in the sidebar and the app flips to Urdu with full right-to-left layout, instantly. The first-touch screens are translated and more roll out continuously.", k: ['urdu', 'language', 'translate', 'english urdu', 'change language', 'rtl', 'اردو'] },
];

const norm = (s: string) => s.toLowerCase().replace(/[^a-z0-9%\s؀-ۿ]/g, ' ').replace(/\s+/g, ' ').trim();

// Synonym canonicalisation: local vocabulary, romanised Urdu and common
// shorthand all fold onto the KB's canonical tokens before matching. Combined
// with typo tolerance below, each keyword effectively matches thousands of
// surface phrasings.
const SYNONYMS: Record<string, string> = {
  kameti: 'committee', kamety: 'committee', kamaiti: 'committee', beesi: 'committee', bisi: 'committee', bc: 'committee', circle: 'committee', circles: 'committee', committe: 'committee', comittee: 'committee', commitee: 'committee',
  paisa: 'money', paise: 'money', paisey: 'money', raqam: 'money', cash: 'money',
  munafa: 'profit', nafa: 'profit', faida: 'profit', earnings: 'profit', return: 'profit', returns: 'profit',
  sood: 'interest', riba: 'interest',
  sona: 'gold', tola: 'gold',
  qist: 'installment', instalment: 'installment', installments: 'installment', kist: 'installment',
  amanat: 'deposit', zamanat: 'deposit', deposits: 'deposit',
  inam: 'bonus', prize: 'bonus',
  madad: 'help', halp: 'help',
  akaunt: 'account', acount: 'account',
  paswrd: 'password', pasword: 'password',
  wallat: 'vault', walat: 'vault', tijori: 'vault',
  mahana: 'monthly', rozana: 'daily',
  shariah: 'halal', shariat: 'halal', islamic: 'halal', islami: 'halal',
  jurmana: 'penalty', fine: 'penalty', penalties: 'penalty',
  turn: 'turn', bari: 'turn', qura: 'draw', qurandazi: 'draw',
};

// Bounded Levenshtein distance with early exit — the autocorrect. "helo"
// matches "hello", "comitee" matches "committee".
function lev(a: string, b: string, max: number): number {
  if (Math.abs(a.length - b.length) > max) return max + 1;
  let prev = Array.from({ length: b.length + 1 }, (_, i) => i);
  for (let i = 1; i <= a.length; i++) {
    const cur = [i];
    let rowMin = i;
    for (let j = 1; j <= b.length; j++) {
      cur[j] = Math.min(prev[j] + 1, cur[j - 1] + 1, prev[j - 1] + (a[i - 1] === b[j - 1] ? 0 : 1));
      if (cur[j] < rowMin) rowMin = cur[j];
    }
    if (rowMin > max) return max + 1;
    prev = cur;
  }
  return prev[b.length];
}

const canon = (t: string) => SYNONYMS[t] ?? t;
const tokensOf = (s: string) => norm(s).split(' ').filter(Boolean).map(canon);

// A query token matches a keyword token exactly, by synonym, or within a
// length-scaled typo budget (1 edit for 4–6 letters, 2 for 7+).
function tokenMatches(qt: string, kt: string): boolean {
  if (qt === kt) return true;
  if (kt.length < 4 || qt.length < 3) return false;
  const budget = kt.length >= 7 ? 2 : 1;
  return lev(qt, kt, budget) <= budget;
}

// Conversation context: Rafa remembers the topic area of the last answer, so a
// short follow-up ("what about the fee?", "and gold?", "why?") biases toward
// the same territory instead of resetting to a cold match.
let lastCat: string | null = null;
let lastId: string | null = null;
const FOLLOWUP = /\b(it|that|this|those|why|how|more|also|and|what about|kya|aur)\b/;

export function matchRafa(query: string): { entry: RafaEntry; score: number } | null {
  const qTokens = tokensOf(query);
  if (qTokens.join('').length < 2) return null;
  const isFollowup = qTokens.length <= 4 || FOLLOWUP.test(' ' + norm(query) + ' ');
  let best: RafaEntry | null = null;
  let bestScore = 0;
  for (const entry of RAFA_KB) {
    // Simple mode hides the investment layer, so Rafa must not answer with it.
    if (SIMPLE_MODE && (entry.cat === 'Vault & savings' || entry.cat === 'Profit & bonus')) continue;
    let score = 0;
    for (const kw of entry.k) {
      const kTokens = tokensOf(kw);
      if (!kTokens.length) continue;
      // a keyword matches when every one of its tokens is present (fuzzily) in the query
      const hit = kTokens.every(kt => qTokens.some(qt => tokenMatches(qt, kt)));
      if (hit) score += kTokens.length + (kTokens.length > 1 ? 1 : 0);
    }
    if (score > 0 && isFollowup && entry.cat === lastCat && entry.id !== lastId) score += 2; // context bias
    if (score > bestScore) { bestScore = score; best = entry; }
  }
  if (best && bestScore > 0) { lastCat = best.cat; lastId = best.id; return { entry: best, score: bestScore }; }
  return null;
}

// A few high-value questions surfaced as tappable chips when the chat opens.
export const RAFA_STARTERS: string[] = SIMPLE_MODE ? [
  'What is Halqa?',
  'How do I join a committee?',
  'How do I pay my installment?',
  'What is auto-pay?',
  'What happens if I pay late?',
  'Can I sell my turn?',
] : [
  'What is Halqa?',
  'Where does the bonus money come from?',
  'How do I join a committee?',
  'What is the Vault?',
  'How does the 10% early fee work?',
  'What happens if I pay late?',
];
