# -*- coding: utf-8 -*-
"""Generate the Statement of Applicability (HQ-IN-05).

Work register, section AJ3: for each of the 93 controls of ISO/IEC 27001:2022 Annex A, "applicability decided, how
it is met described, evidence kept". A bank's own security review asks for this document by name, and asks for it
early, so it is written now rather than after the meeting.

It is written to be true on 6 October 2026, which means most entries say the control is applicable and NOT yet in
place. That is what a Statement of Applicability is for. A document claiming 93 controls in place at a company that
is not yet incorporated, has no staff and has never held a board meeting would be worse than no document at all:
the first question a reviewer asks is for the evidence, and there would be none.

Status is one of:
  IN PLACE        built, and the evidence can be produced today
  PARTLY          some of it is built and the gap is named
  NOT YET         applicable, nothing built, owner and trigger named
  NOT APPLICABLE  with the reason, which is what a reviewer actually checks
"""
import io, json, os, sys
sys.stdout.reconfigure(encoding='utf-8', errors='replace')

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, 'out')

# (control, name, status, how it is met or why not, evidence)
C = [
('5.1', 'Policies for information security', 'NOT YET',
 'An information security policy is drafted but not yet approved: there is no board to approve it, because the '
 'company is not yet incorporated. The policy set is listed in section AL1 of the work register, and approval is '
 'the first board agenda item after incorporation.',
 'Draft policy set in 05 Governance; work register items for drafting, approval, publication and annual review.'),
('5.2', 'Information security roles and responsibilities', 'PARTLY',
 'One person builds and operates the service today, which is stated plainly rather than dressed as a structure. '
 'The roles a partner bank will require, including a named security officer, are allocated in the governance pack '
 'and take effect on incorporation.',
 'Governance pack; the register of roles in 05 Governance.'),
('5.3', 'Segregation of duties', 'NOT YET',
 'Not achievable with one person, and saying otherwise would be false. The compensating control is that every '
 'change to production is recorded in version control and every money movement is recorded in the ledger and the '
 'audit log, so no action is unattributable even where it is not separated.',
 'Git history; AuditLog and LedgerEntry tables; src/lib/audit.ts.'),
('5.4', 'Management responsibilities', 'NOT YET',
 'Depends on 5.1 and 5.2. The chairman holds the duty in the interim and the governance pack records it.',
 'Governance pack.'),
('5.5', 'Contact with authorities', 'PARTLY',
 'The regulator is identified and the route to it is understood: the State Bank of Pakistan supervises this '
 'activity, which the mentorship of 27 September settled, and the partner bank is the channel for anything '
 'requiring a licence. No incident reporting contact is yet registered because there is nothing yet to report.',
 'Regulatory position in 08 Regulatory and Legal; the bank partnership documents.'),
('5.6', 'Contact with special interest groups', 'NOT YET',
 'No membership of a security forum or CERT yet. Worth doing once there is a company to join in its own name.',
 'Open item.'),
('5.7', 'Threat intelligence', 'PARTLY',
 'Dependency advisories are the only feed in use, through the package manager and the repository host. There is no '
 'paid feed and none is proportionate yet.',
 'npm audit output; repository security advisories.'),
('5.8', 'Information security in project management', 'PARTLY',
 'Security work is carried in the same work register as everything else rather than in a separate track, which is '
 'why sections AJ, AK and AL exist. Each item carries its owner and its file.',
 'Work register sections AJ, AK, AL.'),
('5.9', 'Inventory of information and other associated assets', 'IN PLACE',
 'Every record and every field is listed in the data dictionary, generated from the database schema itself so it '
 'cannot drift. Thirty nine records, six hundred fields, with the fields holding personal data marked.',
 'Data Dictionary (HQ-IN-04), generated by docs/generators/register_rev7/make_data_dictionary.py.'),
('5.10', 'Acceptable use of information and other associated assets', 'NOT YET',
 'An acceptable use policy is drafted and unapproved, as 5.1.',
 'Draft policy set.'),
('5.11', 'Return of assets', 'NOT APPLICABLE',
 'No employee or contractor holds an asset of the company. It becomes applicable at the first hire and is in the '
 'joining and leaving procedure for that day.',
 'Governance pack, joiners and leavers procedure.'),
('5.12', 'Classification of information', 'PARTLY',
 'The data dictionary marks which fields hold personal data and which hold a credential that never leaves the '
 'service. A full four tier classification scheme is not written.',
 'Data Dictionary, the Holds column.'),
('5.13', 'Labelling of information', 'NOT YET',
 'Depends on 5.12.',
 'Open item.'),
('5.14', 'Information transfer', 'IN PLACE',
 'Everything the application sends travels over TLS, and HTTP Strict Transport Security is set with a six month '
 'maximum age including subdomains, so a browser will not fall back. The service returns only JSON and sets a '
 'content security policy that forbids scripts, objects and frames outright.',
 'src/app.ts, the helmet configuration: hsts maxAge 15552000, contentSecurityPolicy defaultSrc none.'),
('5.15', 'Access control', 'IN PLACE',
 'Every route requires a signed in member, and each one checks the specific right it needs before acting: '
 'membership of the circle, hosting of it, or ownership of the record. The checks were audited endpoint by endpoint '
 'and the exceptions are listed as deliberate.',
 'src/lib/guards.ts assertMember and assertHost; tests/api, 276 integration tests of which 93 assert refusal '
 'without access.'),
('5.16', 'Identity management', 'IN PLACE',
 'One account per person, keyed on a unique username, email, mobile and CNIC, and checked for all four at sign up. '
 'Identity is graded in levels: nothing on file, CNIC recorded, bank verified.',
 'prisma/schema.prisma unique constraints; src/routes/auth.ts register; kycLevel.'),
('5.17', 'Authentication information', 'IN PLACE',
 'Passwords are stored only as a bcrypt hash and never returned in any response. The application PIN is hashed the '
 'same way. The service refuses to start in production with a weak or default signing secret.',
 'src/lib/security.ts assertSecretsStrong; the SECRET column of the data dictionary, which lists exactly three '
 'secret fields; tests asserting no credential appears in any response.'),
('5.18', 'Access rights', 'PARTLY',
 'Member rights follow from membership and hosting and are checked on every route. Administrative rights are a '
 'single role flag, which is enough for one operator and will not be enough for a team.',
 'requireAdmin in src/lib/auth.ts; the role column.'),
('5.19', 'Information security in supplier relationships', 'PARTLY',
 'The suppliers are known and listed: the hosting provider, the database provider, the payment service provider, '
 'the credit bureau and the messaging provider. No security schedule is signed with any of them yet because no '
 'agreement is signed with any of them yet.',
 'Work register section AL7; the supplier list in 05 Governance.'),
('5.20', 'Addressing information security within supplier agreements', 'NOT YET',
 'Depends on 5.19 and on the bank partnership, which sets most of these terms.',
 'Open item; heads of terms with the partner bank.'),
('5.21', 'Managing information security in the ICT supply chain', 'PARTLY',
 'Dependencies are pinned by exact version in the lock file, so a build cannot silently take new code. There is no '
 'formal review of a supplier\'s own suppliers.',
 'package-lock.json; the pinned devDependencies in package.json.'),
('5.22', 'Monitoring, review and change management of supplier services', 'NOT YET',
 'Nothing scheduled, because no supplier agreement is in force.',
 'Open item.'),
('5.23', 'Information security for use of cloud services', 'PARTLY',
 'The cloud services in use are named and their regions are known: the application and the interface are hosted '
 'in Singapore and the database is in the same region. Whether that is acceptable under the State Bank\'s cloud '
 'framework is an open question put to the partner bank, and it is in the register as such rather than assumed.',
 'Work register, the hosting question for the bank; tech cost model of 30 September.'),
('5.24', 'Information security incident management planning and preparation', 'NOT YET',
 'No incident response plan is written. It is a drafting item and it has to exist before the first member joins, '
 'not before the first incident.',
 'Open item.'),
('5.25', 'Assessment and decision on information security events', 'PARTLY',
 'Security events are recorded in their own table with their type, the identity involved and the address, which is '
 'what an assessment needs. There is no triage procedure and no alerting.',
 'SecurityEvent table; src/lib/security.ts logSecurity.'),
('5.26', 'Response to information security incidents', 'NOT YET',
 'Depends on 5.24.',
 'Open item.'),
('5.27', 'Learning from information security incidents', 'NOT YET',
 'Depends on 5.24.',
 'Open item.'),
('5.28', 'Collection of evidence', 'IN PLACE',
 'Every change of consequence is recorded with the actor, the action, the record it touched and the time, and the '
 'writes that matter are now inside the same transaction as the change they describe, so a change cannot exist '
 'without its entry.',
 'AuditLog table; src/lib/audit.ts; the thirty two write pairs wrapped in transactions on 6 October.'),
('5.29', 'Information security during disruption', 'NOT YET',
 'No continuity plan is written and no recovery objective is set.',
 'Open item.'),
('5.30', 'ICT readiness for business continuity', 'PARTLY',
 'The hosting and database providers both carry their own redundancy, and the application is stateless so it can '
 'be redeployed from version control in minutes. The database restore has never been rehearsed, which is the part '
 'that matters and the part that is missing.',
 'Deployment configuration; provider documentation. No restore test on record.'),
('5.31', 'Legal, statutory, regulatory and contractual requirements', 'IN PLACE',
 'The legal position is written out against the primary texts, each clause verified against the statute rather '
 'than a summary of it, including the Payment Systems and Electronic Fund Transfers Act, the Banking Companies '
 'Ordinance, the Companies Act and the Insurance Ordinance.',
 '08 Regulatory and Legal; the legal verification of 24 and 25 September.'),
('5.32', 'Intellectual property rights', 'PARTLY',
 'All third party code is open source and its licences are permissive. No licence review document exists.',
 'package.json dependency list.'),
('5.33', 'Protection of records', 'IN PLACE',
 'Retention is set per record class in the data dictionary, with ten years for anything a bank must keep and '
 'shorter periods for operational records.',
 'Data Dictionary, the Retention line on every record.'),
('5.34', 'Privacy and protection of personal information', 'PARTLY',
 'Personal data is marked field by field, consent is recorded and can be withdrawn, and no bureau report is '
 'requested without the member\'s instruction. A privacy notice exists in draft. There is no data protection '
 'officer and no personal data register beyond the dictionary.',
 'Data Dictionary; /api/profile/consent; the consent clauses of the undertaking.'),
('5.35', 'Independent review of information security', 'NOT YET',
 'No independent review has been held. The partner bank\'s own review will be the first, which is the right order: '
 'paying for a review before the design is settled buys an opinion about a design that will change.',
 'Open item.'),
('5.36', 'Compliance with policies, rules and standards for information security', 'PARTLY',
 'The standing checks are automated and run on every change: a screen audit over 73 files, a contrast audit over '
 '40 pairs of colours in both themes, an event audit, and 637 tests. What is not automated is compliance with the '
 'policies, because the policies are not yet approved.',
 'halqa-web/tests/audit-screens.mjs, audit-contrast.mjs, audit-events.mjs; halqa-api test suite.'),
('5.37', 'Documented operating procedures', 'PARTLY',
 'The development and deployment procedure is written down and kept current. The operational procedures a live '
 'service needs, including the collection run and the month end, are not.',
 'HANDOVER/MASTER-CONTEXT.md; the development runbook.'),
('6.1', 'Screening', 'NOT APPLICABLE',
 'No employee or contractor has been engaged. Applicable at the first hire, and in the joiners procedure for that '
 'day.',
 'Governance pack.'),
('6.2', 'Terms and conditions of employment', 'NOT APPLICABLE', 'As 6.1.', 'Governance pack.'),
('6.3', 'Information security awareness, education and training', 'NOT APPLICABLE',
 'As 6.1. The training items in the register are written against the policy set, so they are ready for the first '
 'hire rather than written afterwards.',
 'Work register section AL1.'),
('6.4', 'Disciplinary process', 'NOT APPLICABLE', 'As 6.1.', 'Governance pack.'),
('6.5', 'Responsibilities after termination or change of employment', 'NOT APPLICABLE', 'As 6.1.', 'Governance pack.'),
('6.6', 'Confidentiality or non disclosure agreements', 'PARTLY',
 'Advisers and the mentor have seen the design under an understanding rather than a signed agreement. A standard '
 'non disclosure agreement is drafted and goes out before any further disclosure.',
 'Draft agreement in 05 Governance.'),
('6.7', 'Remote working', 'IN PLACE',
 'All work is remote, on one machine, with full disk encryption, a screen lock and no shared account. Stated as '
 'the actual arrangement rather than a policy about an office that does not exist.',
 'Device configuration; this Statement.'),
('6.8', 'Information security event reporting', 'PARTLY',
 'Members can report anything through the support case route, which records the case and its reference. There is '
 'no separate security reporting address and no published disclosure policy.',
 '/api/support/tickets; SupportTicket table.'),
('7.1', 'Physical security perimeters', 'NOT APPLICABLE',
 'The company holds no premises and no server. The hosting and database providers hold the physical estate and '
 'carry their own certification, which is the control that actually applies here and is covered by 5.23.',
 'Provider certifications.'),
('7.2', 'Physical entry', 'NOT APPLICABLE', 'As 7.1.', 'Provider certifications.'),
('7.3', 'Securing offices, rooms and facilities', 'NOT APPLICABLE',
 'No office is held. An Islamabad office is contemplated and this control applies from the day one is taken.',
 'Provider certifications; the office plan.'),
('7.4', 'Physical security monitoring', 'NOT APPLICABLE', 'As 7.1.', 'Provider certifications.'),
('7.5', 'Protecting against physical and environmental threats', 'NOT APPLICABLE', 'As 7.1.', 'Provider certifications.'),
('7.6', 'Working in secure areas', 'NOT APPLICABLE', 'As 7.1.', 'Provider certifications.'),
('7.7', 'Clear desk and clear screen', 'IN PLACE',
 'The one machine in use locks on a short idle timer and shows no member data on a locked screen.',
 'Device configuration.'),
('7.8', 'Equipment siting and protection', 'NOT APPLICABLE', 'As 7.1.', 'Provider certifications.'),
('7.9', 'Security of assets off premises', 'IN PLACE',
 'The development machine is the only asset and it is encrypted at rest.',
 'Device configuration.'),
('7.10', 'Storage media', 'IN PLACE',
 'No removable media is used for member data at all. Backups stay with the database provider.',
 'This Statement; provider backup configuration.'),
('7.11', 'Supporting utilities', 'NOT APPLICABLE', 'As 7.1.', 'Provider certifications.'),
('7.12', 'Cabling security', 'NOT APPLICABLE', 'As 7.1.', 'Provider certifications.'),
('7.13', 'Equipment maintenance', 'NOT APPLICABLE', 'As 7.1.', 'Provider certifications.'),
('7.14', 'Secure disposal or re use of equipment', 'NOT YET',
 'Applicable to the development machine when it is replaced. A procedure is written for that day; nothing has been '
 'disposed of yet.',
 'Open item.'),
('8.1', 'User endpoint devices', 'PARTLY',
 'The member\'s own device is not managed and cannot be. What the service does is require the application PIN on '
 'every open, record each signed in session as a device the member can see, and let them sign every other session '
 'out in one action.',
 '/api/account/devices; the PIN on open; src/routes/auth.ts set-pin and verify-pin.'),
('8.2', 'Privileged access rights', 'PARTLY',
 'The administrative role is required for the routes that need it, including the delinquency collector, which was '
 'open to any signed in member outside production until 6 October. Access to the hosting and database consoles is '
 'through one account with two factor authentication.',
 'requireAdmin usage; provider account configuration.'),
('8.3', 'Information access restriction', 'IN PLACE',
 'Each query is scoped to the caller: a member\'s own rows by their own id, a circle\'s rows through membership. '
 'The queries were audited for rows loaded wider than they are needed, and one was narrowed because it loaded a '
 'whole user row, credentials included, to read one score.',
 'The leak audit of 5 October; src/routes/protection.ts select narrowing.'),
('8.4', 'Access to source code', 'PARTLY',
 'The repository is private and access is through one account with two factor authentication. There is no branch '
 'protection and no review requirement, because there is one developer.',
 'Repository settings.'),
('8.5', 'Secure authentication', 'IN PLACE',
 'An account locks for fifteen minutes after five wrong attempts. Refresh tokens rotate on every use and a reused '
 'token burns the whole family of sessions descended from that sign in, which is what catches a stolen token. A '
 'malformed or expired token is refused as a sign in problem rather than reported as a service fault.',
 'src/routes/auth.ts refresh; the TOKEN_REUSE_REVOKED security event; tests/api/auth.test.ts.'),
('8.6', 'Capacity management', 'PARTLY',
 'Every list the service returns is bounded with a ceiling and a cursor, which is the capacity control that was '
 'missing: four endpoints returned every row a member had ever generated. There is no capacity forecast and no '
 'load testing.',
 'src/lib/page.ts; tests/page.test.ts; the bounds asserted over the wire in tests/api.'),
('8.7', 'Protection against malware', 'PARTLY',
 'The service runs no uploaded code and executes nothing a member sends. The development machine runs the '
 'operating system\'s own protection. Uploaded images are not scanned, which matters once a payslip or a CNIC '
 'photograph can be uploaded.',
 'Device configuration; the open item for scanning uploads.'),
('8.8', 'Management of technical vulnerabilities', 'PARTLY',
 'Dependency advisories are read and acted on. There is no scheduled scan and no penetration test.',
 'npm audit; repository advisories.'),
('8.9', 'Configuration management', 'IN PLACE',
 'Every configuration value is either in version control or an environment variable named in one place, and the '
 'service refuses to start in production without the ones that matter.',
 'src/lib/security.ts assertSecretsStrong; the environment variable list.'),
('8.10', 'Information deletion', 'PARTLY',
 'Retention is set per record class. The deletion itself is not yet automated, so nothing has been deleted on '
 'schedule because nothing has reached its schedule.',
 'Data Dictionary retention lines; the open item for the deletion job.'),
('8.11', 'Data masking', 'PARTLY',
 'Responses are narrowed to the fields a screen needs, and no response carries a credential. A member\'s CNIC and '
 'mobile are not masked where the member is looking at their own record, which is correct, and are not returned at '
 'all to anybody else.',
 'The response projections in src/routes; the reputation projection, which omits the CNIC.'),
('8.12', 'Data leakage prevention', 'PARTLY',
 'The audit over every response projection is the control in use: each one is read for fields that do not belong '
 'in it. There is no outbound monitoring.',
 'The leak audit of 5 October; tests asserting no credential in any response.'),
('8.13', 'Information backup', 'PARTLY',
 'The database provider takes automated backups on its own schedule. A restore has never been tested, which is the '
 'half that counts.',
 'Provider backup configuration. No restore test on record.'),
('8.14', 'Redundancy of information processing facilities', 'PARTLY',
 'The application layer is redundant by construction at the hosting provider. The database is a single instance.',
 'Deployment configuration.'),
('8.15', 'Logging', 'IN PLACE',
 'Three logs, each for its own purpose: the audit log for who changed what, the security event log for sign in and '
 'token events, and the ledger for every movement of money. Request logging carries the method, the path, the '
 'status and the duration and deliberately carries no member data.',
 'AuditLog, SecurityEvent and LedgerEntry tables; the request logger in src/app.ts.'),
('8.16', 'Monitoring activities', 'NOT YET',
 'There is no error monitoring and no alerting at all, which the operational scan of 22 September found and which '
 'is still true. Nothing watches the service; a failure is noticed when somebody looks.',
 'Open item, and one of the few in this Statement that should be closed before the first member joins.'),
('8.17', 'Clock synchronisation', 'IN PLACE',
 'Every timestamp is set by the database or by the platform, both of which are synchronised, and all are stored in '
 'UTC. Nothing trusts a clock a client sends.',
 'prisma/schema.prisma default now(); the absence of any client supplied timestamp in the write paths.'),
('8.18', 'Use of privileged utility programs', 'PARTLY',
 'Database access outside the application is through one command line client on the development machine. There is '
 'no separate privileged tooling and no session recording.',
 'Device configuration.'),
('8.19', 'Installation of software on operational systems', 'IN PLACE',
 'Nothing is installed on a running system. A change reaches production only as a new deployment built from '
 'version control.',
 'Deployment configuration; git history.'),
('8.20', 'Networks security', 'PARTLY',
 'The service is reachable only over TLS and accepts cross origin requests from a named list of origins. The '
 'database is reachable only from the application. There is no network segmentation beyond what the providers give.',
 'src/app.ts cors origin list; provider network configuration.'),
('8.21', 'Security of network services', 'PARTLY',
 'Rate limits are set per route, tighter on sign in and on anything that sends a code or moves money, and keyed on '
 'the member when signed in and on the address otherwise. The address key collapses an IPv6 address to its prefix, '
 'without which a single subscriber could walk through billions of addresses and never reach a ceiling.',
 'src/lib/rate-limits.ts; tests/errors-and-limits.test.ts.'),
('8.22', 'Segregation of networks', 'NOT APPLICABLE',
 'No network of the company\'s own exists to segregate. The providers segregate their own.',
 'Provider documentation.'),
('8.23', 'Web filtering', 'NOT APPLICABLE',
 'No corporate network and no browsing on behalf of members.',
 'This Statement.'),
('8.24', 'Use of cryptography', 'IN PLACE',
 'Transport is TLS. Passwords and PINs are bcrypt. Tokens are signed and their stored form is a hash, so a stolen '
 'database row cannot be replayed as a session. Document signatures are recorded as a SHA-256 fingerprint of the '
 'exact text signed, which is what makes a signature evidence rather than a claim.',
 'src/lib/auth.ts; hashText in the agreements route; the textHash column.'),
('8.25', 'Secure development life cycle', 'PARTLY',
 'Every change is in version control, type checked, and run against 637 tests before it is considered done. There '
 'is no formal review step, because there is one developer.',
 'Git history; the test suite; the type check.'),
('8.26', 'Application security requirements', 'IN PLACE',
 'The security requirements are written as register items against each endpoint: schema checked input, sign in '
 'required, the specific access right checked, a rate limit, a shared error code, no internal field in any '
 'response, and three integration tests. They are tracked individually rather than as a heading.',
 'Work register section AE3.'),
('8.27', 'Secure system architecture and engineering principles', 'IN PLACE',
 'The principles are written down and enforced rather than described: money is recorded in a double entry ledger '
 'that must balance after every posting, a seat a member cannot sit in cannot be claimed by joining, trading or '
 'the ballot, and the rule lives in one engine that every path asks.',
 'src/lib/score-bands.ts and its 37 tests; the ledger identities in the split engine tests.'),
('8.28', 'Secure coding', 'PARTLY',
 'Input is validated by schema before any logic on every route, including the path. Database access is through a '
 'query builder, so no query is assembled from text. There is no coding standard document and no linter in the '
 'pipeline.',
 'src/lib/params.ts and tests/params.test.ts; the Prisma client; the schema parse at the head of each handler.'),
('8.29', 'Security testing in development and acceptance', 'PARTLY',
 'The suite includes tests that exist only to prove a refusal: 93 assert that an endpoint refuses a member without '
 'access, and others assert that no response carries a credential. There is no independent security test.',
 'tests/api; the access audit of 5 October.'),
('8.30', 'Outsourced development', 'NOT APPLICABLE',
 'No development is outsourced.',
 'This Statement.'),
('8.31', 'Separation of development, test and production environments', 'PARTLY',
 'Development and production are separate deployments with separate databases, and the relaxed security switches '
 'used in development cannot be set in production. Test data is generated per run and never copied from '
 'production.',
 'The environment configuration; the production guards in src/lib/rate-limits.ts and src/lib/security.ts; '
 'tests/api/_harness.ts, which makes its own members.'),
('8.32', 'Change management', 'PARTLY',
 'Every change is a commit with a message saying what it does, and production only takes what is in version '
 'control. There is no change approval step and no release record.',
 'Git history.'),
('8.33', 'Test information', 'IN PLACE',
 'No production data is used for testing. The integration suite makes its own members through the real sign up '
 'endpoint and owns a random block of mobile numbers and CNIC numbers so a run cannot collide with anything else.',
 'tests/api/_harness.ts.'),
('8.34', 'Protection of information systems during audit testing', 'NOT YET',
 'No audit testing has taken place. The rule for when it does is that it runs against a copy, not production.',
 'Open item.'),
]


def main():
    assert len(C) == 93, 'expected 93 Annex A controls, have %d' % len(C)
    os.makedirs(OUT, exist_ok=True)
    counts = {}
    for _, _, status, _, _ in C:
        counts[status] = counts.get(status, 0) + 1

    md = ['# Halqa Statement of Applicability', '',
          'Reference HQ-IN-05. ISO/IEC 27001:2022 Annex A, all 93 controls.', '',
          'For each control: whether it applies to Halqa, how it is met or why it does not apply, and where the '
          'evidence is. Written to be true on 6 October 2026, which is why most entries record a control as '
          'applicable and not yet in place.', '',
          'A document claiming 93 controls in place at a company that is not yet incorporated, has no staff and has '
          'never held a board meeting would be worse than no document: the first thing a reviewer asks for is the '
          'evidence, and there would be none. The gaps are named instead, with what closes each one.', '',
          '## Summary', '',
          '| Status | Controls | Meaning |', '| :-- | --: | :-- |',
          '| In place | %d | Built, and the evidence can be produced today |' % counts.get('IN PLACE', 0),
          '| Partly | %d | Some of it is built and the gap is named |' % counts.get('PARTLY', 0),
          '| Not yet | %d | Applicable, nothing built |' % counts.get('NOT YET', 0),
          '| Not applicable | %d | With the reason |' % counts.get('NOT APPLICABLE', 0),
          '', 'The three that matter most among those not yet in place are 8.16 monitoring, 5.24 incident '
          'response planning and 8.13 the untested backup restore. Each should close before the first member '
          'joins rather than before the first audit.', '']

    LABEL = {'IN PLACE': 'In place', 'PARTLY': 'Partly', 'NOT YET': 'Not yet', 'NOT APPLICABLE': 'Not applicable'}
    section = None
    TITLES = {'5': 'Organisational Controls', '6': 'People Controls', '7': 'Physical Controls',
              '8': 'Technological Controls'}
    for num, name, status, how, evidence in C:
        group = num.split('.')[0]
        if group != section:
            section = group
            md += ['## %s. %s' % (group, TITLES[group]), '']
        md += ['### %s %s' % (num, name), '',
               'Status: %s.' % LABEL[status], '',
               how, '',
               'Evidence: %s' % evidence, '']

    path = os.path.join(OUT, 'STATEMENT-OF-APPLICABILITY.md')
    io.open(path, 'w', encoding='utf-8').write('\n'.join(md))
    print('controls %d | in place %d, partly %d, not yet %d, not applicable %d'
          % (len(C), counts.get('IN PLACE', 0), counts.get('PARTLY', 0),
             counts.get('NOT YET', 0), counts.get('NOT APPLICABLE', 0)))
    print('written', path)


if __name__ == '__main__':
    main()
