import { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, CheckCircle2, Gauge, RefreshCw, Shield, Sparkles } from 'lucide-react';
import { api, money } from '../api';
import type { RiskAssessment, RiskProjection } from '../types';

type Deposit={id:string;amountPaisa:string;status:'PENDING'|'HELD'|'REFUNDED'|'FORFEITED';membership:{turnPosition:number;user:{id:string;fullName:string;username:string}}};
type RiskPolicy={targetRiskScore:number;payoutBufferBps:number;liquidityReserveBps:number;latePenaltyBps:number;guarantorRequired:boolean;dynamicDeposit:boolean;profitCollateral:boolean;capitalDaysDistribution:boolean;delayedDistributionDays:number;profitRecycling:boolean;progressivePenalties:boolean;payoutHoldbackEnabled:boolean;holdbackReleasePayments:number;featureLockOnDefault:boolean;smartNudges:boolean;peerNudges:boolean;promissoryNoteRequired:boolean;autoDebitMandateRequired:boolean;depositYieldBps:number;insuranceReserveBps:number;postReceiptPenaltyPoints:number;rehabilitationCooldownMonths:number;consentText:string};
const defaultPolicy:RiskPolicy={targetRiskScore:3,payoutBufferBps:1500,liquidityReserveBps:1000,latePenaltyBps:200,guarantorRequired:false,dynamicDeposit:true,profitCollateral:true,capitalDaysDistribution:true,delayedDistributionDays:0,profitRecycling:false,progressivePenalties:true,payoutHoldbackEnabled:true,holdbackReleasePayments:2,featureLockOnDefault:true,smartNudges:true,peerNudges:true,promissoryNoteRequired:false,autoDebitMandateRequired:false,depositYieldBps:0,insuranceReserveBps:0,postReceiptPenaltyPoints:200,rehabilitationCooldownMonths:6,consentText:'I understand this committee risk limit, liquidity policy, default controls and that all projections are indicative rather than guaranteed.'};

export function RiskBadge({score,band}:{score:number;band:string}){return <span className={`risk-badge risk-${band.toLowerCase()}`}><i>{score}</i>{band} RISK</span>}
export function RiskMascot({score}:{score:number}){const mood=score<=3?'steady':score<=6?'watching':'alert';return <div className={`risk-orbit mood-${mood}`} title={`Live risk state: ${mood}`}><i/><i/><div>{score}</div><small>NURA</small></div>}

export default function RiskConsole({committeeId,host}:{committeeId:string;host:boolean}){
  const [risk,setRisk]=useState<RiskAssessment|null>(null);const [projection,setProjection]=useState<RiskProjection|null>(null);const [deposits,setDeposits]=useState<Deposit[]>([]);const [refs,setRefs]=useState<Record<string,string>>({});const [policy,setPolicy]=useState<RiskPolicy>(defaultPolicy);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  const load=useCallback(async()=>{try{const [assessment,forecast,depositRows]=await Promise.all([api<RiskAssessment>(`/risk/committee/${committeeId}`),api<RiskProjection>(`/risk/committee/${committeeId}/projection`),api<Deposit[]>(`/committees/${committeeId}/deposits`).catch(()=>[])]);setRisk(assessment);setProjection(forecast);setDeposits(depositRows);setPolicy({...defaultPolicy,...assessment.policy,targetRiskScore:assessment.riskTolerance} as RiskPolicy)}catch(reason){setError((reason as Error).message)}},[committeeId]);
  useEffect(()=>{void load()},[load]);
  const refresh=async()=>{setBusy(true);setError('');try{await api(`/risk/committee/${committeeId}/refresh`,{method:'POST'});await load()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  const consent=async()=>{setBusy(true);setError('');try{await api(`/risk/committee/${committeeId}/consent`,{method:'POST',body:JSON.stringify({accepted:true})});await load()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  const confirmDeposit=async(id:string)=>{const txnRef=refs[id]?.trim();if(!txnRef)return;setBusy(true);setError('');try{await api(`/committees/${committeeId}/deposits/${id}/confirm`,{method:'POST',body:JSON.stringify({txnRef})});await load()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  const savePolicy=async()=>{setBusy(true);setError('');try{await api(`/risk/committee/${committeeId}/policy`,{method:'PATCH',body:JSON.stringify(policy)});await api(`/risk/committee/${committeeId}/refresh`,{method:'POST'});await load()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}};
  if(!risk)return <div className="risk-loading"><Gauge/>Building risk map…</div>;
  return <section className="risk-console"><header><div><span className="eyebrow">HALQA-RM · explainable model</span><h2>Circle risk cockpit</h2></div><RiskBadge score={risk.score} band={risk.band}/><RiskMascot score={risk.score}/></header>
    <div className="risk-dials"><RiskDial label="Investment" value={risk.investmentRisk}/><RiskDial label="Default" value={risk.defaultRisk}/><RiskDial label="Liquidity" value={risk.liquidityRisk}/><RiskDial label="Controls" value={10-risk.controlStrength} inverse/></div>
    <div className="risk-economics"><div><span>Expected-loss reserve</span><b>{(risk.expectedLossBps/100).toFixed(2)}%</b></div><div><span>Required early-turn deposit</span><b>{money(risk.depositRequiredPaisa)}</b></div><div><span>Downside profit</span><b>{money(projection?.downsideProfitPaisa||0)}</b></div><div><span>Expected profit</span><b>{money(projection?.expectedProfitPaisa||0)}</b></div></div>
    <div className="factor-list">{risk.factors.map(factor=><article key={factor.key}><div><b>{factor.label}</b><span>{factor.evidence}</span></div><strong>{factor.score.toFixed(1)}</strong><div className="factor-bar"><i style={{width:`${factor.score*10}%`}}/></div></article>)}</div>
    {host&&risk.committeeStatus==='FORMING'&&<section className="risk-policy-editor"><div><span className="eyebrow">Host-configurable · locks at start</span><h3>Risk mandate: {policy.targetRiskScore}/10</h3><p>Schemes above this ceiling are blocked by the API.</p></div><input type="range" min="1" max={risk.mode==='ROTATING'?3:risk.mode==='HYBRID'?6:8} step="1" value={policy.targetRiskScore} onChange={event=>setPolicy({...policy,targetRiskScore:+event.target.value})}/><div className="risk-policy-controls"><label>Payout buffer <input type="number" min="0" max="30" value={policy.payoutBufferBps/100} onChange={event=>setPolicy({...policy,payoutBufferBps:+event.target.value*100})}/><span>%</span></label><label>Liquidity reserve <input type="number" min="5" max="40" value={policy.liquidityReserveBps/100} onChange={event=>setPolicy({...policy,liquidityReserveBps:+event.target.value*100})}/><span>%</span></label><label>Late penalty <input type="number" min="0" max="10" value={policy.latePenaltyBps/100} onChange={event=>setPolicy({...policy,latePenaltyBps:+event.target.value*100})}/><span>%</span></label></div><button className="primary" disabled={busy} onClick={savePolicy}>Save risk mandate</button></section>}
    {deposits.length>0&&<div className="deposit-board"><header><b>Graduated security deposits</b><span>Recorded external commitments</span></header>{deposits.map(deposit=><article key={deposit.id}><div><b>{deposit.membership.user.fullName}</b><span>Position #{deposit.membership.turnPosition} · {money(deposit.amountPaisa)}</span></div><strong className={`status status-${deposit.status.toLowerCase()}`}>{deposit.status}</strong>{host&&deposit.status==='PENDING'&&<div className="deposit-confirm"><input className="field" value={refs[deposit.id]||''} onChange={event=>setRefs({...refs,[deposit.id]:event.target.value})} placeholder="External transfer reference"/><button className="secondary" disabled={busy||!refs[deposit.id]?.trim()} onClick={()=>confirmDeposit(deposit.id)}>Confirm</button></div>}</article>)}</div>}
    <div className="risk-actions"><div>{risk.recommendations.map(item=><p key={item}><AlertTriangle/>{item}</p>)}</div><div className="consent-card">{risk.consent?.status==='ACCEPTED'?<><CheckCircle2/><b>Risk terms accepted</b><span>Your acknowledgement is locked to this policy version.</span></>:<><Shield/><b>You control your participation</b><span>Accept the disclosed allocation, liquidity and default controls before this circle starts.</span><button className="primary" disabled={busy} onClick={consent}>I understand & accept</button></>}{host&&<button className="secondary" disabled={busy} onClick={refresh}><RefreshCw/>Recalculate</button>}</div></div>
    {error&&<div className="error-box">{error}</div>}<footer><Sparkles/>Model {risk.modelVersion}. It estimates exposure; it does not guarantee returns or prevent loss.</footer></section>;
}

function RiskDial({label,value,inverse=false}:{label:string;value:number;inverse?:boolean}){const shown=Math.max(0,Math.min(10,value));return <div className="risk-dial" style={{'--risk-angle':`${shown*36}deg`} as React.CSSProperties}><div><strong>{inverse?(10-shown).toFixed(1):shown.toFixed(1)}</strong><span>/10</span></div><b>{label}</b></div>}
