# -*- coding: utf-8 -*-
"""Work register part 2: sections E to R, everything that is not the interface."""

E = ("E", "Structural removals arising from the design changes",
     "Each construct below implements the previous design and must be gone before the merchant "
     "services agreement is executed.", [
    ("Set SIMPLE_MODE to true, withdrawing the vault, turn market and earning engines from the build", "halqa-web/src/config.ts:21"),
    ("Delete the turn premium ledger entry from buyer to seller", "routes/exchange.ts:156"),
    ("Delete the ten per cent marketplace fee taken on that premium", "routes/exchange.ts:157"),
    ("Remove premiumPaisa from listing creation", "routes/exchange.ts:69"),
    ("Remove competitive bidding on listings", "routes/exchange.ts:95"),
    ("Remove the fifty per cent of payout premium ceiling, now redundant", "routes/exchange.ts:84"),
    ("Retain the swap itself as a zero premium exchange on every tier", "routes/exchange.ts"),
    ("Remove earlyFeeBps from the create schema and every dependent branch, fourteen occurrences", "routes/committees.ts"),
    ("Remove the engine copy describing an early fee paid to other members", "routes/committees.ts:326"),
    ("Remove dividendPooled and the patience weighted split between members", "routes/committees.ts, schema.prisma"),
    ("Remove prizeDrawEnabled from the schema, the create route and round processing", "schema.prisma:357, routes/committees.ts:203"),
    ("Delete bidAprBps", "lib/hyper.ts:109"),
    ("Delete MAX_APR_BPS", "lib/hyper.ts:59"),
    ("Delete MAX_DAY_ONE_PAISA", "lib/hyper.ts:61"),
    ("Rewrite the hyper header comment, which presently describes a priced advance and an annualised ceiling", "lib/hyper.ts:1"),
    ("Re express the hyper seat price as a flat fee payable to Halqa rather than a bid between members", "lib/hyper.ts"),
    ("Unmount the vault route until the distributor registration exists", "app.ts:139"),
    ("Stop populating accruedYieldPaisa on security deposits", "schema.prisma:504, routes/protection.ts"),
    ("Stop creating payout holdbacks", "schema.prisma:521"),
    ("Gate the float sweep and the mudarib fee behind the distributor registration", "lib/sukoon.ts:23"),
    ("Remove the vault auto cover path from the delinquency pass", "services/delinquency.ts"),
    ("Remove rate and cover copy from six front end files", "rafa-knowledge.ts, format.ts, HyperPage.tsx, ProfilePage.tsx, VaultPage.tsx, preview.ts"),
    ("Remove the Halqa cover facility from the fee book", "lib/fee-book.ts"),
    ("Confine asset committee code behind a flag pending the leasing structure", "lib/asset-committee.ts, AssetPage.tsx"),
])

F = ("F", "Structural additions arising from the same changes", "", [
    ("Seat graded fee payable to Halqa, implementing the grid by instalment size and roster size", "lib/fee-book.ts"),
    ("Correct the per instalment fee constant, which presently stands at Rs 50 against a directed grid of Rs 100 to Rs 500", "lib/fee-book.ts"),
    ("Flat fee rule on the daily cadence, asserted in code so a graded fee cannot be configured there", "lib/hyper.ts"),
    ("Three way split engine: contribution, takaful contribution and service fee, each to its own ledger account", "new lib/split.ts"),
    ("Assert identity one at creation: pot equals contribution multiplied by the number of rounds", "routes/committees.ts"),
    ("Assert identity two at creation: roster equals members collecting each period multiplied by the number of periods", "routes/committees.ts"),
    ("Points ledger, issued by Halqa, as compensation to later seats", "new model"),
    ("Fee waiver credit, issued by Halqa, as compensation to later seats", "new model"),
    ("Redemption path for points and waivers against future fees", "routes/rewards.ts"),
    ("Host required on every circle, including daily cadence circles", "routes/committees.ts"),
    ("Host accountability record: who admitted each member to the roster", "new model"),
    ("Seat price display that states a fee in rupees and never a rate", "components"),
    ("Bureau consent capture as a separate screen naming the bureau and the request", "new page"),
    ("Bureau consent record hashed and timestamped on the pattern of the undertaking", "routes/agreements.ts"),
    ("Adverse action pack: the report relied on, the bureau name, address and telephone number, the statutory summary of rights and a statement that the bureau did not decide", "new page"),
    ("Review and gate member visible credit scores inside a circle", "CommitteePage.tsx"),
    ("Fee schedule surface stating every charge before a member commits", "FeesPage.tsx"),
    ("Correct the discount constants to eighty per cent for a cheque, fifty per cent for verified income, and a mandatory salary account", "lib/discounts.ts"),
])

G = ("G", "Collection, mandates and rails", "", [
    ("Implement tier one: a Raast request to pay, issued on the due date and settled on one approval", "new lib/raast.ts"),
    ("Implement tier two: collection against a token mandate held by the aggregator", "new lib/mandate.ts"),
    ("Implement tier three: manual recording against a reference, confirmed by the host", "routes/payments.ts"),
    ("Select the tier automatically by cadence, instalment size and the member own history", "new lib/collection-policy.ts"),
    ("Mandate register: account, ceiling, cadence, the text authorised, the time and the address", "new model"),
    ("Mandate authorisation flow, with the terms stated on their own screen", "new page"),
    ("Mandate cancellation inside the application, effective without a call or a form", "new page"),
    ("Advance notice where an amount will differ from the amount stated at authorisation", "new job"),
    ("Confirmation to the member of every collection taken under a mandate", "new job"),
    ("Daily mandate run, sharded, idempotent and resumable", "new job"),
    ("Retry policy for a failed mandate collection, with a stated schedule and a ceiling on attempts", "new job"),
    ("Reason codes for every failure, mapped to a sentence the member understands", "new lib"),
    ("Arrears recorded against the round, never as a negative balance held by Halqa", "routes/payments.ts"),
    ("Assertion in code that no member balance can be created", "routes/payments.ts"),
    ("Reconciliation against the aggregator settlement report, on a schedule", "new job"),
    ("Exception queue for reconciliation breaks", "new admin page"),
    ("Refund and reversal path through the same rail, with the ledger entry reversed with it", "routes/payments.ts"),
    ("Dispute suspends the mandate while it is open", "routes/payments.ts"),
    ("Idempotency key on every settlement, enforced at the database level", "schema.prisma"),
    ("Signed callback verification on every provider confirmation", "routes/payments.ts"),
    ("Circuit breaker on persistent provider failure, directing members to another rail", "lib/payment-provider.ts"),
    ("Title inquiry before an account anchors collection", "lib/payment-provider.ts"),
    ("Rail cost display before a charged rail is chosen", "PayPage.tsx"),
    ("Rail selection policy documented against instalment size, since a percentage rail consumes a rising share of a flat fee", "documentation"),
    ("Consolidated daily notice on the daily cadence, one message rather than one per member per day", "new job"),
    ("Merchant services agreement executed with a licensed aggregator", "commercial"),
    ("Mandate facility added to that agreement as a commercial term", "commercial"),
    ("Sandbox integration completed and signed off", "integration"),
    ("Production credentials held in the managed secret store", "infrastructure"),
    ("Live rail enabled behind a flag, with a staged rollout", "lib/payment-provider.ts"),
    ("Settlement account opened in the company name for fee revenue only", "commercial"),
    ("Daily settlement report ingested automatically rather than by hand", "new job"),
    ("Payment operations runbook written and rehearsed", "documentation"),
    ("Remove the live branch that throws not implemented once the rail is connected", "lib/payment-provider.ts"),
])

H = ("H", "Takaful cover", "", [
    ("Corporate insurance agent registration with the Commission", "registration"),
    ("Distribution agreement with a licensed takaful operator", "commercial"),
    ("Product terms agreed: what is covered, what is excluded, and how it is priced", "commercial"),
    ("Takaful contribution taken as a fixed part of every daily payment", "lib/split.ts"),
    ("Contribution remitted to the participants risk fund and never held by Halqa", "lib/split.ts"),
    ("Separate ledger account for the risk fund, reconciled separately", "ledger"),
    ("Cover offered at creation and at join on other cadences, priced per member", "new page"),
    ("Cover certificate issued to the member", "new page"),
    ("Claim submission with the payment record attached as evidence", "new page"),
    ("Claim status visible to the member and to the host", "new page"),
    ("Commission from the operator recorded as Halqa revenue and disclosed to the member", "ledger"),
    ("Surplus and deficit treatment documented for the member: surplus belongs to participants, deficit is met by an operator advance", "content"),
    ("Assertion in code that Halqa never promises to pay on another member loss", "review"),
    ("Counsel review of the agency arrangement before cover is offered", "legal"),
])

I = ("I", "Savings, trustee and asset manager", "", [
    ("SECP mutual fund distributor registration", "registration"),
    ("Distribution agreement with a licensed asset management company", "commercial"),
    ("Confirmation that the trust is constituted by deed on paper between the manager and the trustee", "legal"),
    ("Money path built member to trustee collection account, never through Halqa", "integration"),
    ("Units issued in the member own name and held in the member own account", "integration"),
    ("Execution only interface: a menu, with nothing recommended", "new page"),
    ("Distribution commission recorded as Halqa revenue and disclosed", "ledger"),
    ("No share of fund profit and no management fee, asserted in the agreement", "commercial"),
    ("Redemption path back to the member own account", "new page"),
    ("Returns stated as indicative and never guaranteed, with the fund named", "content"),
    ("Electronic Transactions Ordinance section 31(1)(c) checked: no individual circle constituted as an express trust on an electronic signature", "legal"),
    ("Vault route remounted only once the registration is in hand", "app.ts:139"),
])

J = ("J", "Credit data", "", [
    ("Subscriber agreement with TASDEEQ, with DataCheck as the alternate", "commercial"),
    ("Consent wording drafted to constitute Halqa the member duly constituted attorney", "legal"),
    ("Bureau request made only on a member instruction, enforced in code", "new lib"),
    ("Instruction record hashed, timestamped and addressed", "routes/agreements.ts"),
    ("Bureau report stored separately from the internal score and on its own scale", "schema.prisma"),
    ("Adverse action obligation implemented before any score based restriction operates", "new page"),
    ("Disclosure limits reviewed: bureau derived information not shown to other members", "CommitteePage.tsx"),
    ("Dispute route to the bureau correction process, with the entry marked while open", "new page"),
    ("Internal score explained to the member in terms of their own record", "CreditPage.tsx"),
    ("Score bands documented and applied only to which seats may be claimed", "lib/score.ts"),
    ("Write back of Halqa payment history held until the Federal Government notifies furnishers that are not credit institutions", "documentation"),
    ("State Bank register confirmed out of scope, being closed to non banks", "documentation"),
    ("Affordability gate held at one third of declared income", "lib/affordability.ts"),
    ("Exposure summed across every circle held", "lib/exposure.ts"),
    ("Forward liability measured at the point of seat selection", "lib/forward-liability.ts"),
    ("New member confinement to the final seats until two clean circles are completed", "lib/seat-bands.ts"),
])

K = ("K", "Registrations, legal instruments and governance", "", [
    ("SECP incorporation as a private limited company", "registration"),
    ("Memorandum object clause drafted to the restructured model", "legal"),
    ("National Tax Number from the Federal Board of Revenue", "registration"),
    ("Provincial sales tax registration", "registration"),
    ("Company bank account for Halqa own revenue", "commercial"),
    ("Trademark filing with the Intellectual Property Organisation", "registration"),
    ("Corporate Verisys agreement with NADRA", "commercial"),
    ("Member undertaking reviewed by counsel and framed as a liquidated demand", "legal"),
    ("Mutual guarantee reviewed by counsel as a separate member to member instrument", "legal"),
    ("Collection mandate text reviewed by counsel, stating amount, cadence, ceiling and cancellation", "legal"),
    ("Arbitration clause naming the dispute route before a dispute arises", "legal"),
    ("Record only clause stating expressly that Halqa holds no member money", "legal"),
    ("Member agreement, privacy, cookies, advertising, community and fees, versioned together", "legal"),
    ("Written opinion of counsel on limb twelve of the financial institution definition", "legal"),
    ("Confirmation that no product surface proposes a payment determined by the drawing of a lot", "review"),
    ("Data protection position documented, including where records sit", "documentation"),
    ("Record retention schedule for identity and transaction records", "documentation"),
    ("Complaints procedure published", "documentation"),
    ("Terms acceptance recorded with the version, the hash, the address and the time", "routes/agreements.ts"),
    ("Board and shareholding structure settled before the first external agreement", "corporate"),
    ("Insurance for the company itself, separate from member cover", "commercial"),
    ("Confirmation in writing that no regulatory approval is sought and no sandbox participation is pursued", "documentation"),
])

L = ("L", "Data, platform and the path to one hundred thousand members", "", [
    ("Create the migration history; the project presently has no migrations directory at all", "prisma/migrations"),
    ("Write and apply the additive SQL for the two user columns that exist in code and not in production", "prisma"),
    ("Adopt a migrate deploy step in the release pipeline rather than pushing the schema", "pipeline"),
    ("Bound every unbounded query; fifty eight calls presently fetch without a limit", "halqa-api/src"),
    ("Add cursor pagination to every list endpoint", "halqa-api/src/routes"),
    ("Add an index for every list query and every foreign key that drives one", "prisma/schema.prisma"),
    ("Review every N plus one query introduced by nested includes", "halqa-api/src"),
    ("Add a connection pool sized for the serverless execution model", "prisma"),
    ("Move the delinquency sweep to a sharded job rather than one pass", "services/delinquency.ts"),
    ("Move payouts to a queue with retry and a dead letter path", "new queue"),
    ("Move notifications to a queue with rate limiting per member", "new queue"),
    ("Add idempotency to every job so a retry cannot double process", "jobs"),
    ("Add a scheduled job monitor that alerts when a run is missed", "monitoring"),
    ("Add caching for reference data rather than fetching it per request", "halqa-api/src"),
    ("Add a read path that does not touch the primary for heavy list views", "infrastructure"),
    ("Load test the collection path at one hundred thousand members and a daily cadence", "testing"),
    ("Load test the round close and payout path at the same scale", "testing"),
    ("Measure and record the cost per member per month at that scale", "documentation"),
    ("Confirm the serverless execution ceiling is not reached by any job", "infrastructure"),
    ("Add point in time recovery and an independent nightly copy", "infrastructure"),
    ("Rehearse a restore and record how long it takes", "operations"),
    ("Add structured logging with a request identifier carried end to end", "halqa-api/src"),
    ("Add error monitoring with alerting to a named person; there is presently none", "infrastructure"),
    ("Add performance monitoring on the payment and payout paths", "infrastructure"),
    ("Add uptime monitoring on the application, the API and the rails", "infrastructure"),
    ("Add a public status page", "infrastructure"),
    ("Add a staging environment with its own database", "infrastructure"),
    ("Add a documented rollback procedure", "operations"),
    ("Add a feature flag service so a surface can be withdrawn without a deploy", "infrastructure"),
    ("Review the region placement of the database against the users it serves", "infrastructure"),
    ("Add a data export job that produces a member record in full", "new job"),
    ("Add a data deletion job that honours a closure request", "new job"),
    ("Add an append only audit log, retained separately from the application database", "infrastructure"),
    ("Add a double entry assertion that debits equal credits, run on a schedule", "new job"),
    ("Add a ledger integrity check against the settlement report", "new job"),
    ("Add a bundle size budget and enforce it in the build", "pipeline"),
    ("Measure and improve first contentful paint on a low end handset", "halqa-web"),
    ("Add an offline path for reading a schedule and a receipt", "halqa-web"),
    ("Add a service worker with a considered cache policy", "halqa-web"),
    ("Confirm the application works on a two gigabyte handset over a third generation connection", "testing"),
])

M = ("M", "Security", "", [
    ("Correct the permissions policy header, which presently disables the camera and breaks CNIC capture in production", "halqa-web/vercel.json:11"),
    ("Review the content security policy and remove any unsafe directive", "halqa-web/vercel.json"),
    ("Confirm strict transport security across the domain", "halqa-web/vercel.json"),
    ("Confirm the cross origin policy admits only the application origins", "halqa-api/src/app.ts"),
    ("Rate limit every route, per member and per address, tighter on authentication", "halqa-api/src"),
    ("Add a bot challenge before an account is created", "routes/auth.ts"),
    ("Add signup velocity limits per device and per address", "routes/auth.ts"),
    ("Confirm every route checks membership, hosting or ownership before acting", "halqa-api/src/routes"),
    ("Confirm every request is validated against a schema before reaching business logic", "halqa-api/src/routes"),
    ("Confirm internal fields never reach the client", "halqa-api/src"),
    ("Move every credential into a managed store and rotate on a schedule", "infrastructure"),
    ("Encrypt identity images at rest and log every access", "infrastructure"),
    ("Confirm rail tokens are held by the aggregator and never stored by Halqa", "lib/payment-provider.ts"),
    ("Add server side session revocation and a device list the member controls", "routes/auth.ts"),
    ("Add step up authentication before a payout destination is changed", "routes/account.ts"),
    ("Add step up authentication before a mandate is authorised", "new route"),
    ("Add anomaly detection on collection destination changes", "new job"),
    ("Separate administrative access from application access, in named accounts", "infrastructure"),
    ("Require two factor authentication on hosting, database and domain accounts", "infrastructure"),
    ("Add dependency scanning to the build and fail on high severity", "pipeline"),
    ("Add secret scanning across the repository and its history", "pipeline"),
    ("Add static analysis for injection and authorisation defects", "pipeline"),
    ("Commission a penetration test before real money moves", "external"),
    ("Write an incident response plan with a named owner", "documentation"),
    ("Write a breach notification procedure", "documentation"),
    ("Add a vulnerability disclosure route", "documentation"),
    ("Add sanctions and politically exposed person screening at onboarding", "new lib"),
    ("Add ongoing monitoring of patterns against the declared profile", "new job"),
    ("Add fraud rules for repeated identity submissions and unusual account linking", "new lib"),
    ("Add the capability to produce a suspicious transaction report if the obligation is ever held", "new job"),
])

N = ("N", "Testing and release", "", [
    ("Add a test suite for the API; there is presently none in the service", "halqa-api"),
    ("Unit test the split engine against both hyper configurations", "testing"),
    ("Unit test the two identities and confirm a breaking configuration is refused", "testing"),
    ("Unit test the fee grid at every band", "testing"),
    ("Unit test the discount grid, including that discounts do not stack", "testing"),
    ("Unit test the threshold engine at green, amber and red", "testing"),
    ("Unit test the exit ladder arithmetic", "testing"),
    ("Unit test the delinquency ladder at each step", "testing"),
    ("Unit test set off where a member collects and owes in the same round", "testing"),
    ("Unit test idempotency on settlement", "testing"),
    ("Integration test the whole collection path against the aggregator sandbox", "testing"),
    ("Integration test the payout path", "testing"),
    ("Integration test mandate authorisation, variation and cancellation", "testing"),
    ("End to end test the twenty most common member journeys", "testing"),
    ("End to end test the host journeys", "testing"),
    ("Visual regression test every screen at three widths", "testing"),
    ("Accessibility test every screen against the published criteria", "testing"),
    ("Add type checking, linting and tests as required checks on every change", "pipeline"),
    ("Add a preview deployment for every change", "pipeline"),
    ("Add a release checklist and require sign off", "process"),
    ("Add a staged rollout mechanism", "pipeline"),
    ("Add a kill switch for the collection job", "operations"),
    ("Record a manual test script for the journeys automation does not cover", "documentation"),
    ("Run the full suite against production data shapes before the first live collection", "testing"),
])

O = ("O", "Content, language and accessibility", "", [
    ("Write every screen in plain language for a member with no financial background", "content"),
    ("Remove every term that implies Halqa holds money", "content"),
    ("Remove every term that implies a rate, a return or an advance", "content"),
    ("Write the Urdu translation of every string, by a translator rather than by machine", "content"),
    ("Add a language chooser and remember the choice", "SettingsPage.tsx"),
    ("Confirm the layout holds when a string is twice as long", "testing"),
    ("Write the error message for every failure reason, in both languages", "content"),
    ("Write the empty state for every list, in both languages", "content"),
    ("Write the help article for every feature", "content"),
    ("Write the onboarding explanation of what a committee is", "content"),
    ("Write the explanation of the three way split", "content"),
    ("Write the explanation of the mandate and how to cancel it", "content"),
    ("Write the explanation of the fee and why it is flat", "content"),
    ("Write the explanation of cover and who writes it", "content"),
    ("Write the explanation of the credit score and what moves it", "content"),
    ("Give every interactive element an accessible name", "components"),
    ("Give every image and icon alternative text or an explicit hidden marking", "components"),
    ("Confirm every tap target meets the minimum size", "components"),
    ("Confirm colour is never the only carrier of meaning", "components"),
    ("Confirm contrast on every text and control against the background", "components"),
    ("Add a visible focus state to every interactive element", "components"),
    ("Confirm the application is usable with a screen reader end to end", "testing"),
    ("Confirm the application is usable at the largest system text size", "testing"),
    ("Add a text size preference inside the application", "SettingsPage.tsx"),
])

P = ("P", "Measurement", "", [
    ("Add product analytics with a defined event taxonomy", "infrastructure"),
    ("Instrument the signup funnel end to end", "analytics"),
    ("Instrument the identity verification funnel", "analytics"),
    ("Instrument circle creation and join", "analytics"),
    ("Instrument mandate authorisation", "analytics"),
    ("Instrument collection success by rail and by tier", "analytics"),
    ("Instrument first payment failure and recovery", "analytics"),
    ("Instrument default by circle, by cadence and by seat", "analytics"),
    ("Instrument the threshold bands across live circles", "analytics"),
    ("Build the operating dashboard: signups, active circles, collection rate, mandate coverage, default rate", "admin"),
    ("Build the risk dashboard: expected loss against accumulated cover, per circle", "admin"),
    ("Build the finance dashboard: fee revenue, rail cost, commission, net", "admin"),
    ("Define the weekly review and who attends it", "process"),
    ("Confirm no analytics event carries personal data into a third party", "review"),
])

Q = ("Q", "Application store and distribution", "", [
    ("Decide between a wrapped web application and a native build, and record the reason", "decision"),
    ("Register an Apple developer account in the company name", "registration"),
    ("Register a Google Play developer account in the company name", "registration"),
    ("Complete Apple financial services declarations", "compliance"),
    ("Complete Google Play financial services declarations, which are strict for Pakistani lending adjacent applications", "compliance"),
    ("Prepare the data safety declaration honestly against what is actually collected", "compliance"),
    ("Prepare the privacy policy at a public address", "content"),
    ("Prepare the account deletion route required by both stores", "compliance"),
    ("Produce the application icon at every required size", "design"),
    ("Produce store screenshots at every required size, in both languages", "design"),
    ("Write the store listing in both languages", "content"),
    ("Produce a preview video", "design"),
    ("Set up staged rollout and a rollback path on both stores", "operations"),
    ("Set up crash reporting on the released build", "infrastructure"),
    ("Set up a forced update mechanism for a critical fix", "infrastructure"),
    ("Confirm the build runs on the oldest supported operating system version", "testing"),
    ("Confirm deep links open the application rather than the browser", "testing"),
    ("Confirm push notification permission is requested at a sensible moment", "testing"),
    ("Prepare the review response process for store reviews", "process"),
    ("Prepare for the first store rejection, which is likely on a financial application", "process"),
])

R = ("R", "Support and operations", "", [
    ("Staff a support channel with a stated response time", "operations"),
    ("Write the runbook for a failed collection run", "documentation"),
    ("Write the runbook for a failed payout", "documentation"),
    ("Write the runbook for an aggregator outage", "documentation"),
    ("Write the runbook for a reconciliation break", "documentation"),
    ("Write the runbook for a disputed collection", "documentation"),
    ("Write the runbook for a circle that crosses the threshold", "documentation"),
    ("Write the escalation path and who is on it", "documentation"),
    ("Define the hardship path and who may grant it", "process"),
    ("Define the write off authority and its ceiling", "process"),
    ("Define the removal review, so a host decision can be appealed", "process"),
    ("Train whoever answers support on what Halqa may and may not say about money", "process"),
    ("Confirm no process permits a collections telephone call", "review"),
    ("Confirm no process permits contacting a third party about a member debt", "review"),
    ("Record every complaint with its outcome", "operations"),
    ("Review the register itself monthly against what has shipped", "process"),
])

SECTIONS_2 = [E, F, G, H, I, J, K, L, M, N, O, P, Q, R]
