# -*- coding: utf-8 -*-
"""Work register, section C, revision 3 (24 September 2026).

Built from an audit of every screen in the running application at phone width.
A tuple ('§', heading, preamble) opens a sub-part; an item is (text, location)
or (text, location, status). Status defaults to Open.
"""

S = '§'

C = ("C", "Every screen rebuilt to the wallet standard",
     "Every screen except Home is rebuilt to the standard of the JazzCash, Easypaisa and SadaPay "
     "applications, studied from their own store screenshots on 23 September 2026. The audit behind "
     "this section was made on 24 September 2026 by opening every screen of the running application "
     "at phone width: 28 screens, the five committee tabs, the sign-in and sign-up screens, and the "
     "25 components that render inside them. Home is the one screen kept as it stands. Sign up and "
     "sign in are redesigned from nothing. Part C1 applies to every screen and is checked on each "
     "one as it is rebuilt; parts C3 and C4 are done first, because C3 is a legal exposure and C4 "
     "is a screen that does not open.", [

    (S, "C1. Rules that apply to every screen", ""),
    ("No bezels: no bordered or framed container around a section, and never a card inside a card. Surfaces are separated by fill and space", "all screens"),
    ("No rounded pill or badge shapes, under the standing design rule. Buttons, chips, filters and status labels use square or lightly rounded corners; status is an icon, a colour and a word. The component set built on 23 September uses pill buttons and pill badges and is corrected first", "system.css, all screens"),
    ("No emojis in any screen, share text or notification. The country flag in the number field is the one the app shows today; the API's document verification page carries two symbols", "PhoneInput.tsx:13, halqa-api/src/app.ts:106"),
    ("No playful or self-referential copy: the assistant's greeting lines, exclamation marks, the tab title \"Committee savings, made rewarding\", the sign-in slogan, and the error screen's \"not a ledger one\"", "RafaBot.tsx, rafa-knowledge.ts, index.html, AuthPage.tsx, ErrorBoundary.tsx"),
    ("No over-explaining: at most one line of supporting text under a title. Every explanatory paragraph is cut, or moved behind a single How it works link", "all screens"),
    ("No list-of-rows navigation. A screen whose job is to send the member somewhere becomes an icon grid and cards, in the manner of the JazzCash and Easypaisa inner pages. Rows stay only where the content is itself a ledger: payments, members, turns", "ProfilePage, SettingsPage, VerifyPage, ReferPage, FeesPage, AutoPayPage"),
    ("No eyebrow labels above titles and no capitalised section labels; nine files carry them", "AgreementGate, Appearance, CnicCapture, CollectionOrder, ExitSheet, JoinSheet, AuthPage, CommitteePage, CreateCirclePage"),
    ("No stack of equal-weight panels. A screen opens with its one answer, then the evidence, then the actions. The committee's first tab stacks six panels", "CommitteePage.tsx:79"),
    ("No decorative circles on any header, hero or band", "AuthPage, RewardsPage, VaultPage, HyperPage, CommitteePage"),
    ("No off-brand colour on a surface: the orange streak card, the blue status chip, the blue information rule", "RewardsPage, CommitteePage, MarketplacePage"),
    ("No raw undefined, NaN or null on screen. Seen on Rewards (Points NaN, Longest run undefined, NaN to go) and on the committee Safety tab (score undefined against every member). Every number and name passes through a guard", "format.ts, RewardsPage, ProtectionCenter"),
    ("No segmented control that wraps to two lines; the committee tabs do", "CommitteePage"),
    ("Row actions (Remove, Make default, Remind) open in a sheet from the row, instead of sitting as buttons under every row", "CardsPage, ProtectionCenter"),
    ("No truncated title in a header; the committee name is cut to \"Gulshan ...\"", "CommitteePage"),
    ("Every screen checked in dark mode as it is rebuilt, since the older stylesheets hard code white", "all screens"),

    (S, "C2. Sign up and sign in, redesigned from nothing",
     "The individual onboarding and identity screens are listed in section D. This part sets the flow and the standard they are built to."),
    ("Remove the demo credentials printed on the sign-in screen. The line has no environment guard, so \"+92 300 1234567 · halqa123\" is on the live page for anyone", "AuthPage.tsx:538"),
    ("Welcome screen: the mark, one line, and two actions, Create account and Sign in. No slogan, no capitalised strapline, no paragraph", "AuthPage"),
    ("Remove the green marketing banner that fills 40 per cent of every sign-in and sign-up screen", "AuthPage"),
    ("Sign in with phone number and PIN, as the wallets do. No password", "AuthPage"),
    ("Cut sign-up from ten steps to five: phone, code, name, CNIC, PIN. Address, work, bank account and review move to verification after the account exists, where they open seats rather than block entry", "AuthPage.tsx:48"),
    ("Drop the password step. The PIN is the credential on the device and a phone code recovers it", "AuthPage"),
    ("The question is the heading of each step, not \"Step 1 of 10\"; progress is a thin bar only", "AuthPage.tsx:542"),
    ("Phone entry: +92 fixed, numeric keypad, digits grouped as they are typed, no flag", "PhoneInput.tsx"),
    ("Code entry: six boxes, automatic advance, paste from the SMS, resend with a visible countdown, and a change number link", "AuthPage, otp step"),
    ("PIN set and confirm on a full screen numeric keypad of its own, matching the unlock screen", "AuthPage, PinLock"),
    ("CNIC step opens the camera capture first and typing second", "AuthPage, CnicCapture"),
    ("Remove the card-within-a-card frame around every step", "AuthPage"),
    ("Remove the nine-link website footer (Cookie Policy, Ad Choices, Advertising and the rest) from sign in; its links also run together with no spaces. Terms and privacy become one line under the final button", "LegalFooter.tsx"),
    ("One specific error per field, shown under that field, and a retry on network failure", "AuthPage"),
    ("Forgotten PIN: phone code, then a new PIN", "AuthPage"),
    ("Sign-up tested end to end against a staging API, since it cannot be tested on production without creating a real account", "testing"),

    (S, "C3. Retired terms still shown on screen",
     "These screens tell a member things the Legal Position says Halqa does not do. They are fixed before anything else in section C."),
    ("HYPER shows \"30 days · 7 collect a day · 210 members\" and \"Rs 500 a day for 30 days\". Replace with the two fixed configurations and the three way split", "HyperPage.tsx"),
    ("HYPER entry checks ask for \"Daily earnings, or a vault balance\" with a \"Vault minimum Rs 15,000\". Remove the vault", "HyperPage.tsx"),
    ("Fees lists an early-turn fee that \"goes to the other members\" and turn selling at \"whatever the buyer bids\". Remove both", "FeesPage.tsx"),
    ("Fees does not list the service fee at all. Add the flat fee per instalment by instalment size and roster size, and the hyper split", "FeesPage.tsx"),
    ("Pay says \"No charge to contribute. Raast is instant and free.\" State the fee on every payment", "PayPage.tsx"),
    ("The committee screen carries a chip reading \"Turn pricing · 1% early fee → late bonus\". Remove it from every circle", "ui.tsx TurnPricingChip, CommitteePage"),
    ("The committee Safety tab shows \"Payout holdback 15% — On\", \"Deposit held\" and \"Payout held back\". Remove them", "ProtectionCenter.tsx"),
    ("The committee Safety tab shows \"Credit-weighted turns — On\". That ordering was replaced by score bands; remove it", "ProtectionCenter.tsx"),
    ("The turn marketplace says Buy a turn, for sale, bid, and List one of my turns. Recast as a zero-price swap throughout, and rename the Home tile to Swap a turn", "MarketplacePage.tsx, HomePage.tsx"),
    ("The vault is still reachable by link, showing a \"Recorded balance\" earning \"11.19% a year\" and \"Cover a missed instalment, settled from this balance\". Make it unreachable until the distributor registration exists", "VaultPage.tsx, App.tsx"),
    ("Save for something promises the member will \"own it outright\" at Halqa's \"Rs 50 a month\". Hold it until the leasing structure exists", "AssetPage.tsx"),
    ("About states \"What a member pays Halqa: Rs 0\" and calls Halqa \"a record that cannot be argued with\"", "AboutPage.tsx"),
    ("Remove every remaining use of record, recorded or recording to describe what Halqa is", "all screens"),

    (S, "C4. Screens that crash", ""),
    ("Support crashes on open with \"Something broke on this screen\": it reads tickets.length from an unchecked response", "SupportPage.tsx:62"),
    ("Statement crashes on open: it reads totals.paidInPaisa from an unchecked response", "StatementPage.tsx:68"),
    ("Limits crashes on open", "LimitsPage.tsx:36"),
    ("Devices crashes on open", "DevicesPage.tsx:31"),
    ("Preview mode has no data for these four endpoints, which is what exposes the missing guards. Add it, since preview is the mode used for demonstrations", "preview.ts"),

    (S, "C5. Screen by screen", ""),
    ("Home: fix the truncated due in figure, which reads 2 days, 23 and stops", "HomePage.tsx"),
    ("Home: replace total recorded with a phrase that names the figure", "HomePage.tsx", "Done"),
    ("Home: state what the member owes next, and when, as the first thing on the screen", "HomePage.tsx"),
    ("Home: search field in the header, as both reference applications carry", "HomePage.tsx", "Done"),
    ("Home: customisable action grid with an edit control, as JazzCash does", "HomePage.tsx"),
    ("Home: reduce the grid to actions used weekly and move the rest behind a More tile", "HomePage.tsx"),
    ("Home: every grid tile the same icon size, label length and tap target", "HomePage.tsx"),
    ("Home: New and Popular badges inside the tile bounds, and then replaced, since badges fall under the standing rule", "HomePage.tsx", "Partly done"),
    ("Home: activity grouped by date", "HomePage.tsx"),
    ("Home: each activity row opens its receipt", "HomePage.tsx"),
    ("Home: circles held as a horizontal card carousel rather than stacked cards", "HomePage.tsx"),
    ("Home: pull to refresh", "HomePage.tsx"),
    ("Home: a skeleton for every block rather than a full screen spinner", "HomePage.tsx"),
    ("Committees: design the single item case, which leaves half the screen empty", "CirclesPage.tsx"),
    ("Committees: committee cards at full contrast; they read as disabled", "CirclesPage.tsx", "Done"),
    ("Committees: search across the circles held", "CirclesPage.tsx"),
    ("Committees: filters for status, cadence and role", "CirclesPage.tsx"),
    ("Committees: sort by next due date, amount and name", "CirclesPage.tsx"),
    ("Committees: design the Discover tab, an unstyled list today", "CirclesPage.tsx"),
    ("Committees: design the zero circles empty state", "CirclesPage.tsx"),
    ("Committee: header uses a grey circle back button, cuts the name to \"Gulshan ...\" and carries a Member view pill. Rebuild on the standard page header", "CommitteePage.tsx"),
    ("Committee: in preview the hero says \"Your turn is 1 of 12\" while the order below shows the member at turn 3, and reads \"Turn 4 of 2\". Confirm against production data and correct the formula", "CommitteePage.tsx"),
    ("Committee: the Running status sits in a blue pill", "CommitteePage.tsx"),
    ("Committee: the loading state that never resolved when a circle is opened by link", "CommitteePage.tsx", "Done"),
    ("Committee: replace the six second polling loop with a subscription, or lengthen it with backoff", "CommitteePage.tsx:261"),
    ("Committee: a clear payment state per member, with a filter for unpaid", "CommitteePage.tsx"),
    ("Committee: the member's own position and next due date above everything else", "CommitteePage.tsx"),
    ("Committee: chat in its own tab rather than a section in a long scroll", "CommitteePage.tsx"),
    ("Committee: an unread marker on the chat tab", "CommitteePage.tsx"),
    ("Committee: a members tab with standing, seat and payment history", "CommitteePage.tsx"),
    ("Committee: a rules tab restating the configuration the member agreed to", "CommitteePage.tsx"),
    ("Committee, turns tab: six stacked panels become one hero, the turn strip, and the members grid", "CommitteePage.tsx:79"),
    ("Committee, safety tab: a list of fourteen switches becomes three cards: what protects this circle, what happens when someone is late, and the member's own standing", "ProtectionCenter.tsx"),
    ("Committee, payments tab: rebuilt to the rules", "CommitteePage.tsx"),
    ("Committee, messages tab: a chat layout in the manner of the wallets", "CommitteePage.tsx"),
    ("Credit report: remove the assistant bubble that covered the affordability section", "CreditPage.tsx", "Done"),
    ("Credit report: last three instalments labelled with dates and amounts", "CreditPage.tsx"),
    ("Credit report: score chart with an axis, dates and a readable scale", "CreditPage.tsx"),
    ("Credit report: each score factor explained with the member's own figures", "CreditPage.tsx"),
    ("Credit report: internal score and any bureau figure separated and labelled", "CreditPage.tsx"),
    ("Credit report: the stat strip of three grey tiles inside a white card", "CreditPage.tsx"),
    ("Account: rebuilt as a grid of tiles under three headings, in place of the long list", "ProfilePage.tsx"),
    ("Account: the credit report control in the header as a real button", "ProfilePage.tsx"),
    ("Account: a sign out control, absent today", "ProfilePage.tsx"),
    ("Create a circle: uses its own header (a Back text link, an eyebrow, a small title) instead of the standard one", "CreateCirclePage.tsx"),
    ("Create a circle: the step chips are pills and the third is cut off", "CreateCirclePage.tsx"),
    ("Create a circle: \"Give the circle a name first\" shows before the member has typed anything", "CreateCirclePage.tsx"),
    ("Create a circle: full cost of the configuration, every fee included, before commitment", "CreateCirclePage.tsx"),
    ("Create a circle: validate each step before the next opens", "CreateCirclePage.tsx"),
    ("Create a circle: live preview of the schedule as the configuration changes", "CreateCirclePage.tsx"),
    ("Pay: the amount reads \"Rs 10000\", unformatted, with Rs sitting below the figure", "PayPage.tsx"),
    ("Pay: half the screen is empty; the rail choice or a keypad belongs there", "PayPage.tsx"),
    ("Pay: the three parts of the payment shown before the member confirms", "PayPage.tsx"),
    ("Pay: any rail charge shown before the rail is chosen", "PayPage.tsx"),
    ("Pay: pending, settled and failed states, with a reason on failure", "PayPage.tsx"),
    ("Schedule: in preview shows Nothing due while Home shows an instalment due in two days. Confirm against production data", "SchedulePage.tsx"),
    ("Schedule: a calendar as well as a list", "SchedulePage.tsx"),
    ("Statement: exportable as a file", "StatementPage.tsx"),
    ("Rewards: the orange streak card, the grey tiles inside a white card, and reward titles cut mid-word. Rebuild as a progress hero and a grid of reward tiles", "RewardsPage.tsx"),
    ("HYPER: rebuild as the two configuration cards side by side, with the entry checks as one compact progress figure", "HyperPage.tsx"),
    ("Activity: keep it as a ledger, and group each day's rows in one card instead of one card per row", "ActivityPage.tsx"),
    ("Payment methods: Remove and Make default buttons under every account move into a sheet; the buttons are pills", "CardsPage.tsx"),
    ("Verification: a progress figure and a grid of checks in place of two lists; remove the capitalised VERIFIED label", "VerifyPage.tsx"),
    ("Settings: a grid in place of the list; the footer links run together with no spaces", "SettingsPage.tsx, LegalFooter.tsx"),
    ("Appearance: remove the accent colour picker, a dead control since the themes were retired", "Appearance.tsx"),
    ("Appearance: the photo control renders as a letter and a broken icon", "Appearance.tsx"),
    ("Appearance: two titles on one screen (Look and feel, then Appearance and personalisation); theme and language chosen from pills", "Appearance.tsx"),
    ("Notifications: Mark everything read has its tick on a line of its own; groups are ordered oldest first", "NoticesPage.tsx"),
    ("Invite: the capitalised YOUR CODE label; the bottom button sits behind the tab bar", "ReferPage.tsx"),
    ("Auto-pay: the capitalised COLLECTED AUTOMATICALLY label", "AutoPayPage.tsx"),
    ("Turn marketplace: grey tiles inside a white card, and a blue information rule", "MarketplacePage.tsx"),
    ("Vault: no header and no back control", "VaultPage.tsx"),
    ("About: essay paragraphs become three short facts and one link", "AboutPage.tsx"),
    ("Error screen: one line and a retry, in place of \"Something broke on this screen, your data is safe, this is a display error, not a ledger one\"", "ErrorBoundary.tsx"),
    ("Search: kept; checked against C1", "SearchPage.tsx"),

    (S, "C6. Components", "Each is rebuilt to the rules in C1."),
    ("Turns you can take: layout rewritten on 23 September; its style is not yet applied and its copy still over-explains", "SeatEligibility.tsx", "Partly done"),
    ("Circle eligibility", "GroupCredit"),
    ("What you would still owe", "ForwardLiability.tsx"),
    ("Exit votes", "ExitVotes.tsx"),
    ("Collection order", "CollectionOrder.tsx"),
    ("Confirming window", "ConfirmingWindow.tsx"),
    ("Affordability", "Affordability.tsx"),
    ("Score simulator", "ScoreSimulator.tsx"),
    ("Fee schedule", "FeeSchedule.tsx"),
    ("Collection calendar", "CollectionCalendar.tsx"),
    ("Join by code", "JoinByCode.tsx"),
    ("Join sheet", "JoinSheet.tsx"),
    ("Exit sheet", "ExitSheet.tsx"),
    ("Agreements list", "MyAgreements.tsx"),
    ("Weekly undertaking overlay", "AgreementGate.tsx"),
    ("Protection centre", "ProtectionCenter.tsx"),
    ("Risk console", "RiskConsole.tsx"),
    ("Invite share", "InviteShare.tsx"),
    ("Host card", "HostCard.tsx"),
    ("Linked accounts and their manager", "LinkedAccounts.tsx, LinkedAccountsManager.tsx"),
    ("Add a payment source", "AddSource.tsx"),
    ("CNIC capture", "CnicCapture.tsx"),
    ("PIN lock", "PinLock.tsx"),
    ("Receipt", "Receipt.tsx"),
    ("Growth and projection charts", "PersonalGrowthChart.tsx, ProjectionChart.tsx"),
    ("Member status", "MemberStatus.tsx"),
    ("Committee photo prompt", "CommitteePage.tsx"),
    ("The assistant panel", "RafaBot.tsx"),
])

# Status of the items in sections A and B, by position within the section,
# as verified in the browser on 23 and 24 September 2026.
STATUS_A = {1:'Done', 2:'Done', 4:'Done', 6:'Partly done', 7:'Partly done', 8:'Partly done',
            9:'Done', 10:'Done', 11:'Partly done', 13:'Done', 14:'Partly done', 15:'Done',
            16:'Partly done', 17:'Done', 18:'Done', 19:'Done', 20:'Done', 21:'Partly done',
            23:'Partly done', 25:'Partly done', 26:'Partly done', 27:'Partly done',
            28:'Partly done', 29:'Partly done', 30:'Partly done', 31:'Partly done', 32:'Done'}
STATUS_B = {1:'Partly done', 2:'Done', 3:'Done', 4:'Done', 5:'Done', 6:'Done', 7:'Done',
            8:'Done', 9:'Done', 10:'Partly done', 11:'Done', 12:'Done', 13:'Partly done',
            15:'Done', 16:'Done', 17:'Done', 18:'Done', 20:'Partly done', 21:'Partly done',
            22:'Partly done'}
