# -*- coding: utf-8 -*-
"""Work register part 1: sections A to D, the interface."""

A = ("A", "Brand, theme and the visual system",
     "The application already carries a bright green ramp in its stylesheet. It is not applied "
     "consistently, five competing accent themes sit beside it, and the supporting material was "
     "drawn in a different palette entirely. This section makes one palette govern everything.", [
    ("Adopt the bright green ramp as the only brand palette, across the application, the maps, the deck and every document", "index.css"),
    ("Retire the pine, sand, clay, indigo and plum accent themes, which dilute the brand and triple the visual QA surface", "index.css:569"),
    ("Remove the accent picker from the appearance screen and reduce it to light and dark", "AppearancePage.tsx"),
    ("Publish the token set as the single source of truth: ramp, neutrals, status, radii, elevation, spacing", "new tokens.css"),
    ("Replace every hard coded colour literal in components with a token reference", "40 components"),
    ("Define three named elevations and delete every one off shadow value", "six stylesheets"),
    ("Define one spacing scale and remove every off scale margin and padding", "six stylesheets"),
    ("Define a type scale with named roles and remove every one off font size", "six stylesheets"),
    ("Select and self host one display typeface rather than relying on the system stack, which renders differently on every handset", "index.css:47"),
    ("Select and self host an Urdu typeface that sets Nastaliq correctly", "index.css"),
    ("Subset and preload both typefaces so the first paint does not shift", "index.html"),
    ("Normalise every icon to one family, one stroke weight and one grid size", "components"),
    ("Replace the mascot with a flat brand device, or remove it; in its present form it overlaps content on the home, committees, credit and account screens", "RafaBot.tsx"),
    ("Give the assistant a fixed entry point in the header rather than a floating character", "RafaBot.tsx"),
    ("Redraw the green header as a defined surface with a controlled edge rather than a slab carrying a stray lighter circle", "index.css:53"),
    ("Make the header treatment identical on every screen that uses one", "HomePage, CreditPage, ProfilePage"),
    ("Replace the blue credit score ring, which clashes with the brand, with the brand ramp", "CreditPage.tsx, ProfilePage.tsx"),
    ("Stop the score ring being clipped by the header edge on the account screen", "ProfilePage.tsx"),
    ("Replace the red outgoing arrows in the activity list, which read as errors, with a neutral treatment", "HomePage.tsx"),
    ("Establish a status colour convention and document it: success, warning, failure, information", "tokens"),
    ("Define one card component with a fixed radius, padding, border and elevation, and route every surface through it", "ui.tsx"),
    ("Stop nesting grey tiles inside white cards, which produces a muddy surface", "CreditPage.tsx"),
    ("Define one list row component with a title, an optional subtitle, an optional leading icon and an optional trailing control", "ui.tsx"),
    ("Make every list row either carry a subtitle or not, rather than mixing the two in one list", "ProfilePage.tsx"),
    ("Define one button component with primary, secondary, tertiary and destructive variants and three sizes", "ui.tsx"),
    ("Define one form field component with label, hint, error and disabled states", "ui.tsx"),
    ("Define one badge component and stop badges overlapping the tile above them", "HomePage.tsx"),
    ("Define a skeleton for every card, list and chart; the application presently carries five in total", "ui.tsx"),
    ("Define an empty state component with an illustration slot, a sentence and an action", "ui.tsx"),
    ("Define an error state component with a reason and a retry", "ui.tsx"),
    ("Add a dark theme and honour the system preference", "tokens"),
    ("Add a reduced motion preference and honour it in every transition", "tokens"),
    ("Produce a one page visual specification for anyone building a new screen", "documentation"),
    ("Fold the five stylesheets that accumulated outside the system into the token set and delete them", "styles-*.css"),
])

B = ("B", "Navigation and application chrome",
     "Three different navigation patterns are presently in use and the floating controls collide "
     "with content and with one another.", [
    ("Settle one navigation pattern: a large left aligned page title, a back affordance where one applies, and at most two trailing actions", "all pages"),
    ("Remove the centred bare title bar used on the committees screen", "CirclesPage.tsx"),
    ("Remove the grey circle back button used on the credit screen and adopt the standard affordance", "CreditPage.tsx"),
    ("Stop the join button overlapping the start a committee button on the committees screen", "CirclesPage.tsx"),
    ("Stop the join button label being cut off at the bottom of the viewport", "Shell.tsx"),
    ("Decide whether joining is a tab, a floating button or a grid action; at present it is all three", "Shell.tsx, HomePage.tsx"),
    ("Remove the vault tab while the surface is withdrawn", "Shell.tsx"),
    ("Reduce the tab bar to four destinations and give each a filled and an outline state", "Shell.tsx"),
    ("Add a search entry point to the home header, which both reference applications carry", "HomePage.tsx"),
    ("Add a notifications entry point with an unread count that clears on read", "HomePage.tsx"),
    ("Respect the safe area inset at the bottom on handsets with a gesture bar", "index.css"),
    ("Respect the safe area inset at the top on handsets with a notch", "index.css"),
    ("Give every screen a working hardware back behaviour", "App.tsx"),
    ("Preserve scroll position when returning to a list", "App.tsx"),
    ("Add a page transition that communicates depth rather than a hard swap", "App.tsx"),
    ("Add a loading indicator for navigation between lazy boundaries", "App.tsx"),
    ("Give every one of the twenty eight screens a deep link that restores its full state", "App.tsx"),
    ("Fix the committee deep link, which presently shows an unending loading indicator", "App.tsx, CommitteePage.tsx"),
    ("Add a context line inside a committee so the member knows which circle they are in", "CommitteePage.tsx"),
    ("Add a bottom sheet component and use it for secondary actions rather than navigating away", "ui.tsx"),
    ("Add a modal component with focus trapping and an escape route", "ui.tsx"),
    ("Add a confirmation pattern for destructive actions, with the consequence stated", "ui.tsx"),
])

C = ("C", "Screen by screen rebuild",
     "Each item below is a defect observed on the running application or a pattern taken from the "
     "two reference applications studied for this register. JazzCash presents a dark header "
     "carrying identity and balance above a customisable three column action grid, a card "
     "carousel and an edit control. Easypaisa presents a white header with a search field, a "
     "horizontal account card carousel, a three column action grid under a section heading, a "
     "story strip and a five tab bar.", [
    ("Home: fix the truncated due in figure, which presently reads 2 days, 23 and stops", "HomePage.tsx"),
    ("Home: replace total recorded with a phrase that names what the figure is", "HomePage.tsx"),
    ("Home: state what the member owes next, and when, as the first thing on the screen", "HomePage.tsx"),
    ("Home: add a search field in the header, as both reference applications do", "HomePage.tsx"),
    ("Home: make the action grid customisable with an edit control, as JazzCash does", "HomePage.tsx"),
    ("Home: reduce the action grid to the actions used weekly and move the rest behind a more tile", "HomePage.tsx"),
    ("Home: give every grid tile the same icon size, label length and tap target", "HomePage.tsx"),
    ("Home: move the new and popular badges inside the tile bounds", "HomePage.tsx"),
    ("Home: group the activity list by date, as both reference applications do", "HomePage.tsx"),
    ("Home: give each activity row a tappable receipt", "HomePage.tsx"),
    ("Home: present the circles held as a horizontal card carousel rather than stacked cards", "HomePage.tsx"),
    ("Home: add pull to refresh", "HomePage.tsx"),
    ("Home: add a skeleton for every block rather than a full screen spinner", "HomePage.tsx"),
    ("Committees: design the single item case, which presently leaves half the screen empty", "CirclesPage.tsx"),
    ("Committees: raise the contrast of the committee card, which presently reads as disabled", "CirclesPage.tsx"),
    ("Committees: add search across the circles the member holds", "CirclesPage.tsx"),
    ("Committees: add filters for status, cadence and role", "CirclesPage.tsx"),
    ("Committees: add sort by next due date, by amount and by name", "CirclesPage.tsx"),
    ("Committees: design the discover tab, which is presently an unstyled list", "CirclesPage.tsx"),
    ("Committees: design the zero circles empty state", "CirclesPage.tsx"),
    ("Committee: fix the loading state that never resolves when the circle is opened by link", "CommitteePage.tsx"),
    ("Committee: replace the six second polling loop with a subscription, or lengthen it with backoff", "CommitteePage.tsx:261"),
    ("Committee: give the round view a clear payment state per member and a filter for unpaid", "CommitteePage.tsx"),
    ("Committee: show the member their own position and next due date above everything else", "CommitteePage.tsx"),
    ("Committee: move the chat into its own tab rather than a section in a long scroll", "CommitteePage.tsx"),
    ("Committee: add an unread marker on the chat tab", "CommitteePage.tsx"),
    ("Committee: add a members tab carrying standing, seat and payment history", "CommitteePage.tsx"),
    ("Committee: add a rules tab restating the configuration the member agreed to", "CommitteePage.tsx"),
    ("Credit report: remove the assistant bubble that covers the affordability section", "CreditPage.tsx"),
    ("Credit report: label the last three instalments with dates and amounts", "CreditPage.tsx"),
    ("Credit report: give the score chart an axis, dates and a readable scale", "CreditPage.tsx"),
    ("Credit report: explain each score factor with the member own figures rather than in the abstract", "CreditPage.tsx"),
    ("Credit report: separate the internal score from any bureau figure and label which is which", "CreditPage.tsx"),
    ("Account: give every row a subtitle or none, consistently", "ProfilePage.tsx"),
    ("Account: make the credit report control in the header a real button rather than a translucent panel", "ProfilePage.tsx"),
    ("Account: group the rows under headings that match how a member thinks about them", "ProfilePage.tsx"),
    ("Account: add a sign out affordance, which is presently absent", "ProfilePage.tsx"),
    ("Create a circle: show the full cost of the configuration before commitment, including every fee", "CreateCirclePage.tsx"),
    ("Create a circle: validate each step before the next opens rather than at the end", "CreateCirclePage.tsx"),
    ("Create a circle: show a live preview of the schedule as the configuration changes", "CreateCirclePage.tsx"),
    ("Pay: show the three parts of the payment separately before the member confirms", "PayPage.tsx"),
    ("Pay: show any rail charge before the rail is chosen", "PayPage.tsx"),
    ("Pay: give the payment a clear pending, settled and failed state, with a reason on failure", "PayPage.tsx"),
    ("Schedule: present the schedule as a calendar as well as a list", "SchedulePage.tsx"),
    ("Statement: make the statement exportable as a file rather than only a screen", "StatementPage.tsx"),
    ("Authentication: rebuild passcode entry with a numeric keypad rather than a text field", "AuthPage.tsx"),
])

D = ("D", "Screens that do not exist and are required",
     "The application presently carries twenty eight screens. Every item below is a screen a "
     "member, a host or an administrator needs and cannot reach, because it was never built or "
     "because it exists only as a section inside another screen.", [
    ("Welcome and what the product is, shown before the number is asked for", "Onboarding"),
    ("Phone number entry, with the reason for the request stated", "Onboarding"),
    ("Passcode entry, with resend, a timer and a change number route", "Onboarding"),
    ("Set the application PIN", "Onboarding"),
    ("Confirm the application PIN", "Onboarding"),
    ("Forgotten PIN recovery", "Onboarding"),
    ("Biometric enrolment offer", "Onboarding"),
    ("Name and date of birth capture", "Onboarding"),
    ("Address and city capture", "Onboarding"),
    ("Occupation and employer capture", "Onboarding"),
    ("Income declaration, with the reason it is asked", "Onboarding"),
    ("Income verification upload", "Onboarding"),
    ("Income verification status and outcome", "Onboarding"),
    ("CNIC front capture with an alignment guide", "Identity"),
    ("CNIC back capture with an alignment guide", "Identity"),
    ("CNIC manual entry fallback", "Identity"),
    ("CNIC review and confirm before submission", "Identity"),
    ("Identity check in progress", "Identity"),
    ("Identity check failed, with the reason and the next step", "Identity"),
    ("Liveness capture instructions", "Identity"),
    ("Liveness capture", "Identity"),
    ("Verification levels: what each one opens", "Identity"),
    ("Bureau instruction, on a screen of its own", "Identity"),
    ("Bureau instruction confirmation and record", "Identity"),
    ("Adverse action disclosure pack", "Identity"),
    ("Linked accounts list", "Accounts and rails"),
    ("Add a bank account", "Accounts and rails"),
    ("Add a wallet account", "Accounts and rails"),
    ("Account title verification in progress", "Accounts and rails"),
    ("Account title mismatch, with the route to correct it", "Accounts and rails"),
    ("Set the default collection account", "Accounts and rails"),
    ("Remove a linked account, with the consequences stated", "Accounts and rails"),
    ("Collection mandate explainer", "Accounts and rails"),
    ("Authorise a collection mandate", "Accounts and rails"),
    ("Mandate authorised confirmation", "Accounts and rails"),
    ("Mandate list, one row per circle", "Accounts and rails"),
    ("Vary a mandate ceiling", "Accounts and rails"),
    ("Cancel a mandate, with the consequences stated", "Accounts and rails"),
    ("Mandate cancelled confirmation", "Accounts and rails"),
    ("Mandate collection failed, with the reason and the manual route", "Accounts and rails"),
    ("Advance notice of a differing amount", "Accounts and rails"),
    ("Circle templates, for a member who does not know what to configure", "Circles"),
    ("Cadence chooser, with a plain explanation of each", "Circles"),
    ("Roster size chooser, with the pot shown live", "Circles"),
    ("Seat chooser, with each unavailable seat carrying its reason", "Circles"),
    ("Join sheet as a screen of its own", "Circles"),
    ("Split disclosure: what each part of the payment is for", "Circles"),
    ("Mutual guarantee signing", "Circles"),
    ("Undertaking signing", "Circles"),
    ("Signature capture", "Circles"),
    ("Agreement archive", "Circles"),
    ("Confirming window countdown", "Circles"),
    ("Withdraw before start", "Circles"),
    ("Waiting list position", "Circles"),
    ("Host admission queue", "Host"),
    ("Applicant detail, with standing and related accounts", "Host"),
    ("Admission decision record", "Host"),
    ("Roster fill request to Halqa", "Host"),
    ("Collection order assignment", "Host"),
    ("Circle policy settings", "Host"),
    ("Circle risk band explainer", "Host"),
    ("Mandate coverage across the roster", "Host"),
    ("Reminder composer", "Host"),
    ("Removal against the published test", "Host"),
    ("Member vote on a removal", "Host"),
    ("Host accountability record", "Host"),
    ("Circle dissolution", "Host"),
    ("Payment method chooser", "Money"),
    ("Payment confirmation with the full split", "Money"),
    ("Payment pending", "Money"),
    ("Payment failed, with the reason", "Money"),
    ("Receipt detail", "Money"),
    ("Receipt share", "Money"),
    ("Dispute a payment", "Money"),
    ("Dispute status", "Money"),
    ("Payout destination confirmation", "Money"),
    ("Payout released", "Money"),
    ("Payout receipt", "Money"),
    ("Shortfall explanation on a payout", "Money"),
    ("Set off explanation where a member collects and owes in the same round", "Money"),
    ("Partial payment record", "Money"),
    ("Arrears position, stated as owed to the round", "Money"),
    ("Fee schedule, the whole grid", "Money"),
    ("The fee applied to this circle", "Money"),
    ("Discount eligibility: cheque, income, salary account", "Money"),
    ("Guarantee cheque registration", "Money"),
    ("Late notice, step one", "Recovery"),
    ("Late notice, step two", "Recovery"),
    ("Late notice, step three", "Recovery"),
    ("Hardship declaration", "Recovery"),
    ("Revised date agreement", "Recovery"),
    ("Cure confirmation", "Recovery"),
    ("Restitution arithmetic", "Recovery"),
    ("Recovery case status", "Recovery"),
    ("Write off record", "Recovery"),
    ("Exit ladder chooser", "Exit"),
    ("Exit sheet with the arithmetic", "Exit"),
    ("Exit cooling window", "Exit"),
    ("Exit confirmation with PIN and face", "Exit"),
    ("Seat transfer to a replacement", "Exit"),
    ("Guarantee release", "Exit"),
    ("Points ledger, with the reason for each entry", "Rewards"),
    ("Waiver ledger", "Rewards"),
    ("Redemption against a future fee", "Rewards"),
    ("Redemption with a commerce partner", "Rewards"),
    ("Referral invitation and status", "Rewards"),
    ("Cover explainer, naming the operator", "Takaful"),
    ("Cover purchase", "Takaful"),
    ("Cover certificate", "Takaful"),
    ("Claim submission", "Takaful"),
    ("Claim status", "Takaful"),
    ("Savings explainer, naming the trustee and the manager", "Savings"),
    ("Savings subscription", "Savings"),
    ("Savings holding", "Savings"),
    ("Savings redemption", "Savings"),
    ("Help centre index", "Support"),
    ("Help article", "Support"),
    ("Contact support", "Support"),
    ("Complaint record", "Support"),
    ("Service status", "Support"),
    ("Devices and sessions", "Settings"),
    ("Notification preferences", "Settings"),
    ("Language chooser", "Settings"),
    ("Data export request", "Settings"),
    ("Account closure", "Settings"),
    ("Administrative console: circles at risk", "Administration"),
    ("Administrative console: reconciliation exceptions", "Administration"),
    ("Administrative console: identity queue", "Administration"),
    ("Administrative console: dispute queue", "Administration"),
    ("Administrative console: mandate failures", "Administration"),
])
